### ISSUE TITLE
[NEW]: Bitcoin price fluctuates wildly after false tweet

### ISSUE THREAD

**Issue by jvaskonen** [molly/web3-is-going-great#1005]
### Date

2023-10-16

### Description

The price of bitcoin surged 7% after Cointelegraph tweeted that BlackRock's bitcoin ETF had been approved by the SEC, only to return to its prior price after that was revealed to be incorrect.

### Links

https://www.vice.com/en/article/wxj7em/how-one-false-viral-tweet-cost-bitcoin-investors-dollar84-million-in-minutes

### Agreement

- [X] I irrevocably agree to release my contribution under the CC-BY 3.0 License

**Comment by molly** [comment]
Already included at https://web3isgoinggreat.com/?id=fake-etf-approval-news
