### ISSUE TITLE
[NEW]: Safemoon founders being charged with international fraud scheme

### ISSUE THREAD

**Issue by sandervankasteel** [molly/web3-is-going-great#1017]
### Date

2023-11-01

### Description

The DOJ is charging the founders of Safemoon with international fraud scheme in the district of New York.

From the the DOJ website: "Defendants Allegedly Misappropriated Millions of Dollars of Investors’ Funds for Their Own Use, Including the Purchase of Luxury Vehicles, Real Estate, and Personal Investments"

### Links

https://www.justice.gov/usao-edny/pr/founders-and-executives-digital-asset-company-charged-multi-million-dollar

### Agreement

- [X] I irrevocably agree to release my contribution under the CC-BY 3.0 License

### Attribution name

Sander van Kasteel

### Personal link

https://mastodon.online/@SuitedUpDev

**Comment by molly** [comment]
https://web3isgoinggreat.com/?id=safemoon-executives-charged-and-arrested
