### ISSUE TITLE
[EDIT] Safemoon grammar fix

### ISSUE THREAD

**Issue by R3Ked** [molly/web3-is-going-great#1018]
# Entry

Safemoon executives charged and arrested, November 1, 2023

# Changes

Change "SafeMoon, which promised buyers it would "safely go to the moon" by locking the liquidity pool so that its developers couldn't rug pull." to "SafeMoon promised buyers it would "safely go to the moon" by locking the liquidity pool so that its developers couldn't rug pull."

# Agreement

By submitting this issue, I irrevocably agree to release my contribution under the [CC-BY 3.0 License](http://creativecommons.org/licenses/by/3.0/deed.en_US). I agree that a hyperlink or URL is sufficient attribution under the Creative Commons license.

Please attribute this contribution to:

- 
- 

You can leave this blank if this is a change so small as to not be copyrightable.

**Comment by molly** [comment]
Thanks!
