### ISSUE TITLE
403 error when looking at any Twitter archive images (Google cloud)

### ISSUE THREAD

**Issue by Cobertos** [molly/web3-is-going-great#1019]
When I try to click on any image links from Twitter archived posts, I get a 403 forbidden.

Example 1: https://storage.cloud.google.com/tweet-archives/2023-10-16-2/2/assets/1-0.webp

From:  https://web3isgoinggreat.com/archive/2023-10-16-2/2

Example 2: https://storage.cloud.google.com/tweet-archives/2023-10-16-2/0/assets/0-0.webp

https://storage.cloud.google.com/tweet-archives/2023-10-16-2/0/assets/0-1.webp

https://storage.cloud.google.com/tweet-archives/2023-10-16-2/0/assets/1-0.webp

From: https://web3isgoinggreat.com/archive/2023-10-16-2/0

![Screenshot_20231104-234659](https://github.com/molly/web3-is-going-great/assets/6759176/fc9c5dfe-87a7-4460-8006-6093d2af7114)

Thanks!

**Comment by molly** [comment]
Well that's mortifying! Should be fixed now, but definitely feel free to reopen the issue if you're still seeing problems. Thanks for the report!
