### ISSUE TITLE
[NEW]: Yuga Labs Gives BYAC Holders Photokeratitis At Exclusive Party

### ISSUE THREAD

**Issue by CounterPillow** [molly/web3-is-going-great#1020]
### Date

2023-11-05

### Description

Yuga Labs held an exclusive party in Hong Kong for holders of Bored Ape Yacht Club NFTs. Unfortunately for the attendees, the venue used the wrong type of UV lamps, likely UV-C, which causes sunburn and Photokeratitis (more or less sunburn on the eye itself).

### Links

https://twitter.com/YallahHabibiBTC/status/1721191120074428825

https://fortune.com/crypto/2023/11/06/bored-ape-yacht-club-nft-visitors-blame-lighting-apefest-severe-eye-burn-unprotected-exposure-ultraviolet-rays-photokeratitis/

### Agreement

- [X] I irrevocably agree to release my contribution under the CC-BY 3.0 License

**Comment by CounterPillow** [comment]
For some background information, the wonderful bigclive made two videos about UV-C lamps, where he described these symptoms and cases of UV-C lamps being used by nightclubs by accident.
1. https://youtu.be/1m0TQjBRcFo
2. https://youtu.be/2T39BHvrHZ0

**Comment by molly** [comment]
https://web3isgoinggreat.com/?id=apefest-photokeratitis
