### ISSUE TITLE
Suggestion: social icons on mobile should be horizontally aligned instead of vertically aligned.

### ISSUE THREAD

**Issue by mingfengwan** [molly/web3-is-going-great#1047]
<img width="769" alt="Screenshot 2023-11-24 at 11 16 42 PM" src="https://github.com/molly/web3-is-going-great/assets/22718316/c29590eb-507d-47ac-ab9d-6c66072434ae">

Social icons being vertically aligned on mobile/tablet creates a giant chunk of empty space in the header.

**Comment by molly** [comment]
Thanks! This was a bug.
