### ISSUE TITLE
Proper attribution for "dollar amounts"

### ISSUE THREAD

**Issue by DPsystems** [molly/web3-is-going-great#1059]
I would humbly request, in the interest of technical accuracy, that any mention of monetary losses as measured in fiat, be enclosed in "quotes" or associated with the term [sic], to indicate the very real situation that any crypto values expressed in fiat such as dollars, are not in any way representative of actual liquidity in the marketplace or actual "dollars lost."

Or at least add a disclaimer along the lines of:

* All references to crypto losses in fiat are based on the premise that such crypto could be immediately sold at the current market value.  This assumes two things that we have no hard evidence for:  1.  The market price reflects actual organic demand for crypto as opposed to manipulation, and 2. Such sales of crypto would not cause the market price to collapse.   In reality, it's unrealistic to make those assumptions.

**Comment by molly** [comment]
See https://web3isgoinggreat.com/faq

**Comment by DPsystems** [comment]
Understood.  However, from a pure journalistic standpoint, wouldn't it be better to associate a footnote with any such value claim?  How is somebody supposed to know that you're estimating those amounts and that there's zero actual evidence they're accurate?

I understand this may sacrifice readability for technical accuracy.  And your priority may be readability.   So be it.
