### ISSUE TITLE
[NEW]: Late Confession in Austria Crypto Trial

### ISSUE THREAD

**Issue by dsghub** [molly/web3-is-going-great#1065]
### Date

2023-12-13

### Description

After weeks of courtroom drama, the main accused in a crypto fraud trial suddenly reversed course and confessed. After first pleading innocent when the trial started in September, then confessing to some things, then retracting some of that Wednesday morning, he suddenly admtted Wednesday just before lunch that the EXW (exchange wallet) and EXW-Token (ECR20 on Ethereum) were always meant to be a fraudulent ponzi scheme from inception.

The prosecution knows of 40.000 victims and 17,6 mio Euro in money stolen. A witness, the main accused's ex-girlfriend and mother of his child, testified that actually 80 to 120 mio Euro were stolen by the EWX group.

### Links

https://www.heise.de/news/Ploetzliches-Gestaendnis-Kaerntner-Krypto-Token-war-von-Anfang-an-Betrug-9574145.html
https://kaernten.orf.at/stories/3236486/

Here's a video about the opening of their office in Klagenfurt, Austria, some 4 years ago 
https://www.youtube.com/watch?v=mzRRVtaAdso
Reportedly, such events were used to raise money. Bags full of cash are said to have been handed over at such events.

### Agreement

- [X] I irrevocably agree to release my contribution under the CC-BY 3.0 License

### Attribution name

Daniel AJ Sokolov

### Personal link

https://social.heise.de/@newstik

**Comment by hzulla** [comment]
There's more reporting in Austrian media about this.

https://www.sn.at/wirtschaft/oesterreich/exw-prozess-hauptangeklagter-150071365

https://www.derstandard.de/story/3000000199475/exw-prozess-hauptangeklagter-bekennt-sich-vollumf228nglich-schuldig

https://kaernten.orf.at/stories/3236486/

**Comment by hzulla** [comment]
There is some interesting collected background information and what kind of person was behind this here

https://behindmlm.com/companies/exw-wallet-indictments-arrests-criminal-trial-in-austria/

> Herzog was arrested last year after attending a party in “Upper Austria”. Upon being arrested, Herzog purportedly feigned being autistic.

https://kurier.at/chronik/oesterreich/betrug-exw-klagenfurt-bandion-ortner-kryptowaehrung/402608954

> [Der Kurier:] According to prosecutor Czedik-Eysenberg, he acted as an autistic person. But he managed to reset his phone to factory settings in time.

I'm rolling my eyes at the many times crypto scammers have abused autism to either signal _"look at me, I'm a math genius, invest with me"_ or try to use it as _"but I didn't understand I was hurting people"_.

**Comment by molly** [comment]
Thanks so much for all the detail and translation! https://web3isgoinggreat.com/?id=exw-fraud
