### ISSUE TITLE
[NEW]: Radiant hack

### ISSUE THREAD

**Issue by ArtPisanski** [molly/web3-is-going-great#1082]
### Date

2024-01-02

### Description

Radiant (RDNT) hacked and drained! 1,900 ETH gone.

### Links

https://fxtwitter.com/officer_cia/status/1742317178341228814

### Agreement

- [X] I irrevocably agree to release my contribution under the CC-BY 3.0 License

### Attribution name

Artemia

**Comment by molly** [comment]
Thank you! https://web3isgoinggreat.com/?id=radiant-capital-hack
