### ISSUE TITLE
[NEW]: Chief executive of collapsed crypto fund Hyperverse does not appear to exist

### ISSUE THREAD

**Issue by brandongalbraith** [molly/web3-is-going-great#1083]
### Date

2023-01-03

### Description

"A chief executive officer whose claimed qualifications appear to have no basis in fact was used to promote the HyperVerse crypto fund, alongside celebrity messages of support, as part of a push to recruit new investors into the scheme.

A [Guardian Australia investigation last month revealed thousands of people have lost millions of dollars](https://www.theguardian.com/australia-news/2023/dec/14/crypto-currency-schemes-investors-losing-millions-regulation-hyperverse-warning-ntwnfb) to the HyperVerse crypto scheme, which was promoted by the Australian entrepreneur Sam Lee and his business partner, Ryan Xu, two of the founders of the collapsed Australian bitcoin company Blockchain Global."

### Links

https://www.theguardian.com/technology/2024/jan/04/chief-executive-of-collapsed-crypto-fund-hyperverse-does-not-appear-to-exist

### Agreement

- [X] I irrevocably agree to release my contribution under the CC-BY 3.0 License

### Attribution name

No attribution please

**Comment by molly** [comment]
Hyperverse covered here: https://web3isgoinggreat.com/?id=hyperverse-scam
