### ISSUE TITLE
Positive Development: Cretik's Report shows a 51% decline in hack loss compared to 2022

### ISSUE THREAD

**Issue by Lucas-Andrew** [molly/web3-is-going-great#1084]
### Date

2023

### Description

CertiK released its recent report which states crypto hack losses declined 51% in 2023. The report records 751 security incidents in 2023 of about $1.8 billion in digital assets which is 51% lower compared to 2022 of about $3.7 billion. The whole report was published by blockchain firm Certik in its annual report under the title "Hack3D: The web3 security Report 2023". Among all the hacks the 47 incidents made a whopping $880 million loss because private keys were compromised. On the overall scale, Ethereum makes a $686 million loss in 224 incidents. Ronghui Gu, co-founder of Certik says it is a positive development and added "The growth of bug bounty platforms and other proactive security measures is a good sign. Hopefully, we will see a continued decline in losses throughout 2024".

### Links

https://www.certik.com/resources/blog/7BokMhPUgffqEvyvXgHNaq-hack3d-the-web3-security-report-2023

### Agreement

- [X] I irrevocably agree to release my contribution under the CC-BY 3.0 License

### Attribution name

Lucas

**Comment by molly** [comment]
Covered this general type of report in the newsletter: https://citationneeded.news/issue-47-residual-garbage/
