### ISSUE TITLE
[NEW]: Google and Bing under fire for promoting nonconsensual deepfake porn, as AI continues to brew more trouble

### ISSUE THREAD

**Issue by Crazypedia** [molly/web3-is-going-great#1099]
### Date

2024-01-15

### Description

the article bemoans the rampant spread of deepfake porn and the apparent inability of search engines, also running AI components now, are unable to prevent these from showing up as top results

### Links

https://www.yahoo.com/tech/google-bing-under-fire-promoting-164040502.html

### Agreement

- [X] I irrevocably agree to release my contribution under the CC-BY 3.0 License

### Attribution name

@crazypedia@pagan.plus

**Comment by molly** [comment]
Thanks! AI is out of scope for web3 is going great, though, unless there's also a blockchain/crypto component.
