### ISSUE TITLE
[NEW]: Fake press release dupes media outlets into reporting that Walmart will begin accepting Litecoin

### ISSUE THREAD

**Issue by VerifiedJoseph** [molly/web3-is-going-great#11]
### Date

2021-09-13

### Description

Press release distributed via GlobeNewswire claimed Walmart was announcing a partnership with Litecoin to begin accepting the cryptocurrency as a payment method. The value of Litecoin spiked before tumbling after Walmart said the announcement was fake.

### Links

https://mashable.com/article/litecoin-walmart-fake-news

### Agreement

- [X] I irrevocably agree to release my contribution under the CC-BY 3.0 License

### Attribution name

Joseph

### Personal link

https://github.com/VerifiedJoseph

**Comment by molly** [comment]
Added, thank you!
