### ISSUE TITLE
[NEW]: Spanish Soccer President accused of sexual assault and coercion launches NFT Collection

### ISSUE THREAD

**Issue by bcb44** [molly/web3-is-going-great#1100]
### Date

2024-1-17

### Description

Luis Rubiales is notorious for kissing a Spanish soccer player on the mouth after their victory in the Women's World Cup and just launched his own NFT collection. Pretty incredible colab

### Links

https://www.espn.com/soccer/story/_/id/39327314/ex-spain-fa-boss-rubiales-launches-nft-support-equality

### Agreement

- [X] I irrevocably agree to release my contribution under the CC-BY 3.0 License

**Comment by molly** [comment]
Thanks: https://web3isgoinggreat.com/?id=luis-rubiales-nft
