### ISSUE TITLE
[NEW]: Industry lawyer admits: Cryptocurrency just like Beanie Babies

### ISSUE THREAD

**Issue by mbegley** [molly/web3-is-going-great#1101]
### Date

2024-1-17

### Description

Coinbase lawyer William Savitt had a moment of accidental honesty when he compared cryptocurrency to Beanie Babies.

“It’s the difference between buying Beanie Babies Inc and buying Beanie Babies,” said the Coinbase lawyer William Savitt.

The Cryprocurrency/Beanie Baby comparison has been used for many years as a way to ridicule cryprocurrency, so it's refreshing to see the industry finally embrace the reality that their product is a worthless piece of fluff, pumped up by hype.

### Links

https://www.theguardian.com/technology/2024/jan/18/coinbase-cryptocurrency-lawsuit-beanie-babies-securities-sec

### Agreement

- [X] I irrevocably agree to release my contribution under the CC-BY 3.0 License

**Comment by molly** [comment]
Covered in the newsletter: https://citationneeded.news/issue-49/
