### ISSUE TITLE
Punctuation error?

### ISSUE THREAD

**Issue by dchevrie** [molly/web3-is-going-great#1116]
# Entry

February 1, 2024

Crypto exchange created by Three Arrows Capital founders to shut down

# Changes

Shouldn't the first sentence end with a question mark?  

# Agreement

By submitting this issue, I irrevocably agree to release my contribution under the [CC-BY 3.0 License](http://creativecommons.org/licenses/by/3.0/deed.en_US). I agree that a hyperlink or URL is sufficient attribution under the Creative Commons license.

Please attribute this contribution to:

- 
- 

You can leave this blank if this is a change so small as to not be copyrightable.

**Comment by molly** [comment]
This is written as intended
