### ISSUE TITLE
[NEW]: Feds arrest married couple, seize $3.6 billion in hacked bitcoin funds

### ISSUE THREAD

**Issue by cdevroe** [molly/web3-is-going-great#113]
### Date

2022-02-08

### Description

The Justice Department announced Tuesday it had seized more than $3.6 billion in bitcoin allegedly stolen as part of a [2016 hack of Bitfinex](https://www.reuters.com/article/us-bitfinex-hacked-hongkong-idUSKCN10E0KP), saying authorities have also arrested a husband and wife in New York for allegedly trying to launder the cryptocurrency fortune.

### Links

https://www.washingtonpost.com/national-security/2022/02/08/bitfinex-hack-bitcoin-arrests/

### Agreement

- [X] I irrevocably agree to release my contribution under the CC-BY 3.0 License

### Attribution name

@cdevroe

### Personal link

http://cdevroe.com

**Comment by micah** [comment]
Looks like there is a post about this already up!

**Comment by molly** [comment]
Thank you! https://web3isgoinggreat.com/?id=2022-02-08-0
