### ISSUE TITLE
[NEW]: Crypto4Winners

### ISSUE THREAD

**Issue by willmacdonald** [molly/web3-is-going-great#1148]
### Date

2024-03-08

### Crypto4Winners Official PR

It appears one of the founders of C4W has gone on the lam with hardware wallets.

> Due to technical issues, we are currently conducting an internal investigation. Regrettably, we are unable to respond to all inquiries at this time. However, you may still withdraw any funds currently held in your wallet. We will provide an official update as soon as we gather more information about the situation.
> Thank you for your understanding.

> Our investigations lead us to suspect an individual of committing fraudulent acts that may have compromised the integrity of assets. It is also possible that the current and historical data at our disposal has been tampered with, with a high degree of sophistication. At this time, we cannot disclose the name of the suspected individual, for fear of defamation. 
> 
> We are actively investigating to assess the impact on platform clients' assets. Our priority is the protection and recovery of clients' assets and their return. We have already contacted and alerted the authorities, with whom we stand fully ready to cooperate. Unfortunately, the current situation no longer allows the platform to process fund withdrawals until it is resolved. 
> 
> We fully empathize with your distress and impatience. In the event of asset compromise, we too will be fully affected and harmed by the potential fraudulent actions of the suspected individual. If our suspicions are confirmed, rest assured that the fraudulent activities will have benefited only the individual in question, to the detriment of all other internal and external stakeholders. 
> 
> We are subject to significant uncertainties and legal constraints, which require us to be cautious in our communication. Nevertheless, we are doing everything possible to be as transparent as possible in the current situation. In addition to our immediate actions, we are already exploring all possible collective recourse against the suspected individual, if our suspicions are confirmed. 
> 
> We will keep you informed to the best of our ability as the situation develops. 
> 
> As things are still uncertain, we might not be able to reply to every message individually right now. But know that we're getting your messages and doing our best to fix things. 

### Links

https://crypto4winners.com/

### Agreement

- [X] I irrevocably agree to release my contribution under the CC-BY 3.0 License

### Attribution name

William

**Comment by molly** [comment]
Thank you! https://www.web3isgoinggreat.com/?id=crypto4winners-theft
