### ISSUE TITLE
[NEW]: Crypto.com fined € 2.85 million by Dutch central bank

### ISSUE THREAD

**Issue by Luit** [molly/web3-is-going-great#1149]
### Date

2023-10-02

### Description

De Nederlandsche Bank (DNB) today published about a fine handed to the company behind Crypto.com for serving Dutch customers without the required registration with DNB. This registration is required since 2020-05-21 by the Anti-Money Laundering and Anti-Terrorist Financing Act (Wet ter voorkoming van witwassen en financieren van terrorisme – Wwft).

This is similar to the earlier rulings (reported here as well, second and third link) against Coinbase and Binance.

### Links

https://www.dnb.nl/nieuws-voor-de-sector/handhavingsmaatregel-2024/boete-voor-foris-dax-mt-limited-crypto-com-vanwege-het-tot-2-augustus-2023-zonder-de-wettelijk-vereiste-registratie-aanbieden-van-cryptodiensten-in-nederland/
https://www.web3isgoinggreat.com/?id=coinbase-fined-3-6-million-by-dutch-central-bank
https://www.web3isgoinggreat.com/?id=binance-fined-3-million-for-operating-in-the-netherlands-without-registering

### Agreement

- [X] I irrevocably agree to release my contribution under the CC-BY 3.0 License

**Comment by Luit** [comment]
I see the earlier posts don't have links to the (Dutch) original press release. Should I add an issue linking them? 

links:
https://www.dnb.nl/nieuws-voor-de-sector/oud/handhavingsmaatregel-2022/boete-voor-binance-holdings-ltd-vanwege-het-zonder-de-wettelijk-vereiste-registratie-aanbieden-van-cryptodiensten/
https://www.dnb.nl/nieuws-voor-de-sector/oud/handhavingsmaatregel-2023/boete-voor-coinbase-europe-limited-vanwege-het-tot-22-september-2022-zonder-de-wettelijk-vereiste-registratie-aanbieden-van-cryptodiensten-in-nederland/

**Comment by molly** [comment]
Thank you! https://www.web3isgoinggreat.com/?id=cryptocom-fine
