### ISSUE TITLE
[EDIT] Link to r/Orfano not working

### ISSUE THREAD

**Issue by barnabywalters** [molly/web3-is-going-great#115]
# Entry
https://web3isgoinggreat.com/?id=2022-02-09-0

# Changes
The link to r/Orfano links to the Jim Waterson tweet already linked above rather than (presumably) https://www.reddit.com/r/Orfano/

# Agreement
By submitting this issue, I irrevocably agree to release my contribution under the [CC-BY 3.0 License](http://creativecommons.org/licenses/by/3.0/deed.en_US). I agree that a hyperlink or URL is sufficient attribution under the Creative Commons license.

No need for attribution!

**Comment by molly** [comment]
Oops, thanks!
