### ISSUE TITLE
RSS feed not showing all entries

### ISSUE THREAD

**Issue by alanshutko** [molly/web3-is-going-great#116]
I noticed that some articles don't show up in the RSS feed. For example, as of February 9, 2022 2:28 PM CT, the most recent article on the site is "Samsung launches environmental sustainability-themed metaverse scavenger hunt where people plant virtual trees and earn NFTs" but that article isn't in the feed. I've attached the feed as I've pulled it.

[feed.xml.txt](https://github.com/molly/web3-is-going-great/files/8035977/feed.xml.txt)

**Comment by molly** [comment]
Thanks! I borked the RSS once again, it's fixed now.

**Comment by ztane** [comment]
Are you sure it is fixed now? I subscribed to the feed in our Slack and it shows the OpenSea post as topmost now :thinking:

**Comment by molly** [comment]
Should be good now. I added some alerting so that I hopefully stop doing this but it's clearly not sufficient—on my to-do to fix up! Thanks for reporting the issue in the meantime @ztane
