### ISSUE TITLE
[NEW]: Skycoin, now with torture, kidnapping and extortion claims 

### ISSUE THREAD

**Issue by georgzoeller** [molly/web3-is-going-great#119]
### Date

2022-02-10

### Description

Bloomberg reports that the creator of Skycoin claims a former consultant and others tried to extort tens of millions of dollars with ransomware attacks, organised a plot to kidnap him and his girlfriend, and conspired to undermine the not at all scammy digital token.

Throw in some claims of extortion, torture, pornographic link scamming and all the other things we’ve come to associate with the technology and it’s just a normal day on the web3. 

### Links

https://www.straitstimes.com/business/banking/founder-of-singapore-based-skycoin-claims-in-suit-he-was-extorted-kidnapped

### Agreement

- [X] I irrevocably agree to release my contribution under the CC-BY 3.0 License

### Attribution name

@gulbsoft

**Comment by molly** [comment]
Thank you! https://web3isgoinggreat.com?id=2022-02-09-4
