### ISSUE TITLE
Cursor is incorrect in article bodies

### ISSUE THREAD

**Issue by Mstrodl** [molly/web3-is-going-great#1190]
The cursor doesn't change when hovering over text in an article body.

Looks like something here:
https://github.com/molly/web3-is-going-great/blob/53cdeeb5feb3605041791cf1e49738811361b46a/src/styles/main.sass#L591

**Comment by molly** [comment]
https://github.com/molly/web3-is-going-great/commit/d9326cf0b588c3daef2a6220fe2351ac09c8e9dc should resolve this. The `pointer-events` style is needed to allow pointer events to pass through some of these divs, which overlap portions of other entries. At some point I need to look into styling the article divs differently so I don't have to do so much manual cursor/pointer-event wrangling.

Thanks for the report!
