### ISSUE TITLE
[NEW]: The Web3 Fraud

### ISSUE THREAD

**Issue by triptych** [molly/web3-is-going-great#12]
### Date

2021-12-16

### Description

So why this hype?  Because the cryptocurrency space, at heart, is simply a giant ponzi scheme where the only way early participants make money is if there are further suckers entering the space.  

### Links

https://www.usenix.org/publications/loginonline/web3-fraud

### Agreement

- [X] I irrevocably agree to release my contribution under the CC-BY 3.0 License

### Attribution name

@triptych

### Personal link

https://twitter.com/triptych

**Comment by molly** [comment]
Added to https://web3isgoinggreat.com/what
