### ISSUE TITLE
[NEW]: Loopring Smart Wallets drained by hacker that compromised the company's official 2FA service

### ISSUE THREAD

**Issue by fz3n** [molly/web3-is-going-great#1210]
### Date

2024-06-09

### Description

Some users of the Loopring Smart Wallet were drained of their assets as part of an attack that compromised Loopring's two-factor authentication service. This allowed a hacker to impersonate the wallet owners and gain control of any wallet that only used Loopring's Official Guardian wallet for social recovery. Until a very recent upgrade, solely using the Official Guardian was the default configuration for any smart contract wallet created using Loopring's service.

At the time of writing, the attacker has drained approximately $5,000,000 of digital assets.

### Links

Discord link:
https://discord.com/invite/KkYccYp

Screenshot from Discord announcement:
![image](https://github.com/molly/web3-is-going-great/assets/815174/e7ddcdf0-ff62-4b02-aeed-7c4016e35d71)

Drainer wallet, with about $5,074,582.66 at the time of writing.
https://etherscan.io/address/0x44f887cfbd667cb2042dd55ab1d8951c94bb0102

### Agreement

- [X] I irrevocably agree to release my contribution under the CC-BY 3.0 License

**Comment by fz3n** [comment]
Additional stories: 

https://www.theblock.co/post/299177/loopring-suffers-5-million-hack-after-guardian-two-factor-authentication-service-is-compromised

**Comment by molly** [comment]
Thank you! https://www.web3isgoinggreat.com/?id=loopring-wallet-hack
