### ISSUE TITLE
[NEW]: WazirX temporarily suspends crypto deposits and withdrawals after $230M hack

### ISSUE THREAD

**Issue by Chirag8023** [molly/web3-is-going-great#1211]
### Date

2024-07-18

### Description

Indian crypto exchange [WazirX](https://economictimes.indiatimes.com/markets/wazirx) on Thursday temporarily [suspended](https://economictimes.indiatimes.com/topic/suspended) withdrawals after being hit by the [security breach](https://economictimes.indiatimes.com/topic/security-breach).

### Links

https://economictimes.indiatimes.com/markets/cryptocurrency/wazirx-temporarily-suspends-crypto-deposits-and-withdrawals-after-230m-hack/articleshow/111834527.cms?from=mdr

### Agreement

- [X] I irrevocably agree to release my contribution under the CC-BY 3.0 License

**Comment by molly** [comment]
https://www.web3isgoinggreat.com/?id=wazirx-hack
