### ISSUE TITLE
[EDIT] Finish the first sentence of 30 July 2024 DraftKings entry

### ISSUE THREAD

**Issue by pmcjones** [molly/web3-is-going-great#1212]
# Entry

# Changes

Change first sentence, "American sports gambling behemoth DraftKings announced to users of its Reignmakers NFT game and NFT marketplace, effective immediately.", to mention what was announced.

# Agreement

By submitting this issue, I irrevocably agree to release my contribution under the [CC-BY 3.0 License](http://creativecommons.org/licenses/by/3.0/deed.en_US). I agree that a hyperlink or URL is sufficient attribution under the Creative Commons license.

- No attribution required.

**Comment by molly** [comment]
Ack, thanks!
