### ISSUE TITLE
[NEW]: SEC goes after USD 650 Mio Multi-Level-Marketing-Cryptocurrenncy Fraud

### ISSUE THREAD

**Issue by dsghub** [molly/web3-is-going-great#1213]
### Date

2024-08-12

### Description

SEC Charges NovaTech and its Principals and Promoters with $650 Million Crypto Fraud

### Links

https://www.sec.gov/newsroom/press-releases/2024-95
https://www.sec.gov/files/litigation/complaints/2024/comp-pr2024-95.pdf

### Agreement

- [X] I irrevocably agree to release my contribution under the CC-BY 3.0 License

### Attribution name

It's not by me, it's by SEC.gov, which is public domain

### Personal link

https://social.heise.de/@newstik

**Comment by molly** [comment]
Thanks! https://www.web3isgoinggreat.com/?id=novatech-lawsuit
