### ISSUE TITLE
[NEW]: Ponzi scheme with fake smartbots

### ISSUE THREAD

**Issue by dsghub** [molly/web3-is-going-great#1214]
### Date

2024-08-26

### Description

Those bots, that automatically deploy smart contracts to provide liquidity for flash loans, were, unfortunately, as fake, as the purported payments by Gemini. It was all a multi million dollar ponzi scheme. And the brother did not disclose to his victims that he had a history in financial crime! I am shocked. Shocked! 

### Links

https://www.sec.gov/newsroom/press-releases/2024-107
https://www.sec.gov/files/litigation/complaints/2024/comp-pr2024-107.pdf

### Agreement

- [X] I irrevocably agree to release my contribution under the CC-BY 3.0 License

### Attribution name

Daniel AJ Sokolov

### Personal link

https://social.heise.de/@newstik

**Comment by molly** [comment]
Looks like we were reading this at the same time :) https://www.web3isgoinggreat.com/?id=adam-brothers-charged-by-sec
