### ISSUE TITLE
[NEW]: AssangeDAO faces rug pull accusations from organizer

### ISSUE THREAD

**Issue by EmmaBest** [molly/web3-is-going-great#1217]
### Date

2024-09-09

### Description

[Over $10 million in ETH remain](https://x.com/silkenoa/status/1809662226636181735) from the [more than $55 million](https://www.coindesk.com/opinion/2022/03/08/assangedao-raised-56m-and-quickly-split-up-was-it-still-a-success/) raised by [AssangeDAO](https://assangedao.org/) to finance Julian Assange’s legal and public relations campaigns. [Amir Taaki](https://en.wikipedia.org/wiki/Amir_Taaki), one of [AssangeDAO’s organizers](https://x.com/Narodism/status/1820062794135269819), made accusations on Monday that the DAO was a rug pull. In other posts, Amir alleged that Harry Halpin was working with the [Wau Holland Foundation](https://en.wikipedia.org/wiki/Wau_Holland_Foundation) to cut out the DAO for control of the remaining funds. The next day, Bitfinex announced that they were adding AssangeDAO’s JUSTICE token to their listings.

### Links

https://emma.best/2024/09/13/assangedao-launches-on-bitfinex-as-it-faces-rug-pull-accusations-from-organizer/
https://t.me/Real_AssangeDAO/1/5414
https://t.me/Real_AssangeDAO/1/5415
https://t.me/Real_AssangeDAO/1/5416
https://t.me/assangedaochat/604
https://t.me/assangedaochat/606
https://t.me/assangedaochat/607
https://t.me/Real_AssangeDAO/1/6303
https://t.me/Real_AssangeDAO/1/6153
https://x.com/harryhalpin/status/1830872233629073894
https://t.me/Real_AssangeDAO/1/6292
https://t.me/Real_AssangeDAO/1/6293
https://t.me/assangedaochat/1131
https://t.me/assangedaochat/1132

### Agreement

- [X] I irrevocably agree to release my contribution under the CC-BY 3.0 License

### Attribution name

@Mxy@kolektiva.social

### Personal link

https://emma.best/

**Comment by molly** [comment]
https://www.web3isgoinggreat.com/?id=assangedao-accused-of-rugpull
