### ISSUE TITLE
[NEW]: Atomic Wallet failed to address security issues found in security review by Least Authority

### ISSUE THREAD

**Issue by jspaleta** [molly/web3-is-going-great#122]
### Date

2022-02-10

### Description

Least Authority made a security disclosure to inform the public that they consider the Atomic Wallet to be insufficiently secure in protecting user assets and private data after Atomic Wallet failed to remediate issues found in security review.  

### Links

https://leastauthority.com/blog/disclosure-of-security-vulnerabilities-in-atomic-wallet/

### Agreement

- [X] I irrevocably agree to release my contribution under the CC-BY 3.0 License

**Comment by molly** [comment]
Thank you! https://web3isgoinggreat.com?id=2022-02-10-0
