### ISSUE TITLE
[EDIT] Faulty source link in “Trump family Twitter accounts compromised ahead of World Liberty Financial launch”

### ISSUE THREAD

**Issue by Zegnat** [molly/web3-is-going-great#1220]
# Entry

September 3, 2024: [Trump family Twitter accounts compromised ahead of World Liberty Financial launch](https://www.web3isgoinggreat.com/single/trump-family-twitter-accounts-compromised)

# Changes

The entry has 2 source links, but both point to the same Blockworks link. The Politico source should link: `https://www.politico.com/news/2024/09/03/lara-tiffany-trump-social-media-hack-00177261`.

# Agreement

You can leave this blank if this is a change so small as to not be copyrightable.

**Comment by molly** [comment]
Thank you!
