### ISSUE TITLE
[NEW]: 13-year old rug-pulled $30K and things got ugly.

### ISSUE THREAD

**Issue by mxxcon** [molly/web3-is-going-great#1227]
### Date

November 20, 2024 03:56:12 +UTC

### Description

A 13-year-old, known as the "Gen Z Quant kid," created a token called QUANT and executed a rug-pull, making $30,000. In retaliation, "crypto community" pumped the token's value, causing it to skyrocket, making him miss out on potentially ~$4M and then doxxing the kid. Things got even worse when allegedly the kid's dog, Bari, was kidnapped and the perpetrators then launched a new token named $BARI using the dog's image.

### Links

https://decrypt.co/292594/this-child-made-30k-rugging-a-solana-meme-coin-then-crypto-degens-got-revenge
https://www.cryptotimes.io/2024/11/22/quant-kids-dog-stolen-after-rug-pull-kidnapper-launches-bari/
https://www.cryptonewsz.com/quant-rug-pull-kidnapped-dog-revenge-token/

### Agreement

- [X] I irrevocably agree to release my contribution under the CC-BY 3.0 License

**Comment by molly** [comment]
Thanks. https://www.web3isgoinggreat.com/?id=quant-rug-pull
