### ISSUE TITLE
[EDIT] ngmi glossary (typo)

### ISSUE THREAD

**Issue by lucaswerkmeister** [molly/web3-is-going-great#125]
# Entry
The glossary entry “ngmi” (not going [to] make it), e.g. under [mtgDAO gets a legal notice from Wizards of the Coast, writes that they are "unfairly discriminat[ing] against web3 tech and web3 communities"](https://web3isgoinggreat.com/?id=2022-02-10-1).

# Changes
peroson → person :)

# Agreement
By submitting this issue, I irrevocably agree to release my contribution under the [CC-BY 3.0 License](http://creativecommons.org/licenses/by/3.0/deed.en_US). I agree that a hyperlink or URL is sufficient attribution under the Creative Commons license.

Please attribute this contribution to:
* Lucas Werkmeister
* no link I think
* honestly this probably falls below ToO so feel free to not credit me at all ^^

**Comment by molly** [comment]
Thanks!
