### ISSUE TITLE
[EDIT] Jacked Ape Club NFT project team erupts in chaos

### ISSUE THREAD

**Issue by carpenterd777** [molly/web3-is-going-great#136]
# Entry
Jacked Ape Club NFT project team erupts in chaos, February 13, 2022

# Changes
...they simply removed the trio because their work was done, and ~~becausue~~ because they said...

# Agreement
By submitting this issue, I irrevocably agree to release my contribution under the [CC-BY 3.0 License](http://creativecommons.org/licenses/by/3.0/deed.en_US). I agree that a hyperlink or URL is sufficient attribution under the Creative Commons license.

Please attribute this contribution to:
carpenterd777

**Comment by carpenterd777** [comment]
(p.s. this site is fascinating to read. thank you for creating and maintaining it!)

**Comment by molly** [comment]
Thank you!
