### ISSUE TITLE
[NEW]: Update to mgtDAO, "I have no idea what I'm doing"

### ISSUE THREAD

**Issue by hslabbert** [molly/web3-is-going-great#137]
### Date

2022-02-14

### Description

Update to the mgtDAO fiasco, with the organizer basically flat out admitting they have zero clue about copyright or IP law.

From 2022-02-10:

"To members of mtgDAO, I don’t know exactly where we go from here. Wizard’s position seems reactionary _but I don’t currently know enough about copyright law to be confident about how a court would interpret this situation_."

And then the update 2022-02-15:

"1/ I don’t know shit about copyright law, so I’m trying not to discuss it much, but I’ll tell you that mtgDAO NFTs being IP infringement is not intuitive to me."

That's a helluva business plan, pal.

### Links

https://twitter.com/mtgDAO/status/1491939411277201410?s=20&t=1irEGf_4OZsOHPldDoHzsw
https://twitter.com/mtgDAO/status/1493840726500667392?s=20&t=1irEGf_4OZsOHPldDoHzsw

### Agreement

- [X] I irrevocably agree to release my contribution under the CC-BY 3.0 License

### Attribution name

@hugoslabbert

### Personal link

https://twitter.com/hugoslabbert

**Comment by molly** [comment]
Updated the existing entry: https://web3isgoinggreat.com/?id=2022-02-10-1
