### ISSUE TITLE
metadeckz shuts down after blowback from streamers

### ISSUE THREAD

**Issue by bnb** [molly/web3-is-going-great#138]
### Date

2022-02-17

### Description

Apparently an artist artist started creating “trading cards” of streamers without their permission and without meaningfully letting them know.

Apparently one was quote tweeted by someone who works directly with Ludwig, who is featured on one of the cards: https://twitter.com/slime_machine/status/1494129425264168964?s=21

That quote tweeted got a reply from the artist: https://twitter.com/metadeckz/status/1494142271004065796?s=21

Ludwig replied to the artists reply: https://twitter.com/ludwigahgren/status/1494152752448122882?s=21

Which led to the artist deciding to shut down the NFT side of it, in a somewhat long winded video in which they say they knew the audience didn’t like NFTs but thought they could change people’s minds by making “something cool, something relatable”.
https://twitter.com/metadeckz/status/1494171088103911429?s=21

The artist said he’s going to continue making the art, just not as NFTs.

### Links

https://twitter.com/slime_machine/status/1494129425264168964?s=21

https://twitter.com/metadeckz/status/1494142271004065796?s=21

https://twitter.com/ludwigahgren/status/1494152752448122882?s=21

https://twitter.com/metadeckz/status/1494171088103911429?s=21

### Agreement

- [X] I irrevocably agree to release my contribution under the CC-BY 3.0 License

### Attribution name

@bitandbang

### Personal link

https://twitter.com/bitandbang

**Comment by molly** [comment]
Thank you! https://web3isgoinggreat.com/?id=2022-02-16-3
