### ISSUE TITLE
[NEW]: Money that won Melania Trump's NFT Came From Melania Trump Wallet

### ISSUE THREAD

**Issue by Bonkles** [molly/web3-is-going-great#139]
### Date

2022-02-16

### Description

From Bloomberg: 

The source of funds for the winning bid in Melania Trump’s first NFT auction appears to be the creators of the project themselves

### Links

https://t.co/qHdwr8CD73

### Agreement

- [X] I irrevocably agree to release my contribution under the CC-BY 3.0 License

### Attribution name

@dongleflop

### Personal link

https://twitter.com/dongleflop

**Comment by molly** [comment]
I believe this is already covered with https://web3isgoinggreat.com/?id=2022-01-26-5

**Comment by Bonkles** [comment]
derrrrrp. Sorry about that- could have sworn that wasn't up when I posted this
