### ISSUE TITLE
[NEW]: German ID Wallet app stopped after 1 day of public availability

### ISSUE THREAD

**Issue by gittaca** [molly/web3-is-going-great#14]
### Date

2021-09-24

### Description

Shortly before the federal election, the German government launched the app "ID Wallet". It was supposed to store driver's licenses and other identification documents, and allow them to be shared with authorized parties (like the police, or during hotel check-ins). Because the distributed ledger back-end met neither basic EU security standards, nor handled more than a few thousand users (in total, not per second), the launch failed and private data stored in the app would have been exposed to identity theft. FOIA requests revealed, that the project developers had known about the shortcomings of their design months in advance.

### Links

https://marketresearchtelecast.com/id-wallet-the-german-government-had-long-known-about-it-security-vulnerabilities/190919/
https://netzpolitik.org/2021/interview-zu-id-wallet-konzeptionell-kaputt-und-ein-riesiger-rueckschritt/

### Agreement

- [X] I irrevocably agree to release my contribution under the CC-BY 3.0 License

**Comment by molly** [comment]
Added, thank you!
