### ISSUE TITLE
[NEW]: Kickstarter exec admits in interview that they don’t really have a clue what their “move to blockchain” means

### ISSUE THREAD

**Issue by barnabywalters** [molly/web3-is-going-great#142]
### Date

2022-02-18

### Description

“Beat reporter Sean Z. was given an opportunity to interview Kickstarter COO Sean Leow about these issues, with a few questions added by Beat editor-in-chief Heidi MacDonald. As far as we know it is the first time a Kickstarter executive has spoken publicly on the blockchain move.”

When faced with some basic questions about the company’s much-discussed “switch to blockchain”, the best Kickstarter’s COO is able to do is splutter buzzwords and admit that he doesn’t really know what the move means, or what benefits it might bring.

### Links

https://www.comicsbeat.com/kickstarter-blockchain-controversy-interview/

### Agreement

- [X] I irrevocably agree to release my contribution under the CC-BY 3.0 License

### Attribution name

no attribution please

**Comment by molly** [comment]
Thank you! https://web3isgoinggreat.com/?id=2022-02-18-0
