### ISSUE TITLE
[NEW]: Crypto Chick #2 created by Polly in the OG Collection of Crypto Chicks was not original art.  

### ISSUE THREAD

**Issue by tel3machuz** [molly/web3-is-going-great#143]
### Date

2022-02-21

### Description

Yesterday, we became aware that Crypto Chick #2 created by Polly in the OG Collection of Crypto Chicks was not original art.  While we initially thought that this art may have come from one woman artist, we have since discovered this art more broadly online and in various Stock photo websites. Our team has been working hard to define our path forward, including many of us not sleeping.

This news was devastating to us for many reasons, but mostly because our community relies on us to promote and protect women artists.  This act could not be more misaligned with our values of honesty, integrity, and our commitment of transparency to you, our community.

We deeply regret any harm this may have caused you as a community member.  We have discussed with Polly and she will no longer be a part of the Crypto Chicks team. We are making additional changes to our team structure, but we ask that you give us time in order to ensure everything is set up from a legal perspective. We will communicate with everyone completely transparently about this.  Myself and the team who has helped to build this community will be here to build CC into the brand we know it can be. We will use this as an opportunity to find another woman artist in the space we can uplift, who is dedicated to creativity and originality.

We realize there may also be concerns around the Baby Chick collection and as such have decided to pause the Time Machine potion allocation. We have a number of ideas for how these will be used in the future, but please give us time to find another woman artist we are really excited to collaborate with.

And lastly, to further show our commitment to promoting women artists, we are setting up an ETH fund towards supporting 1/1 women artists in the NFT space. We will have more details to share with you soon on how that will be deployed. 

We’ve already made contact with most of our brand partners, who have all expressed love and support for our leadership team and have confidence, as we do, in Crypto Chicks.

Again, we hope that our community accepts our sincere apology and recognizes our deep commitment to women artists around the world. We remain fully committed to honesty, transparency, and our community. We will be targeting daily, detailed community updates to set a regular cadence of communication as we work through this period of flux.

### Links

https://twitter.com/NFTCryptoChicks/status/1495144337394610176

### Agreement

- [X] I irrevocably agree to release my contribution under the CC-BY 3.0 License

**Comment by molly** [comment]
https://web3isgoinggreat.com/?id=2022-02-18-3
