### ISSUE TITLE
[NEW]: OnePlus made an NFT collection, in case you needed more reasons to not buy OnePlus products

### ISSUE THREAD

**Issue by RazvanRauta** [molly/web3-is-going-great#15]
### Date

2021-12-17

### Description

1 of 15 characters we created to memorialize our devices in celebration of our 8th Anniversary and give back to our community.

All 5,000 collectibles are minted and FREE for you to collect right now while supplies last. 

### Links

https://twitter.com/OnePlus_USA/status/1471905068383444998?s=20

### Agreement

- [X] I irrevocably agree to release my contribution under the CC-BY 3.0 License

### Attribution name

RRazvan

**Comment by molly** [comment]
Probably won't add this unless there's outside reporting on it
