### ISSUE TITLE
[EDIT] Seventeen OpenSea users have their NFTs stolen and flipped for a total of $3 million by a phishing scammer

### ISSUE THREAD

**Issue by tel3machuz** [molly/web3-is-going-great#158]
# Entry
Seventeen OpenSea users have their NFTs stolen and flipped for a total of $3 million by a phishing scammer

# Changes
add link 
NFT Trader Sues OpenSea for $1 Million Over Stolen Ape With Baby's Bonnet
https://gizmodo.com/the-internet-was-a-mistake-throw-your-computer-into-the-1848574699

# Agreement
By submitting this issue, I irrevocably agree to release my contribution under the [CC-BY 3.0 License](http://creativecommons.org/licenses/by/3.0/deed.en_US). I agree that a hyperlink or URL is sufficient attribution under the Creative Commons license.

Please attribute this contribution to:
* 
*

**Comment by molly** [comment]
Thanks! This is added in a separate entry, since the theft happened two weeks before this phishing incident and hasn't been definitively connected: https://web3isgoinggreat.com/?id=2022-02-18-4

**Comment by tel3machuz** [comment]
sorry, I have seen it after I have press the submit :D

**Comment by molly** [comment]
Not a problem! I would rather get duplicates than miss something interesting! 💯
