### ISSUE TITLE
[NEW]: Ex-crypto CEO likely stole $11B of ETH in infamous 2016 DAO hack. 

### ISSUE THREAD

**Issue by sokirill** [molly/web3-is-going-great#161]
### Date

2022-02-22

### Description

The man responsible for hacking Ethereum DAO has been named as former TenX CEO Toby Hoenisch. The 2016 hack resulted in a controversial Ethereum hard fork that rolled back the network so stolen funds could be returned to users.

### Links

https://www.forbes.com/sites/laurashin/2022/02/22/exclusive-austrian-programmer-and-ex-crypto-ceo-likely-stole-11-billion-of-ether/?sh=14297c077f58

### Agreement

- [X] I irrevocably agree to release my contribution under the CC-BY 3.0 License

**Comment by molly** [comment]
Thank you! https://web3isgoinggreat.com/?id=2022-02-22-1
