### ISSUE TITLE
[NEW]: 

### ISSUE THREAD

**Issue by rschpdr** [molly/web3-is-going-great#162]
### Date

2022-02/23

### Description

Space Crypto, a new play-to-earn game that launched on Feb. 15, announced this wednesday (Feb. 23) that users won't be able to withdrawl all their reward tokens. Without previously informing investors, they decided that players won't be able to withdrawl the amount of reward tokens ($SPE) necessary to repair all their ships, essentially locking everyone in to artificially extend the game's life. They also decided that the token exchange rate would be 5 in-game tokens = 1 $SPE (again, without any of this being specified in the Whitepaper), essentially hiding the true amount of in-game currency needed for ROI right until the last minute. The community is almost entirely enraged at this point, and the $SPE token price is melting very fast.

Here are some messages from the devs:

🎉🎉🎉GOOD NEWS - YOU CAN WITHDRAW $SPE NOW

🎉Tutorial
-Hit to refresh page F5
-When withdraw Cick Max then subtract 0.01. Example if you click max and you get 10.84, you have to type 10.83 to withdraw.

🎉You need to hold at least 1 SPG to withdraw your SPEs -> SPE. The withdraw Ratio is 5 SPEs = 1 SPE

🎉THE REPAIR FEE FOR FIXING SPACESHIPS
Regarding the last announcement, the SPEs is used for SpaceShip Maintenance and will be locked for maintenance/fix spaceships in-game.
The amount of locked SPEs = your number of spaceships * fixing cost
Rarity             |      SPEs Repair Cost
Common        |        10
Rare               |        10
Super Rare    |        12
Epic               |        16
Legend          |        24
Mythical        |        36

🎉Example: A user has 20 commons and 1 legendary and 800 SPEs. The SPEs locked is: (20*10) + (1*24) = 224 SPEs. The result of allowing withdraw will be 800 - 224 = 576 SPEs

#SpaceCrypto #Metaverse  #PlayToEarn #GameFi #NFTs

-----------------------------------------------------------------------------------------------------------------------------------------

📣Please spend your 5 minutes to think about it
- Some people said we scam - Dev DID NOT sell a single token, check the dev wallet. all of it is still locked. in fact we are still working hard day by day to solve the issues.
- You have invested in the project => you MUST protect your own assets.

HOW?!? => STOP THE FUD, we know there were some mistakes and you're suffering, but we're on your side, think about it!

### Links

$SPE token price history: https://poocoin.app/tokens/0x74da4412b2c70644929479f4d169325e9ce35ddb

official devs twitter: https://twitter.com/SpaceCryptoGame

their Telegram channel: https://t.co/EwNqhxmhVj

White Paper: https://docs.spacecrypto.io/guides/readme

### Agreement

- [X] I irrevocably agree to release my contribution under the CC-BY 3.0 License

**Comment by molly** [comment]
Thank you! https://web3isgoinggreat.com/?id=2022-02-23-3
