### ISSUE TITLE
[NEW]: Metaverse app allows kids into virtual strip clubs

### ISSUE THREAD

**Issue by relaxedguy** [molly/web3-is-going-great#163]
### Date

2022-02-23

### Description

A BBC News researcher - using an app with a minimum age rating of 13 - visited virtual-reality rooms where avatars were simulating sex. She was shown sex toys and condoms, and approached by numerous adult men... One man told our researcher that avatars can "get naked and do unspeakable things". Others talked about "erotic role-play".

### Links

https://www.bbc.com/news/technology-60415317

### Agreement

- [X] I irrevocably agree to release my contribution under the CC-BY 3.0 License

### Attribution name

relaxedguy

**Comment by molly** [comment]
This is horrifying, though I think a bit out of scope for the project. I'm still fully deciding which metaverse-related topics to include, but am trying to limit it to projects with a crypto/NFT component (or plans for one).
