### ISSUE TITLE
[EDIT] Nelson Mandela paintings from 2002, not from when he was incarcerated

### ISSUE THREAD

**Issue by VerifiedJoseph** [molly/web3-is-going-great#167]
# Entry
[Nelson Mandela's paintings from prison to be sold as NFTs](https://web3isgoinggreat.com/single/2022-02-25-0)

# Changes
The watercolours where created long after Mandela was released from prison and after he stood down as president in 1999.

From the [theguardian](https://www.theguardian.com/world/2022/feb/25/nelson-mandela-paintings-of-life-in-prison-to-be-sold-as-nfts):

> My Robben Island consists of five vivid watercolours painted by Mandela after he stood down as president in 1999, plus The Motivation, a handwritten text that explains his visualisation of the harsh island prison. All six works bear his signature.

> The watercolours, painted in 2002 as a therapeutic activity under the guidance of the art teacher Varenka Paschke.

Therefore I recommend these changes: 

Title: 
> Nelson Mandela's paintings of prison life to be sold as NFTs

First sentence:
> The Guardian reported that five watercolor paintings of prison life  created by former South African president Nelson Mandela will be sold as NFTs next month, as well as a handwritten description of why he created the artwork.

# Agreement
By submitting this issue, I irrevocably agree to release my contribution under the [CC-BY 3.0 License](http://creativecommons.org/licenses/by/3.0/deed.en_US). I agree that a hyperlink or URL is sufficient attribution under the Creative Commons license.

Please attribute this contribution to:
Joseph
*

**Comment by molly** [comment]
Thank you! Fixed.
