### ISSUE TITLE
[Request] Ukraine NFT

### ISSUE THREAD

**Issue by Naleksuh** [molly/web3-is-going-great#169]
I searched DuckDuckGo "ukraine nft" because I was sure someone had done something but surprisingly as much as I was expecting NFTs about the Ukraine attack I was much more surprised to find people using NFTs to raise money to help Ukraine. Looks like Lana Rhoades is back at it again by saying people cannot discuss her NFT scam while Ukraine thing is going on https://www.tweaktown.com/news/84780/famous-porn-star-compares-her-nft-scam-to-russia-invading-ukraine/index.html

PS Also will there be a new way to discuss additions for web3isgoinggreat? GitHub is a coding website and I would prefer for my issues here to be software related, thanks.

**Comment by molly** [comment]
Yeah, should probably add some. While there seem to be some NFT projects and DAO fundraisers that are genuinely sending some proceeds to Ukraine, it also seems like a wave of scammers have come in as well.

Regarding off-GH discussions, I hadn't really thought about it. Is there another system you had in mind as being particularly well-suited?

**Comment by Naleksuh** [comment]
@molly Personally, I would just add a forum board to web3isgoinggreat.com but I think most people are looking for some type of social media platform. guilded.gg is an up and coming alternative to Discord, could try that out?

**Comment by molly** [comment]
I've added an entry on Ukraine-related grifts to https://web3isgoinggreat.com/?id=2022-02-26-0

As for the discussion thing, I'll think on it. I definitely do not plan to add a forum or commenting to W3IGG—I don't have the time, energy, or desire to moderate such a thing.
