### ISSUE TITLE
RSS feed is broken (error on line 96)

### ISSUE THREAD

**Issue by VerifiedJoseph** [molly/web3-is-going-great#17]
Hi Molly,

The RSS feed is broken. there is an error on line 96.
![feed-eorror](https://user-images.githubusercontent.com/20118140/147154734-80edf12d-ddde-45d4-9f27-ef9f0918dd70.PNG)

**Comment by molly** [comment]
Oops! How's it look now? I just pushed a fix.

**Comment by VerifiedJoseph** [comment]
It's fixed. 👍

**Comment by molly** [comment]
Great! Thanks so much for the report!
