### ISSUE TITLE
[NEW]: '50% of transactions were fraudulent' when Steam accepted Bitcoin for payments

### ISSUE THREAD

**Issue by hmlongco** [molly/web3-is-going-great#178]
### Date

2022-02-26

### Description

Bitcoin was introduced as a payment method on Steam in April 2016 and removed in December 2017, reportedly due to the volatility of Bitcoin's price and "a significant increase in the fees to process transactions on the Bitcoin network."

Turns out that wasn't the only problem. In a recent interview, Valve president Gabe Newell said. "We had problems when we started accepting cryptocurrencies as a payment option. 50% of those transactions were fraudulent, which is a mind-boggling number. These were customers we didn't want to have."

Newell continued, "There's nothing inherently about distributed ledgers that makes them problematic. It's just so far that's almost always what our experience has been."

### Links

https://www.pcgamer.com/uk/50-of-transactions-were-fraudulent-when-steam-accepted-bitcoin-for-payments-says-gabe-newell/

### Agreement

- [X] I irrevocably agree to release my contribution under the CC-BY 3.0 License

### Attribution name

hmlongco

**Comment by molly** [comment]
Although this statement was made recently, he's discussing an experiment from far before the timeline I'm trying to cover with this project.
