### ISSUE TITLE
[NEW]: crypto booster believes some funds and NFTs stolen from metamask wallet due to his plugging in a USB dildo

### ISSUE THREAD

**Issue by mlncn** [molly/web3-is-going-great#18]
### Date

2021-12-21

### Description

> This morning at 5:40am my desktop metamask was hacked and drained of all funds and NFTs.
>
> The only thing I did differently was charge a brand new dildo on my computer and installed the app
>
> Still trying to wrap my head around this but I think I was just hacked by a fucking dildo

### Links

https://twitter.com/crypto_bitlord7/status/1473231965927063553

### Agreement

- [X] I irrevocably agree to release my contribution under the CC-BY 3.0 License

**Comment by mlncn** [comment]
mostly this is worthy to be included for hilarity rather than notability but it's a good example of the constant minor losses that constantly happen but go unnoticed if a cryptocurrency booster doesn't publicly post their L

**Comment by molly** [comment]
Pretty sure this is a joke, which is why I've held off adding it.
