### ISSUE TITLE
Add www.web3isgoinggreat.com

### ISSUE THREAD

**Issue by Naleksuh** [molly/web3-is-going-great#183]
https://www.web3isgoinggreat.com returns a Cloudflare errror, but https://web3isgoinggreat.com works. May need a new www entry

**Comment by Naleksuh** [comment]
By the looks of the error it seems like www is trying to serve a certificate that is only valid for the root domain. Only Molly can check though because Cloudflare was recently added (it was a Google certificate before, and I didn't save it)

**Comment by molly** [comment]
Thanks, should be fixed now.
