### ISSUE TITLE
[NEW]: 

### ISSUE THREAD

**Issue by scannopolis** [molly/web3-is-going-great#184]
### Date

2021-07-06

### Description

Residents nearby Seneca Lake were amazed to suddenly realize that the glacial lake suddenly turned into "a giant hot tub". The culprit? The operations of Greenidge, a bitcoin mining company that employs only 30 people to maintain 8,000 computers mining.

### Links

https://www.businessinsider.com/bitcoin-mining-seneca-lake-finger-lakes-new-york-hot-tub-2021-7

### Agreement

- [X] I irrevocably agree to release my contribution under the CC-BY 3.0 License

**Comment by molly** [comment]
Thank you! https://web3isgoinggreat.com/?id=2022-02-09-6
