### ISSUE TITLE
[NEW]: NeosVR, a metaverse platform, announces it's separating from its crypto component after months of team turmoil

### ISSUE THREAD

**Issue by philpax** [molly/web3-is-going-great#185]
### Date

2022-03-05

### Description

Apologies in advance: this one is a bit of a long one, but I needed to provide context for you. Feel free to ensmallen it, and ask me any questions about events. I've been here for the last two months of this rollercoaster and I want to make sure the story's told correctly. (Might write a blog post about it, maybe!)

NeosVR is a metaverse platform, like VRChat, that lets people join shared scriptable dynamic worlds and interact with each other and do, well, anything on both desktop and VR. It is much more of a metaverse than Decentraland or similar projects - it actually delivers on its promise, with diverse and fantastical worlds powered by some of the most powerful in-game scripting / customisation that I've seen in a game, and I've seen many platforms try to compete in that space.

I begun with this preface to provide context for what's happened: in 2018, Neos introduced Neos Credits (NCR) to its platform, a ERC-20 token, to allow people to transact between each other on the platform. At first, this was not a terrible idea - they needed a solution to let people transact, and they did not want to invest in a Linden Dollars-like solution. Neos trundled along with this for a while, culminating in an ICO where ~45 million of the ~50 million coins were minted and dispersed at a slowly growing mint price, with NCR staying in the low cents during this time period. The money from this ICO was intended to be used to pay for development costs. NCR was primarily managed by the CEO of Neos, Karel Hulec, with the software being handled by Frooxius, the primary developer/CTO of Neos, in addition with other team members.

In mid-to-late 2021, everything changed. Metaverse hype went off the rails as a result of the Meta rebranding, and Steam banned crypto games from its storefront. This perfect storm of two events resulted in NCR rocketing from its value of a few cents up to a peak of ten dollars, through the sheer power of Moon:tm:, and resulted in both the introduction of the crypto community in all of its true slur-lovin' pepe-wearing glory to Neos, as well as several long-time NCR holders exiting their position with a new house or with a new car. 

Karel wanted to capitalise on this and promptly undertook a public poll, visible only to people actively engaging with the NCR community (which at this point has siloed itself away from the wider Neos community, due to mutual distaste), to decide what the future of NCR would be. After a deeply polarising and unsatisfactory debate, involving Discord react polls gone mad, Karel decided to prop up the value of NCR, spending 8,000 ETH of the 13,000 ETH in the ICO wallet to buy up NCR and drive it up. Yes, he spent _40 million dollars_ of the 60 million dollars that crypto had brought in for fundraising.

After this, there was silence from the team. Come February, and Frooxius, makes a [joint statement with the rest of the team](https://twitter.com/Frooxius/status/1491880566479892483) in which they express discontent with Karel's side of the operation, and mention an ongoing negotiation behind the scenes to resolve this. Several blows are traded on Twitter and Discord:

- Karel responds to the initial statement (now deleted)
- Frooxius puts out another public statement, implying that the team-wide problems are wider than the community imagined: https://twitter.com/Frooxius/status/1492657273109422080
- Karel puts out a reply to this in which he makes some unsettling claims about his interactions with Frooxius: https://twitter.com/KarelHulec/status/1492825107147939844

For a few weeks, there is mostly silence, with Karel occasionally posting in Discord and then moving to Telegram once the tone on the Discord turns mostly-hostile against him. NCR is pegged to a dollar by the use of a five million dollar liquidity pool, but it's not moving in any particular direction as not much is happening. Karel promises to try and get things up and running again, and that he is doing his best at the negotiation table with the rest of the team. By this point, the majority of the 60 million dollar ICO fund has been drained on buybacks, with Karel stating that this was him applying a vote of confidence to the token.

Yesterday, he fucked up. He published an update to the crypto whitepaper outlining his vision for Neos, with updated "tokenomics", but did not remove Frooxius's name from it, lending it credence that it did not merit (keep in mind that, over the past three months, the team has stopped work for the most part and has explicitly disclaimed Karel's ability to make claims on behalf of the team.)

A few hours later, [Frooxius and the team drop the hammer](https://twitter.com/Frooxius/status/1499883137706377220). Frooxius finally takes the gloves off as a result of Karel fraudulently using his credentials, whether by accident or not, and officially disclaims any further association with Karel. The most damning part for us, of course, is this:

> We no longer believe that there is any space for Karel in our shared goal, even though he has done a number of things to help the project outside of its development. As such we have been working on a fair dissolution of our cooperation with him over the past months, but it has been taking longer than we hoped. On behalf of the whole team, I’d like to ask you for more patience. We're doing what we can, because we’ve been itching to get things moving again for a while, but certain legal matters need to be settled first.
> 
> Our proposal would also let Karel independently implement and distribute NCR functionality on top of our work, but as a 3rd party solution, under a company solely under his ownership and direction and derive value from our development efforts for NCR holders. We will no longer provide first party support ourselves and at the same time we will not be further involved with any NCR related decisions and actions.
> 
> Many of the recent transfers of tokens to liquidity isn’t something that we understand and something nobody on the team was consulted or informed on. Any actions regarding NCR are done purely by Karel and therefore he holds full responsibility. Our goal is to still use the funding for its actual intended purpose - development of this project.
> 
> Karel’s unilateral actions with the new whitepaper, together with a number of his actions regarding NCR and funding, both public and private, have led to significant doubts on me and my team’s side in regards to Karel’s handling of NCR, crypto and business. I do not support his whitepaper and have formally requested to have my name removed.

Many of the crypto investors who had spent money on Neos had been promised that the value of NCR would go up as people transacted within Neos, with the value of the token being attached to Neos's growth and usability as a platform. Frooxius's announcement officially declared an intent on behalf of the team to decouple NCR from the platform, so that it could still be used for transactions, but it would no longer be a part of the core Neos proposition.

So of course the price of NCR crashed (at time of submission, it is at $0.59 and the five million dollar liquidity pool is completely gone). The announcement destroyed the "inherent value" argument for NCR's pricing, and now people are very much in the red. A lot of people, actually, who overinvested in the promises of a metaverse platform being made by people who didn't seem to really care for the crypto component of what they were building...

In any case, it's still early days for this glorious post-NCR future, and it's unclear how everything will shake out. One thing is sure, though: Neos is dead, long live Neos! May it live a glorious crypto-free life, and be known for its technology, not for its shitcoin!

### Links

https://neos.com/
https://twitter.com/Frooxius/status/1491880566479892483
https://twitter.com/KarelHulec/status/1492825107147939844
https://twitter.com/Frooxius/status/1499883137706377220

### Agreement

- [X] I irrevocably agree to release my contribution under the CC-BY 3.0 License

### Attribution name

Philpax

### Personal link

[https://twitter.com/philpax_](https://twitter.com/philpax_)

**Comment by molly** [comment]
This is much too long for the site, though I will add a shortened version. If you release a blog post with this detail I will happily link to it.

**Comment by molly** [comment]
[Added here ](https://web3isgoinggreat.com/?id=2022-03-04-1) ([tweet](https://twitter.com/web3isgreat/status/1500563751807950857)). Let me know if you publish a blog post and I'll update the entry with a link.

**Comment by philpax** [comment]
Brilliant, thank you! Yes, I'll let you know if I write it up.

fyi noticed a typo: "th eteam"

**Comment by molly** [comment]
oop, thanks

**Comment by L33Tech** [comment]
@philpax If you need anything for your blog post just let me know. I'm sure you can find me on Discord at this point. :P
