### ISSUE TITLE
Jump to date

### ISSUE THREAD

**Issue by molly** [molly/web3-is-going-great#19]
Add the ability to jump to a specific month. As we enter 2022 this will probably be needed for readability.

**Comment by jose8109** [comment]
todo me hackearon el telefono

**Comment by jose8109** [comment]
no se que se creen para destruir mi privacidad modificando todo entrando en lugares que nunca entre o bien inventando situaciones

**Comment by jose8109** [comment]
no se quien tiene acceso a mi teléfono, no puede ser que no pueda ni siquiera hablar por teléfono, con nadie no puedo hacer nada expusieron y cambiaron mis archivos
