### ISSUE TITLE
[NEW]: Stronghold Digital Mining saves coal plants from shutdown with crypto mining and get to greenwash themselves and collect tax dollar

### ISSUE THREAD

**Issue by bindestrichsoz** [molly/web3-is-going-great#194]
### Date

2020-10-20

### Description

Coal plants in the US are already running at a loss. Stronghold (SDIG) overcomes this by using the power for their own mining rigs. The company already bought 2 coal plants in Pennsylvania  with over 160MW generation capacity and is on route to buy more. The plants use waste coal, a by-product of coal mining. Pennsylvania classifies the burning of waste coal, also called Coal Refuse, as a Tier II Alternative Energy, the same class as hydropower.  While removing the abandoned waste coal is indeed good for the environment, the carbon emissions of burning coal are not. Regardless of this, the plants are eligible for 4 different public subsidies. 

### Links

https://www.puc.pa.gov/general/consumer_ed/pdf/AEPS_Fact_Sheet.pdf
https://www.pennfuture.org/Blog-Item-Chasing-Bitcoin-is-a-Bad-Investment-for-Pennsylvania
https://carbontracker.org/reports/how-to-waste-over-half-a-trillion-dollars/
https://strongholddigitalmining.com/the-facility/

### Agreement

- [X] I irrevocably agree to release my contribution under the CC-BY 3.0 License

### Attribution name

@bindestriche

### Personal link

@bindestriche

**Comment by molly** [comment]
2020 is before the time period I'm aiming to cover with this project
