### ISSUE TITLE
[NEW]: Mexican Cartels turn to bitcoin for money laundering.

### ISSUE THREAD

**Issue by Leath563** [molly/web3-is-going-great#196]
### Date

2022-3-10

### Description

Severas news outlets have reported the UN's International Narcotics Control Board has recently submitted a report stating that Mexican Cartels have turned to bitcoin and crypto investments as a way to launder money. This follows several reports in recent years that have referred cryptocurrencies being used frequently as payment for drugs online. Report suggests Cartels use cryptocurrencies to pay their associates worldwide.

### Links

https://www.washingtonpost.com/business/mexican-cartels-turn-to-bitcoin-internet-e-commerce/2022/03/10/b910270c-a097-11ec-9438-255709b6cddc_story.html
https://www.google.com/amp/s/abcnews.go.com/amp/International/wireStory/mexican-cartels-turn-bitcoin-internet-commerce-83367341

### Agreement

- [X] I irrevocably agree to release my contribution under the CC-BY 3.0 License

### Attribution name

@zulueta1

**Comment by molly** [comment]
Not including this because they seem to be referencing a report that predates the time frame I cover in this site: https://www.reuters.com/article/mexico-bitcoin-insight/latin-american-crime-cartels-turn-to-cryptocurrencies-for-money-laundering-idUSKBN28I1KD
