### ISSUE TITLE
"Force dark mode" feature in a non dark mode browser produces illegible contrast

### ISSUE THREAD

**Issue by elektronik2k5** [molly/web3-is-going-great#222]
Hi and thanks for this project!

The issue is a bit of an edge case, but a serious one cause it results in a the feature being completely broken exactly where it should work:
1. Open website in a browser which isn't dark mode aware. This reproduces for me in two browsers on Linux with Gnome3: (a) Google Chrome stable channel (probably cause Chrome doesn't pick up the dark theme setting form the OS) and ["Web" (such a stupid name for a browser, but whatever)](https://wiki.gnome.org/Apps/Web), probably for the same reason.
2. Click the gears icon in the bottom right corner > check "Force dark mode". The front page looks fine, which is probably why nobody reported this issue so far.
3. Navigate to any of the other content pages: https://web3isgoinggreat.com/glossary, https://web3isgoinggreat.com/what or https://web3isgoinggreat.com/about.

Result in Chrome:
![image](https://user-images.githubusercontent.com/1078554/160153891-924c600a-d77d-4d93-9d96-4f0f37cbdfcd.png)

"Web" browser:
![image](https://user-images.githubusercontent.com/1078554/160154047-571d50b0-ecc7-4a6e-ad55-227ed64a15cd.png)

If anyone else cares about this then I can probably fix the bug myself.

**Comment by Naleksuh** [comment]
I tried your replication steps and got this:
![image](https://user-images.githubusercontent.com/24828999/160780616-47d42bc0-c068-4b91-8b5e-89e47a22981a.png)

Except this seems to be what is expected. What is expected to happen differently?

**Comment by elektronik2k5** [comment]
The text should be legible, like so:
![image](https://user-images.githubusercontent.com/1078554/160854656-2b06fd22-3a53-4759-bf66-2128cb0d9f96.png)
Screenshot from Brave browser, which is aware of the dark theme and applies it automatically.

Similarly, in Firefox:
![image](https://user-images.githubusercontent.com/1078554/160855012-1ef9d14e-5abd-454c-a5b9-92657aeec761.png)

**Comment by molly** [comment]
Thanks so much for the report, @elektronik2k5, there was definitely a bug there. Should be all set now!

**Comment by elektronik2k5** [comment]
Looks good now, thanks!
