### ISSUE TITLE
[EDIT] 2022-03-29-1

### ISSUE THREAD

**Issue by cryptog0** [molly/web3-is-going-great#239]
# Entry
id=2022-03-29-1

# Changes
in which they stated unequivocally that "**he** same rules apply to

he -> the

# Agreement
By submitting this issue, I irrevocably agree to release my contribution under the [CC-BY 3.0 License](http://creativecommons.org/licenses/by/3.0/deed.en_US). I agree that a hyperlink or URL is sufficient attribution under the Creative Commons license.

**Comment by molly** [comment]
Good catch, thank you!
