### ISSUE TITLE
[EDIT]: Adidas NFT drop attribution

### ISSUE THREAD

**Issue by anematode** [molly/web3-is-going-great#241]
# Entry
December 17, 2021 ("Adidas learns ... ")

# Changes
The article incorrectly states Montana Wong was the person who got hundreds of NFTs; she just reported about it. Removing her name from the main text works, or attributing it to them at the end of the sentence.

```They apparently didn't realize that there is no guarantee that one address = one individual, and a crafty blockchain engineer, Montana Wong, created a smart contract that generated additional smart contracts, each with their own address.```
->
```They apparently didn't realize that there is no guarantee that one address = one individual; a crafty blockchain engineer created a smart contract that generated additional smart contracts, each with their own address, according to blockchain developer Montana Wang.```

# Agreement
By submitting this issue, I irrevocably agree to release my contribution under the [CC-BY 3.0 License](http://creativecommons.org/licenses/by/3.0/deed.en_US). I agree that a hyperlink or URL is sufficient attribution under the Creative Commons license.

Please attribute this contribution to:
* Timothy Herchen
*

**Comment by molly** [comment]
Good spot, thank you!

**Comment by anematode** [comment]
Oops, I didn't see that their name was used later too. Probably should replace `Wong was able to snag 330 NFTs.` with `They were able to snag 330 NFTs.`

**Comment by molly** [comment]
I missed it too! Good catch.
