### ISSUE TITLE
[NEW]: Official Formula 1 NFT Game Shuts Down, Tokens Are Now Practically Worthless

### ISSUE THREAD

**Issue by eliotgerson** [molly/web3-is-going-great#253]
### Date

2022-04-04

### Description

Official Formula 1 NFT Game Shuts Down, Tokens Are Now Practically Worthless... self explanatory

### Links

https://kotaku.com/f1-formula-1-one-delta-time-nft-crypto-cursed-shut-down-1848748953

### Agreement

- [X] I irrevocably agree to release my contribution under the CC-BY 3.0 License

### Attribution name

anonymous / no attribution

**Comment by molly** [comment]
Already on the site, just at an earlier date: https://web3isgoinggreat.com/?id=2022-03-15-4

Thanks!
