### ISSUE TITLE
[NEW]: Ubisoft ends updates to Tom Clancy's Ghost Recon: Breakpoint, including minting new NFTs

### ISSUE THREAD

**Issue by ToadKing** [molly/web3-is-going-great#254]
### Date

2022-04-06

### Description

Ubisoft announced it is no longer making updates for Tom Clancy's Ghost Recon: Breakpoint, including minting new "Ubisoft Quartz" NFTs for the game. On the NFT marketplace page for the game they now have a message congratulating players who now "own a piece of the game and have left your mark in its history". Ubisoft also claims they will continue to add NFTs to future games.

### Links

https://www.gamesindustry.biz/articles/2022-04-06-ubisoft-ends-ghost-recon-breakpoint-development-working-on-nfts-for-other-titles
https://twitter.com/GhostRecon/status/1511373147475484682
https://quartz.ubisoft.com/Game:7c788439-f696-4362-8848-d719eeb3e9d2

### Agreement

- [X] I irrevocably agree to release my contribution under the CC-BY 3.0 License

### Attribution name

Toad King

### Personal link

https://twitter.com/TheToadKing

**Comment by molly** [comment]
https://web3isgoinggreat.com/?id=2022-04-05-3
