### ISSUE TITLE
[NEW]: Four Months after adding NFTs to Ghost Recon Breakpoint, Ubisoft rug pulls 

### ISSUE THREAD

**Issue by hanzov69** [molly/web3-is-going-great#255]
### Date

2021-04-06

### Description

In mid-December 2021, Ubisoft launched their Quartz platform for purchasing NFTs. Ghost Recon Breakpoint featured these NFTs as in-game equipment. Four month later, Ubisoft has announced that they will no longer be updating Ghost Recon Breakpoint. The last NFT for the game was released mid-March 2022. Ubisoft thanked players for "owning" a piece of the game and encouraged them to stay tuned for future opportunities to buy NFTs for other games; there is no news regarding if (or how) the current NFTs may be used for future titles. 

### Links

https://www.theverge.com/2022/4/6/23013346/ubisoft-ghost-recon-breakpoint-content-nft-digits-quartz

### Agreement

- [X] I irrevocably agree to release my contribution under the CC-BY 3.0 License

### Attribution name

Mr. Christian

### Personal link

https://go.fuckyourselv.es

**Comment by molly** [comment]
https://web3isgoinggreat.com/?id=2022-04-05-3
