### ISSUE TITLE
Automation to validate RSS feed

### ISSUE THREAD

**Issue by molly** [molly/web3-is-going-great#26]
I keep accidentally breaking the RSS feed and not realizing it until someone reports a problem.

**Comment by paposeco** [comment]
Can confirm that currently RSS feed is broken. Thunderbird checks if the feed is valid on [validator.w3.org](https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fweb3isgoinggreat.com%2Ffeed.xml) and I think you might be able to find a clue there.

**Comment by molly** [comment]
Closed in 42f9b8f3c7b97fd091220e60c2e87a75da6449e0
