### ISSUE TITLE
[EDIT] Star Trek NFTs

### ISSUE THREAD

**Issue by philipkd** [molly/web3-is-going-great#260]
# Entry
[Star Trek Gets into NFTs](https://web3isgoinggreat.com/?id=2022-04-06-0)

# Changes
I love the site and I check it every day. I also love Star Trek. However, I couldn't find anything that was bad in the Star Trek NFT news, unless we're assuming that just associating with NFTs is sufficiently negative.

# Agreement
By submitting this issue, I irrevocably agree to release my contribution under the [CC-BY 3.0 License](http://creativecommons.org/licenses/by/3.0/deed.en_US). I agree that a hyperlink or URL is sufficient attribution under the Creative Commons license.

**Comment by molly** [comment]
> unless we're assuming that just associating with NFTs is sufficiently negative.

You got it. It's pretty antithetical to the stories _Star Trek_ tries to tell, if you ask me.
