### ISSUE TITLE
feature: add vanity/title chunk in URL after slug

### ISSUE THREAD

**Issue by nschonni** [molly/web3-is-going-great#269]
Sorry I'm failing to think of the right word, so I'm using "vanity" for a user readable chunk of the title after the actual permalink slug.
EX: `https://www.theverge.com/23022777/hasbro-robosen-transforming-optimus-prime-robot-trailer` the portion I'm talking about is the `hasbro-robosen-transforming-optimus-prime-robot-trailer` that is a simply escaped copy of the title, but if someone puts any arbitrary value it will still resolve with the actual proceeding slug.

Why: I find it easier to (mentally) parse when coming across the cross post links if I can tell the article titles

Why not: Might be a pain to sort out these links in your CMS for possibly the benefit of only a few people that like that link style

**Comment by molly** [comment]
I am actually working on this feature as we speak! Appreciate you opening an issue for it.
