### ISSUE TITLE
RSS feed titles don't show up in NetNewsWire

### ISSUE THREAD

**Issue by Gaelan** [molly/web3-is-going-great#27]
Hi, thanks for doing this!

My RSS reader of choice, [NetNewsWire](https://netnewswire.com), somehow isn't able to see article titles in your feed:

<img width="1553" alt="Screen Shot 2022-01-06 at 2 40 51 PM" src="https://user-images.githubusercontent.com/4495750/148462438-7193c09e-98f4-44c5-9c98-a8719f125e76.png">

I suspect it has to do with the XML you're using for the title. You do something like this:

```xml
<title type="xhtml"><div xmlns="http://www.w3.org/1999/xhtml">Matt Damon stars in a truly cringeworthy ad for Crypto.com</div></title>
```

But a random sampling of other RSS feeds I follow all just do this:

```xml
<title>[$] LWN's unreliable predictions for 2022</title>
<!-- or, in one case I found -->
<title><![CDATA[Weekly Update 267]]></title>
```

Not sure if this is your bug or NetNewsWire's.

**Comment by molly** [comment]
Does it work now? I've removed the HTML from titles.

**Comment by Gaelan** [comment]
Yes! Thanks.
