### ISSUE TITLE
[NEW]: "$650,000" stolen from MetaMask wallet due to Apple phishing attack

### ISSUE THREAD

**Issue by xfix** [molly/web3-is-going-great#284]
### Date

2022-04-17

### Description

Backups of MetaMask wallet for iOS stored on iCloud contained seed. An attacker used a phishing attack to get access to iCloud account, and the seed was used to steal NFTs.

### Links

https://twitter.com/Serpent/status/1515545806857990149

### Agreement

- [X] I irrevocably agree to release my contribution under the CC-BY 3.0 License

### Attribution name

@xfix

### Personal link

https://www.xfix.pw/

**Comment by molly** [comment]
Thank you! https://web3isgoinggreat.com/?id=metamask-credentials-backed-up-to-icloud
