### ISSUE TITLE
[NEW]: Coffeezilla's new piece on the Safemoon fiasco

### ISSUE THREAD

**Issue by isonno** [molly/web3-is-going-great#285]
### Date

2022-04-18

### Description

Coffeezilla has a [new video](https://www.youtube.com/watch?v=CzbBi0agLNg&ab_channel=Coffeezilla) out giving the rundown on the $3B Safemoon fiasco.

### Links

https://www.youtube.com/watch?v=CzbBi0agLNg&ab_channel=Coffeezilla

### Agreement

- [X] I irrevocably agree to release my contribution under the CC-BY 3.0 License

### Attribution name

J. Peterson

**Comment by molly** [comment]
Thanks! I've added the link to an existing entry on SafeMoon: https://web3isgoinggreat.com/?id=safemoon-class-action
