### ISSUE TITLE
Back button does not return to article after viewing contribute page

### ISSUE THREAD

**Issue by Xkeeper0** [molly/web3-is-going-great#288]
Original URL: https://web3isgoinggreat.com/?id=first-crypto-burger-purchase-at-bored-ape-restaurant-illustrates-why-people-dont-widely-do-this

If I click the "Contribute" link in the header, the browser URL changes to https://web3isgoinggreat.com/contribute and the Contribute page is displayed.

If I then use the browser's back button (or hotkey/shortcut), the browser URL will revert to the article, but the actual page itself does not change, and stays on the "Contribute" page.

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.88 Safari/537.36

**Comment by molly** [comment]
Thanks for the report! 4078109fd63322a21589bc1afbfb656ac5e864a6 should close this, but if you encounter more issues please feel free to reopen.
