### ISSUE TITLE
Text in definition buttons can't be selected in Firefox

### ISSUE THREAD

**Issue by AntiCompositeNumber** [molly/web3-is-going-great#289]
Trying to select and copy `"hodl and help us bring this back to life!"` from https://web3isgoinggreat.com/?id=developers-drain-11-million-from-chedda, for example, results in only `" and help us bring this back to life!"` being copied to the clipboard.
![image](https://user-images.githubusercontent.com/10331574/164811997-6e226aea-8e7a-4c71-8453-9909ab8ca8a1.png)

Tested in Firefox 99.0.1 on Linux. Could not reproduce in Google Chrome 100.0.4896.127.

**Comment by molly** [comment]
Hmm, I'm not able to repro this on Firefox 99.0.1 on OSX. Will dig a bit.
