### ISSUE TITLE
[NEW]: Norton 360 Now Comes With a Cryptominer

### ISSUE THREAD

**Issue by shaunco** [molly/web3-is-going-great#29]
### Date

2022-01-06

### Description

Norton 360, one of the most popular antivirus products on the market today, has installed a cryptocurrency mining program on its customers’ computers.

### Links

https://krebsonsecurity.com/2022/01/norton-360-now-comes-with-a-cryptominer/

### Agreement

- [X] I irrevocably agree to release my contribution under the CC-BY 3.0 License

### Attribution name

None

**Comment by molly** [comment]
Thanks! I've added the Krebs link to the existing entry: https://web3isgoinggreat.com/?id=2021-07-20-0
