### ISSUE TITLE
[NEW]: How crypto giant Binance built ties to a Russian FSB-linked agency

### ISSUE THREAD

**Issue by sokirill** [molly/web3-is-going-great#290]
### Date

2022-04-23

### Description

Russian intelligence agencies received from Binance, the largest crypto exchange in the world, information about users who made large transfers to the Anti-Corruption Foundation (FBK, an organization recognized as extremist and banned in Russia) Alexei Navalny. According to Reuters, Rosfinmonitoring employees agreed on this in April 2021 with the head of Binance for Eastern Europe and Russia, Gleb Kostarev.

Financial intelligence required the exchange to provide customer data, including names and addresses, “to help fight crime.” According to Reuters sources, Kostarev admitted to his partners that he had no choice. The company said that the Russian authorities never contacted Binance about Navalny.

### Links

https://www.reuters.com/technology/how-crypto-giant-binance-built-ties-russian-fsb-linked-agency-2022-04-22/

### Agreement

- [X] I irrevocably agree to release my contribution under the CC-BY 3.0 License

**Comment by molly** [comment]
Thank you! https://web3isgoinggreat.com/?id=binance-gave-putin-regime-information-on-users-who-donated-to-opposition-leader-alexei-navalny
