### ISSUE TITLE
[NEW]: $34M Ether Burn Cause Bad Code

### ISSUE THREAD

**Issue by misterducky** [molly/web3-is-going-great#291]
### Date

4/22/2022

### Description

Because a dev wrote some bad code in some NFT smart contract, $34M worth of Ether is lost forever.

### Links

https://twitter.com/0xfoobar/status/1517680400142716929

### Agreement

- [X] I irrevocably agree to release my contribution under the CC-BY 3.0 License

**Comment by molly** [comment]
Thanks! https://web3isgoinggreat.com/?id=akudreams-earns-34-million-team-will-never-be-able-to-withdraw
