### ISSUE TITLE
Attribution link isn't clickable in some entries

### ISSUE THREAD

**Issue by salty-horse** [molly/web3-is-going-great#292]
In some entries, the attribution link isn't clickable, and hovering over the caption text doesn't turn the cursor into the "text selection" type.
I'm assuming another element is on top of it, blocking it (Manually deleting paragraph elements in the entry seems to fix it).

Tested in Firefox and Chrome.

Examples where the attribution link isn't clickable:
* https://web3isgoinggreat.com/?id=akudreams-earns-34-million-team-will-never-be-able-to-withdraw
* https://web3isgoinggreat.com/?id=andre-cronje-calls-for-crypto-regulation

Examples where it's clickable:
* https://web3isgoinggreat.com/?id=binance-adds-a-branded-emoji-to-twitter-that-closely-resembles-a-swastika
* https://web3isgoinggreat.com/?id=metamask-credentials-backed-up-to-icloud

**Comment by molly** [comment]
Thanks so much for catching this!
