### ISSUE TITLE
[NEW] NFTs "celebrating" the life of George Floyd are sold, with no apparent link to his family

### ISSUE THREAD

**Issue by astamos** [molly/web3-is-going-great#3]
# Date
December 11, 2021

# Description/blurb
An anonymous NFT "artist" released a collection of poorly made NFTs featuring the late George Floyd, whose murder by a police officer in May 2020 set off protests around the world. There is no apparent link to his family or any social justice charity; this is just a scam to make money off of the memory of a murder victim. 

# Links
https://opensea.io/collection/floydies

# Agreement
By submitting this issue, I irrevocably agree to release my contribution under the [CC-BY 3.0 License](http://creativecommons.org/licenses/by/3.0/deed.en_US). I agree that a hyperlink or URL is sufficient attribution under the Creative Commons license.

Please attribute this contribution to:

**Comment by molly** [comment]
Added, thank you.
