### ISSUE TITLE
[NEW]: MetaDocs (Web 3 "Healthcare")

### ISSUE THREAD

**Issue by The1AndMany** [molly/web3-is-going-great#304]
### Date

04-25-2022

### Description

MetaDocs is an NFT project that promises to provide healthcare to any of its holders. Given the previous sentence, it should surprise exactly nobody that the project is a metaphorical dumpster fire. Among numerous other concerns like pledging donations to a "Vaccines Cause Autism" charity and the removal of some doctors from the project's roster due to claims that they've never agreed to participate, it turns out they don't even have the proper licenses required to provide telehealth in the first place. I.e., the project's primary selling point.

Warning for the link provided: It's a deep dive. Prepare to spend a good 30 minutes reading.

### Links

https://www.buzzfeednews.com/article/emilybakerwhite/metadocs-nfts-tiktok-instagram-celebrity-doctors

### Agreement

- [X] I irrevocably agree to release my contribution under the CC-BY 3.0 License

### Attribution name

Rez

**Comment by molly** [comment]
Thank you! https://web3isgoinggreat.com/?id=metadocs-nft-project-wants-tiktok-famous-doctors-to-diagnose-you-but-they-dont-have-a-license
