### ISSUE TITLE
[NEW]: Crypto Color Collection is released

### ISSUE THREAD

**Issue by R3Ked** [molly/web3-is-going-great#31]
### Date

2021-2-20

### Description

Crypto Color Collection is a collection of NFTs that allow people to buy NFTs featuring only a single color as well as a label saying exactly which color it is as well as the name of the project, starting with the color black. As of January 10th, 2022, the first NFT is going for $3,000.
Yep, people are buying literal colors now.
![unnamed](https://user-images.githubusercontent.com/20342336/148841978-564548d4-81ac-4f38-9d8f-1ed24172c3fa.png)

### Links

https://opensea.io/assets/0x495f947276749ce646f68ac8c248420045cb7b5e/70893885489976215591627014725549049728091981516033634167103779792466066014209
https://opensea.io/assets/matic/0x2953399124f0cbb46d2cbacd8a89cf0599974963/70893885489976215591627014725549049728091981516033634167103781435136437911553
https://opensea.io/collection/crypto-color-collection

### Agreement

- [X] I irrevocably agree to release my contribution under the CC-BY 3.0 License

**Comment by molly** [comment]
they're better-looking than a lot of the NFT projects I've seen 😛 I'll probably leave this off unless they end up rugpulling or something
