### ISSUE TITLE
[NEW]: Bitcoin becomes official currency in Central African Republic

### ISSUE THREAD

**Issue by paulmwatson** [molly/web3-is-going-great#318]
### Date

2022-04-28

### Description

Just 4% of people in CAR (Central African Republic) have access to the internet yet this poor, war torn, and undeniably corrupt country, rich in diamonds, gold and uranium, has adopted Bitcoin as official currency.

### Links

https://www.bbc.com/news/world-africa-61248809

### Agreement

- [X] I irrevocably agree to release my contribution under the CC-BY 3.0 License

### Attribution name

Paul Watson

### Personal link

https://paulmwatson.com

**Comment by molly** [comment]
Thank you! https://web3isgoinggreat.com/?id=central-african-republic-adopts-bitcoin-as-legal-tender
