### ISSUE TITLE
[NEW]: 

### ISSUE THREAD

**Issue by BreakerSwitch** [molly/web3-is-going-great#320]
### Date

2022-5-2

### Description

NFT sales are down 92% since September of last year.

### Links

https://www.wsj.com/articles/nft-sales-are-flatlining-11651552616

### Agreement

- [X] I irrevocably agree to release my contribution under the CC-BY 3.0 License

### Attribution name

Vince

**Comment by molly** [comment]
Thanks! https://web3isgoinggreat.com/?id=nft-sales-drop-92-from-peak
