### ISSUE TITLE
[EDIT] Entry feels like service is being co-opted to advertise a project instead of reporting on issues with it

### ISSUE THREAD

**Issue by clarjon1** [molly/web3-is-going-great#321]
# Entry

https://web3isgoinggreat.com/?id=ape-holders-can-use-multiple-slurp-juices-on-a-single-ape
# Changes

Not sure how to change it but this feels more like just someone using web3isgoinggreat to advertise their thing, given that it's just their own advertisement tweet without any context, rewording, etc?
# Agreement
By submitting this issue, I irrevocably agree to release my contribution under the [CC-BY 3.0 License](http://creativecommons.org/licenses/by/3.0/deed.en_US). I agree that a hyperlink or URL is sufficient attribution under the Creative Commons license.

Please attribute this contribution to:
* 
*

**Comment by molly** [comment]
Just making a joke based on a completely incomprehensible tweet that went out earlier today: https://twitter.com/rarecandyio/status/1521548615579226114

Don't worry, it's still me at the wheel and I haven't pivoted to NFT ads 😄

**Comment by clarjon1** [comment]
phew that's a relief! thanks for the update!! 💚
