### ISSUE TITLE
[EDIT] Potential typo in most recent entry

### ISSUE THREAD

**Issue by anematode** [molly/web3-is-going-great#325]
# Entry
[most recent entry](https://web3isgoinggreat.com/?id=mmfinance-suffers-apparent-frontend-breach)
(May 4)

# Changes
When you click on "phished" it gives you a hint about "FUD", not "phished", at least on my end. 

# Agreement
By submitting this issue, I irrevocably agree to release my contribution under the [CC-BY 3.0 License](http://creativecommons.org/licenses/by/3.0/deed.en_US). I agree that a hyperlink or URL is sufficient attribution under the Creative Commons license.

Please attribute this contribution to:
* Timothy Herchen

**Comment by molly** [comment]
Good catch, thank you! Bad copy-paste 😄
