### ISSUE TITLE
[NEW]: $750M "loaned" from Luna stablecoin to support TerraUSD

### ISSUE THREAD

**Issue by LemmaEOF** [molly/web3-is-going-great#340]
### Date

2022-05-09

### Description

After [TerraUSD's peg broke](https://web3isgoinggreat.com/?id=terrausd-ust-stablecoin-struggles-to-retain-peg) today, the Luna stablecoin foundation has pledged to loan $750M in Bitcoin to TerraUSD in order to protect the project's stability. This was done by...transferring more than two thirds of the Luna reserve wallet, totaling about $1.4B, before having approximately $877M returned. Whether this is good-faith or one of the biggest rug-pulls on record is yet to be seen.

### Links

https://twitter.com/DaxxTrader/status/1523732538350395392
https://twitter.com/LFG_org/status/1523512196965167104

### Agreement

- [X] I irrevocably agree to release my contribution under the CC-BY 3.0 License

### Attribution name

LemmaEOF

### Personal link

https://twitter.com/LemmaEOF

**Comment by molly** [comment]
Mentioned in https://web3isgoinggreat.com/?id=terrausd-ust-stablecoin-struggles-to-retain-peg already
