### ISSUE TITLE
[NEW]: MM.Finance “DNS attack”

### ISSUE THREAD

**Issue by hpshelton** [molly/web3-is-going-great#341]
### Date

2022-05-04

### Description

The Mad Meerkat Finance platform—or MM.Finance—said it lost $2 million worth of cryptocurrency last week due to a “DNS attack” “where an attacker managed to inject a malicious contract address into the frontend code.”

### Links

https://medium.com/@MMFinance/dns-hi-jacking-post-mortem-compensation-3e2b5bb21183

### Agreement

- [X] I irrevocably agree to release my contribution under the CC-BY 3.0 License

**Comment by molly** [comment]
Already covered at https://web3isgoinggreat.com/?id=mmfinance-suffers-apparent-frontend-breach
