### ISSUE TITLE
[NEW]: Fake Yuga Labs Website Tricks Collectors Into Handing Over $6.2 Million Worth of Bored Apes and Other NFTs

### ISSUE THREAD

**Issue by ellulpatrick** [molly/web3-is-going-great#342]
### Date

2022-05-05

### Description

Hackers posing as the administrators behind the Otherside NFT, a new virtual game and metaverse by the creators of BAYC, Yuga Labs, lured crypto collectors by creating a fake website designed to look identical to the original before making off with approximately $6.2 million worth of BAYCs and other popular non-fungible artworks.

### Links

https://news.artnet.com/art-world/bored-ape-yacht-club-hack-2109480 

### Agreement

- [X] I irrevocably agree to release my contribution under the CC-BY 3.0 License

**Comment by molly** [comment]
https://web3isgoinggreat.com/?id=phishing-sites-appearing-to-be-the-otherside-bored-ape-land-project-steal-nfts-valued-at-6-million
