### ISSUE TITLE
RSS feed not updating

### ISSUE THREAD

**Issue by sesh** [molly/web3-is-going-great#343]
👋. I was wondering why I hadn't seen updates for a couple of days in Feedbin (especially with all the LUNA shenanigans!) and noticed that the RSS feed has stopped updating.

Hopefully it's not something that's too terminal!

**Comment by molly** [comment]
Agh, thanks, not sure why the alert I set up didn't fire. Should be ok now!

**Comment by sesh** [comment]
Thanks a bunch for the super quick fix (on the weekend!). Love following the site and the madness!
