### ISSUE TITLE
[NEW]: 

### ISSUE THREAD

**Issue by joeldg** [molly/web3-is-going-great#350]
### Date

May 16, 2022

### Description

Miamicoin down 95%

### Links

https://qz.com/2165639/miamis-mayor-backed-miamicoin-then-its-price-dropped-95-percent/

### Agreement

- [X] I irrevocably agree to release my contribution under the CC-BY 3.0 License

### Attribution name

joeldg

**Comment by molly** [comment]
Already somewhat covered at https://web3isgoinggreat.com/?id=miamicoin-loses-money-for-investors
