### ISSUE TITLE
[NEW]: U.S. issues charges in first criminal cryptocurrency sanctions case

### ISSUE THREAD

**Issue by hagandazs** [molly/web3-is-going-great#352]
### Date

2022-05-16

### Description

Last week America's Justice Department "launched its first criminal prosecution involving the alleged use of cryptocurrency to evade U.S. economic sanctions," reports the Washington Post. They cite a nine-page opinion from a federal judge approving the government's criminal complaint against an American "accused of transmitting more than $10 million worth of bitcoin to a virtual currency exchange in one of a handful of countries comprehensively sanctioned by the U.S. government: Cuba, Iran, North Korea, Syria or Russia.

### Links

https://www.msn.com/en-us/money/news/us-issues-charges-in-first-criminal-cryptocurrency-sanctions-case/ar-AAXkfZp

### Agreement

- [X] I irrevocably agree to release my contribution under the CC-BY 3.0 License

**Comment by molly** [comment]
https://web3isgoinggreat.com/?id=american-running-untraceable-service-designed-to-evade-us-sanctions-is-charged-after-being-traced
