### ISSUE TITLE
[NEW]: Troy Baker partnered with an NFT project that secretly used 15.ai without any credit or any real tech

### ISSUE THREAD

**Issue by SaphireLattice** [molly/web3-is-going-great#36]
### Date

2022-01-14

### Description

A "vocaloid NFT" project that Troy Baker has partnered with turned out to be using 15.ai to general all the voice lines. When this was revealed, they cited that they are only a week away from having actual tech to do what they are already selling. The original tweet has been since deleted.

### Links

https://twitter.com/fifteenai/status/1482076584517455884

### Agreement

- [X] I irrevocably agree to release my contribution under the CC-BY 3.0 License

**Comment by molly** [comment]
https://web3isgoinggreat.com/?id=2022-01-14-0 thank you!
