### ISSUE TITLE
[NEW]: Seth Green is now unable to launch a NFT-centric comedy show due to his apes getting stolen

### ISSUE THREAD

**Issue by The1AndMany** [molly/web3-is-going-great#363]
### Date

2022-05-24

### Description

Seth Green (of Robot Chicken fame) recently had his NFT wallet drained after falling for a phishing scam. (As has been [previously reported on this very site](https://web3isgoinggreat.com/?id=four-pricey-nfts-stolen-from).) It turns out that this has thrown a "monkey wrench" in his plans to launch a comedy show called White Horse Tavern where half the characters are NFTs. BAYC was among the first NFT projects to adopt a policy where the current owner of a given NFT had the exclusive rights to adapt the depicted character for commercial use. Since Green no longer owns the NFT that was used for the main character, he has now found himself in a legally dubious situation shortly before the show was scheduled to air.

### Links

https://www.buzzfeednews.com/article/sarahemerson/seth-green-bored-ape-stolen-tv-show

### Agreement

- [X] I irrevocably agree to release my contribution under the CC-BY 3.0 License

### Attribution name

Rez

**Comment by molly** [comment]
Thanks! Rather than adding a new entry I've updated the existing one.
