### ISSUE TITLE
[NEW]: CryptoBike showing sign of scam

### ISSUE THREAD

**Issue by SuperQAxClub** [molly/web3-is-going-great#37]
### Date

2022-01-13

### Description

The Vietnamese cryptocurrency investment community has lately been concerned by the news that CryptoBike – a Non-fungible token (NFT) game or Decentralized Finance (DeFi) game – is showing signs of defrauding investors with the amount reaching up to US$1.4 million.

### Links

https://www.sggpnews.org.vn/science_technology/cryptobike-showing-signs-of-scam-96791.html

https://diendandoanhnghiep.vn/du-an-game-nft-viet-dung-chieu-tro-chiem-doat-1-4-trieu-usdroi-bo-tron-215022.html

### Agreement

- [X] I irrevocably agree to release my contribution under the CC-BY 3.0 License

### Attribution name

@superquanganh

**Comment by molly** [comment]
Added, thank you! https://web3isgoinggreat.com/?id=2022-01-01-5
