### ISSUE TITLE
[EDIT] Cawthorn redlink

### ISSUE THREAD

**Issue by walker-ericsson** [molly/web3-is-going-great#375]
# Entry
[Representative Madison Cawthorn under ethics investigation related to crypto, violated STOCK Act](https://web3isgoinggreat.com/?id=representative-madison-cawthorn-under-ethics-investigation) (23 May 2022)

# Changes
[Link](https://ethics.house.gov/sites/emathics.house.gov/files/documents/Press%20Release_267.pdf) to statement of the chair and ranking member is dead. It appears the document is at [https://ethics.house.gov/sites/ethics.house.gov/files/documents/Press%20Release_267.pdf](https://ethics.house.gov/sites/ethics.house.gov/files/documents/Press%20Release_267.pdf) instead - URL differs in removing ma from emathics.

# Agreement
By submitting this issue, I irrevocably agree to release my contribution under the [CC-BY 3.0 License](http://creativecommons.org/licenses/by/3.0/deed.en_US). I agree that a hyperlink or URL is sufficient attribution under the Creative Commons license.

Please attribute this contribution to:
* Walker Ericsson

**Comment by molly** [comment]
Thank you!
