### ISSUE TITLE
[NEW]: Crypto ponzi @insta

### ISSUE THREAD

**Issue by yeahbutso** [molly/web3-is-going-great#377]
### Date

2021-11-09

### Description

Let's fully out an Instagram-based crypto scam, shall we? 

The Setup:

1. A trusted friend post screenshots of insane "returns" and invites DM's.
2. The pitch continues in private and the mark is introduced to a "mentor".
3. A series of relatively small debit transfers are initiated to phdfxtraders.com via bitcoin.com and CashApp using wallet addresses supplied by the mentor
4. A dashboard at phdfxtraders.com is loaded with deposit info and the alleged ROI value.
5. A withdrawal PIN request link is provided, and repeatedly proves worthless.
6. After complaints, chat sessions with "customer service" and "a manager" are initiated through sketchy looking email handles and WhatApp.
7. The directive is to initiate more bitcoin buys to reach the "required withdrawal minimum".  Your bedraggled protagonist repeats these steps for 11 grueling days.
8. When the morning after finally arrives, one should fully bail and hire a crypto scam recovery firm. Payback LTD has muscle. Yours truly learns that the origin and destination banks, the Visa M/C platform, and the bitcoin sellers are all criminally liable for dealing (however remotely) with an unlicensed forex trader.
9. Demand letters to all institutions, and a jaw-dropping 39 page crypto tracing report are generated to good effect.
10. Keep waiting. Keep fighting.

Where's the class action suit for me to join? I saved all receipts :)

Getting shady crypto investment advice at the mall? Do what I did not: mind the cognitive gap, kids.

### Links

![IMG-20211118-WA0007](https://user-images.githubusercontent.com/106542480/171020449-2e2a460a-8a76-47ee-ad2c-899722d2715d.jpg)

### Agreement

- [X] I irrevocably agree to release my contribution under the CC-BY 3.0 License

**Comment by spygency1** [comment]
NEED URGENT HELP?!!

NOTE:MESSAGE ONLY THIS ACCOUNT
#🇬🇧Expert Here To Assist In Any Cyber Issues General_Hacking_Recovery_Spy_Blackmail_Stolen,Lost BTC_Hacked Phones ☎️ 📥
🌎Facebook hacking - recovery
🌎Instagram hacking - recovery
🌎Snapchat hacking - recovery
🌎Lost money(investment scams) recovery
🌎Cheating partner spy (online)
🌎Crypto wallet hacking
🌎Phone hacks📱
🌎Message hacks & tweaks

For swift response send a message to my social media accounts, we are active 24/7 to solve all your Online ETHICAL HACKING issues 

INSTAGRAM 📥 spygency.1
EMAIL 📧 spygency@gmail.com

**Comment by spygency1** [comment]
NEED URGENT HELP?!!

NOTE:MESSAGE ONLY THIS ACCOUNT
#🇬🇧Expert Here To Assist In Any Cyber Issues General_Hacking_Recovery_Spy_Blackmail_Stolen,Lost BTC_Hacked Phones ☎️ 📥
🌎Facebook hacking - recovery
🌎Instagram hacking - recovery
🌎Snapchat hacking - recovery
🌎Lost money(investment scams) recovery
🌎Cheating partner spy (online)
🌎Crypto wallet hacking
🌎Phone hacks📱
🌎Message hacks & tweaks

For swift response send a message to my social media accounts, we are active 24/7 to solve all your Online ETHICAL HACKING issues 

INSTAGRAM 📥 spygency.1
EMAIL 📧 spygency@gmail.com

**Comment by spygency1** [comment]
NEED URGENT HELP?!!

NOTE:MESSAGE ONLY THIS ACCOUNT
#🇬🇧Expert Here To Assist In Any Cyber Issues General_Hacking_Recovery_Spy_Blackmail_Stolen,Lost BTC_Hacked Phones ☎️ 📥
🌎Facebook hacking - recovery
🌎Instagram hacking - recovery
🌎Snapchat hacking - recovery
🌎Lost money(investment scams) recovery
🌎Cheating partner spy (online)
🌎Crypto wallet hacking
🌎Phone hacks📱
🌎Message hacks & tweaks

For swift response send a message to my social media accounts, we are active 24/7 to solve all your Online ETHICAL HACKING issues 

INSTAGRAM 📥 spygency.1
EMAIL 📧 spygency@gmail.com
