### ISSUE TITLE
Feed not discoverable by Feedly

### ISSUE THREAD

**Issue by derat** [molly/web3-is-going-great#38]
Nice site! I noticed that [Feedly](https://feedly.com/) doesn't suggest the feed when `https://web3isgoinggreat.com/` is entered at https://feedly.com/i/discover. I suspect that the `type="application/xml"` attribute at https://github.com/molly/web3-is-going-great/blob/0500efc2f29111baf735b004c09ee00e08ec0472/public/index.html#L35 may need to instead be `type="application/atom+xml"`.

**Comment by molly** [comment]
@derat I've adjusted the type, does that fix discovery for you?

**Comment by derat** [comment]
Yep, that looks like it did the trick. The Atom feed is displayed now:

![Screenshot 2022-01-15 18 27 17](https://user-images.githubusercontent.com/40385/149639605-81491b73-1627-4c00-a3f9-740bf1e80ba7.png)

Thanks!

**Comment by molly** [comment]
Great, thank you so much for reporting and confirming the fix!
