### ISSUE TITLE
[NEW]: Timechain investigated by Quebec financial authorities

### ISSUE THREAD

**Issue by Circeus** [molly/web3-is-going-great#381]
### Date

2022-06-03

### Description

Timechain, a Montreal based DeFi project, and its leader Louis Cléroux, Jérémie Picard and Mathieu Cocher are under investigation by the Autorité des Marchés Financiers under charges of distribution without a prospectus and lying to AMF investigator. According to Timechain, investors lost about six million dollars because a stop-loss mechanism failed to engage when the Luna token collapsed which drained their Binance account, information contradicted by Binance. According to the latter, the Timechain account had been drained prior to the Terra collapse. AMF investigators believe funds were appropriate for by Cléroux for private and operational expenses, such as a 1.4 million dollars condo, which is now under a legal order preventing its sale.

### Links

https://www.lapresse.ca/affaires/2022-06-03/timechain-et-ses-dirigeants-font-l-objet-d-une-enquete.php
https://www.journaldemontreal.com/2022/06/03/depouilles-par-une-compagnie-quebecoise-de-cryptomonnaie

### Agreement

- [X] I irrevocably agree to release my contribution under the CC-BY 3.0 License

**Comment by molly** [comment]
Thanks! https://web3isgoinggreat.com/?id=timechain-allegedly-attempts-to-falsely-blame-missing-money-on-terra-collapse
