### ISSUE TITLE
[NEW]: Quebec's Autorité des Marchés Financiers reports at least 12 investors flawed for 6 million in Timechain DeFi platform scam

### ISSUE THREAD

**Issue by franc00018** [molly/web3-is-going-great#387]
### Date

2022-06-02

### Description

The founder of a Quebec-based cryptocurrency firm allegedly ripped off nearly $6 million from a dozen investors, which was used for his personal expenses, among other things.

Louis Cléroux, founder of the cryptocurrency firm Timechain, along with his partner Jérémie Picard and employee Mathieu Cocher, were hit this Monday with a slew of orders from the Autorité des Marchés Financiers, Quebec's financial regulatory agency

### Links

https://www.tvanouvelles.ca/2022/06/03/une-douzaine-dinvestisseurs-depouilles-par-une-compagnie-quebecoise-de-cryptomonnaie

https://lautorite.qc.ca/grand-public/salle-de-presse/actualites/fiche-dactualite/ordonnances-a-lencontre-de-technologies-timechain-inc-louis-cleroux-jeremie-picard-et-mathieu-cocher

### Agreement

- [X] I irrevocably agree to release my contribution under the CC-BY 3.0 License

### Attribution name

@franc00018

**Comment by molly** [comment]
Already listed at https://web3isgoinggreat.com/?id=timechain-allegedly-attempts-to-falsely-blame-missing-money-on-terra-collapse
