### ISSUE TITLE
[NEW]: Images are stretched on certain resolutions

### ISSUE THREAD

**Issue by Arrigi** [molly/web3-is-going-great#392]
### Date

2022-06-08

### Description

When I opened one of your links on an iphone 12 mini, the photo of Cawthorn was stretched wider than it should be. Can also replicate this in Safari using responsive design mode for an iphone 8. Similar in Firefox, simulating the iphone SE 2nd gen. Can also be seen in the instagram screenshot involving Cawthorn.

Doesn't seem to happen with any of the other images in any recent posts

Screenshot: Firefox simulation iphone SE 2nd gen on the left, regular desktop rendering on the right.
<img width="1293" alt="Screenshot 2022-06-08 at 21 18 09" src="https://user-images.githubusercontent.com/77449627/172698888-06f42898-b632-45a5-a179-da66d89227fe.png">

### Links

https://web3isgoinggreat.com/?id=representative-madison-cawthorn-belatedly-reports-up-to-950000-in-crypto-trades-long-past-the-stock-act-deadline

### Agreement

- [X] I irrevocably agree to release my contribution under the CC-BY 3.0 License

**Comment by molly** [comment]
Thank you! I've deployed a fix for this.

**Comment by Arrigi** [comment]
Thank you. That was incredibly quick.
