### ISSUE TITLE
[NEW]: Jack Dorsey's TBD is building a decentralized web on #Bitcoin called Web5

### ISSUE THREAD

**Issue by YousraMashkoor** [molly/web3-is-going-great#395]
### Date

2022-06-10

### Description

Former Twitter CEO Jack Dorsey has announced a new platform on Twitter called ‘Web5’, a combination of Web3  and Web 2.0, built on the Bitcoin blockchain. The platform promises to fix the issue of securing personal data. “We struggle to secure personal data with hundreds of accounts and passwords we can’t remember. On the web today, identity and personal data have become the property of third parties,” the company said on its website.

### Links

https://twitter.com/BitcoinMagazine/status/1535307469701926914
https://indianexpress.com/article/technology/crypto/former-twitter-ceo-jack-dorsey-announces-a-new-platform-web-5-7964556/

### Agreement

- [X] I irrevocably agree to release my contribution under the CC-BY 3.0 License

### Personal link

https://www.linkedin.com/in/yousra-mashkoor/

**Comment by YousraMashkoor** [comment]
Hey @molly wondering if this got added? If not would really love to get your feedback if there's a specific type of content you guys are looking for? :)

**Comment by molly** [comment]
Heya -- I've chosen not to add this quite yet just because there's so little _there_ there with this "Web5" thing. Once there's more clarity about what this project is actually trying to do I might add it.

**Comment by YousraMashkoor** [comment]
> Heya -- I've chosen not to add this quite yet just because there's so little _there_ there with this "Web5" thing. Once there's more clarity about what this project is actually trying to do I might add it.

Aight! Thanks @molly for the quick feedback :)
