### ISSUE TITLE
[NEW]: Ubisoft Devs Don’t Understand Company’s NFT Push

### ISSUE THREAD

**Issue by numbertheory** [molly/web3-is-going-great#4]
### Date

2021-12-14

### Description

Ubisoft's announcement of an NFT platform built into _Tom Clancy’s Ghost Recon Breakpoint_ caught a lot of Ubisoft developers off guard. Some were worried they would be forced to include NFTs in their own games, while others raised environmental concerns that come with the NFT technology stack.

### Links

https://kotaku.com/ubisoft-devs-don-t-understand-company-s-nft-push-eithe-1848215633

### Agreement

- [X] I irrevocably agree to release my contribution under the CC-BY 3.0 License

### Attribution name

JP Etcheber

### Personal link

https://twitter.com/jpscribbles

**Comment by molly** [comment]
I've incorporated your text into the existing entry about the Ubisoft NFTs. Thank you!
