### ISSUE TITLE
[NEW]: Coinbase Announces 18% Layoffs 

### ISSUE THREAD

**Issue by mayt** [molly/web3-is-going-great#405]
### Date

2022-06-13

### Description

Coinbase announces an 18% layoff effective immediately. The CEO cites overhiring in 2021 and the need to manage costs in the turbulent down market as the reason. 

### Links

https://blog.coinbase.com/a-message-from-coinbase-ceo-and-cofounder-brian-armstrong-578d76eedb12

### Agreement

- [X] I irrevocably agree to release my contribution under the CC-BY 3.0 License

### Personal link

https://twitter.com/productive_mayt

**Comment by molly** [comment]
Thank you! https://web3isgoinggreat.com/?id=coinbase-lays-off-1100-employees-in-18-cut
