### ISSUE TITLE
[NEW]: Coin Base warns user a bankruptcy could see them use users crypto to pay company debts. 

### ISSUE THREAD

**Issue by kdavidfong** [molly/web3-is-going-great#408]
### Date

2022-06-14

### Description

Coinbase said its users' crypto assets could become company property if it went bankrupt.

### Links

https://www.businessinsider.com/coinbase-warning-users-could-lose-crypto-bankruptcy-earnings-2022-5

### Agreement

- [X] I irrevocably agree to release my contribution under the CC-BY 3.0 License

**Comment by molly** [comment]
Already included: https://web3isgoinggreat.com/?id=coinbase-adds-new-language-regarding-bankruptcy-to-its-latest-quarterly-report
