### ISSUE TITLE
Sort by grift amount

### ISSUE THREAD

**Issue by molly** [molly/web3-is-going-great#412]

**Comment by hectorcoronado** [comment]
:wave: Molly! Guess who got laid off? *This* dude. Not sure if you'll recall, used to be active on Twitter but yeeted my account last year. Anyway, was poking around the site and this doesn't appear to be implemented, can take a stab at it if you like? Would need some guidance as to how you were envisioning it.

**Comment by molly** [comment]
Oh no Hector, I'm so sorry to hear that!

This is probably not a great feature to work on at the moment simply because I'm still halfway through rearchitecting how the $ amounts are stored, so anything you did would probably need to change immediately afterwards.

**Comment by hectorcoronado** [comment]
Gotcha gotcha -- appreciate you letting me know! Mebbe you could ping when the rearchitecture is completed if you wanna offload this bug to me? Tryna keep active with coding whilst in-between jobs :)

**Comment by molly** [comment]
Resolved with https://web3isgoinggreat.com/charts/top
