### ISSUE TITLE
[NEW]: Inverse Finance stung for $1.2 million via flash loan attack

### ISSUE THREAD

**Issue by RockyDog** [molly/web3-is-going-great#413]
### Date

2022/06/17

### Description

A decentralized autonomous organization (DAO) called Inverse Finance has been robbed of cryptocurrency somehow exchangeable for $1.2 million, just two months after being taken for $15.6 million.

### Links

https://www.theregister.com/2022/06/17/inverse_finance_heist/

### Agreement

- [X] I irrevocably agree to release my contribution under the CC-BY 3.0 License

### Attribution name

RockyDog

**Comment by molly** [comment]
Already recorded at https://web3isgoinggreat.com/?id=hacker-steals-over-1-2-million-from-inverse-finance
