### ISSUE TITLE
[EDIT] Change instance of "id='oracle-manipulation-attack'" to "id='oracle-manipulation'"

### ISSUE THREAD

**Issue by houhoulis** [molly/web3-is-going-great#426]
# Entry

https://web3isgoinggreat.com/?collection=oracle-manipulation&id=hacker-steals-over-1-2-million-from-inverse-finance

June 16, 2022

Hacker steals over $1.2M from Inverse Finance

# Changes

The tooltip link in the first sentence of the article opens a blank tooltip.

> A hacker was able to perform an <.button class="define-target" id="oracle-manipulation-attack" aria-haspopup="dialog" aria-expanded="true">oracle manipulation attack<./button> 

The tooltip works if I change `id="oracle-manipulation-attack"` to `id="oracle-manipulation"`.

# Agreement
By submitting this issue, I irrevocably agree to release my contribution under the [CC-BY 3.0 License](http://creativecommons.org/licenses/by/3.0/deed.en_US). I agree that a hyperlink or URL is sufficient attribution under the Creative Commons license.

Please attribute this contribution to:
* Chris Houhoulis
* https://github.com/houhoulis

**Comment by molly** [comment]
Thank you!
