### ISSUE TITLE
[NEW]: The "f" in "pegged to fiat currencies--*f*or example" in the tooltip explainer for peg is a funny, curly F rather than the ordinary F

### ISSUE THREAD

**Issue by harrisongowland** [molly/web3-is-going-great#428]
### Date

23/06/2022

### Description

The latter 'f' in "pegged to fiat currencies -- *f*or example" in the tooltip explainer for peg is an odd curly F rather than the ordinary F seen prior. This can be seen by clicking on the tooltip for peg on [for e.g. this story](https://web3isgoinggreat.com/?id=magic-internet-money-stablecoin-wobbles)

![funny f](https://user-images.githubusercontent.com/62898188/175359736-be6c81fb-87f1-4ba8-a110-28f7741c18bc.png)

### Links

https://web3isgoinggreat.com/?id=magic-internet-money-stablecoin-wobbles

### Agreement

- [X] I irrevocably agree to release my contribution under the CC-BY 3.0 License

### Attribution name

Harrison Gowland

**Comment by molly** [comment]
Thanks!
