### ISSUE TITLE
[NEW]: Animator Youtube account hacked, used to promote fake Elon Musk cryptocurrency livestream

### ISSUE THREAD

**Issue by ataylor-design** [molly/web3-is-going-great#429]
### Date

2022-25-6

### Description

The Youtube account of animator Joel Guerra, creator of the popular ENA and HANDS UP! series, was hacked the morning of June 25th. All of the videos were removed, the account was rebranded to Tesla Motors, and the account posted a fake livestream of Elon Musk discussing cryptocurrency. Joel was able to recover his account quickly, but noted that he never received a suspicious activity notification, even with 2FA enabled.

### Links

https://twitter.com/JoelGuerraC/status/1540707232068734977
https://www.youtube.com/c/JoelG

### Agreement

- [X] I irrevocably agree to release my contribution under the CC-BY 3.0 License

### Attribution name

Antonia Taylor

### Personal link

https://twitter.com/ataylor_design

**Comment by molly** [comment]
This unfortunately happens so often that I don't typically report each instance.
