### ISSUE TITLE
[EDIT] XCarnival Update

### ISSUE THREAD

**Issue by jtennant** [molly/web3-is-going-great#439]
# Entry
https://web3isgoinggreat.com/?id=hacker-makes-off-with-3-8-million-from-the-xcarnival-metaverse-bank

# Changes
Update: It appears there has been an agreement between XCarnival and the thief to treat this as a whitehat attack together with a bug bounty. Amazingly, the negotiation was conducted partially on-chain so it's visible for all to see. After proposing a $300k bug bounty, XCarnival finally settled for 1,500 ETH or a notional $1.8m.

Tweet by XCarnival - https://twitter.com/XCarnival_Lab/status/1541226298399653888
Tweet by Tal Be'ery - https://twitter.com/TalBeerySec/status/1541329941203226624

# Agreement
By submitting this issue, I irrevocably agree to release my contribution under the [CC-BY 3.0 License](http://creativecommons.org/licenses/by/3.0/deed.en_US). I agree that a hyperlink or URL is sufficient attribution under the Creative Commons license.

Please attribute this contribution to:
James Tennant (if you think it's worth an attribution - just pointing it out!)

**Comment by molly** [comment]
Thank you, I've updated! https://web3isgoinggreat.com/?id=hacker-makes-off-with-3-8-million-from-the-xcarnival-metaverse-bank
