### ISSUE TITLE
[EDIT] add “million” to “1.5”

### ISSUE THREAD

**Issue by barnabywalters** [molly/web3-is-going-great#44]
# Entry
[August 10, 2021](https://web3isgoinggreat.com/?id=2021-08-10-0)

# Changes
“around $1.5 in investments” should be “around $1.5 million in investments”

# Agreement
By submitting this issue, I irrevocably agree to release my contribution under the [CC-BY 3.0 License](http://creativecommons.org/licenses/by/3.0/deed.en_US). I agree that a hyperlink or URL is sufficient attribution under the Creative Commons license.

No attribution necessary for this tiny typo correction. Please don’t link to me.

**Comment by molly** [comment]
Oop, good catch, thanks!
