### ISSUE TITLE
Crypto Broker Voyager Issues Notice of Default to Three Arrows

### ISSUE THREAD

**Issue by RockyDog** [molly/web3-is-going-great#440]
### Date

2022/06/27

### Description

Crypto broker [Voyager Digital Ltd.](https://www.bloomberg.com/quote/VOYG:CN) said it has issued a notice of default to Three Arrows Capital, the troubled crypto hedge fund, on a loan worth roughly $675 million based on Bitcoin’s price on Monday.

### Links

https://www.bloomberg.com/news/articles/2022-06-27/crypto-broker-voyager-issues-notice-of-default-to-three-arrows?srnd=premium

### Agreement

- [X] I irrevocably agree to release my contribution under the CC-BY 3.0 License

### Attribution name

RockyDog

**Comment by molly** [comment]
Already covered in https://web3isgoinggreat.com/?id=voyager-digital-reduces-withdrawal-limit
