### ISSUE TITLE
Remember fire/fireworks animations settings

### ISSUE THREAD

**Issue by barnabywalters** [molly/web3-is-going-great#441]
The fireworks are fun but distracting, and while I appreciate the possibility to turn them off, they come back when I refresh the page. It’d be great if the fire/firework status could be retained e.g. in a cookie or localstorage.

**Comment by molly** [comment]
I've turned off the fireworks for now since they've been active for a while, so this shouldn't be a problem anymore. I'll leave the issue open, though, since I will presumably put the fireworks back on at some other milestone, and the preference should have been recorded in localstorage.

**Comment by molly** [comment]
Fixed in 5bd0b6958c52d2169b974e45ca8ed156ebf55271
