### ISSUE TITLE
One of the most prominent crypto hedge funds just defaulted on a $670 million loan

### ISSUE THREAD

**Issue by steepestdescent** [molly/web3-is-going-great#442]
### Date

6/27/2022

### Description

Prominent crypto hedge fund Three Arrows Capital has defaulted on a loan worth more than $670 million.
Digital asset brokerage Voyager Digital issued a notice on Monday morning, stating that the fund failed to repay a loan of $350 million in the U.S. dollar-pegged stablecoin, USDC, and another 15,250 bitcoin, worth about $323 million at today’s prices.

### Links

https://www.cnbc.com/2022/06/27/three-arrows-capital-crypto-hedge-fund-defaults-on-voyager-loan.html

### Agreement

- [X] I irrevocably agree to release my contribution under the CC-BY 3.0 License

### Attribution name

steepestdescent

### Personal link

https://github.com/steepestdescent

**Comment by molly** [comment]
Already covered in https://web3isgoinggreat.com/?id=voyager-digital-reduces-withdrawal-limit
