### ISSUE TITLE
[NEW]: Terra Labs had $3.6 billion in stablecoins potentially used for price manipulation, study shows

### ISSUE THREAD

**Issue by patrickhwood** [molly/web3-is-going-great#443]
### Date

2022-06-28

### Description

Terra Labs had $3.6 billion in stablecoins potentially used for price manipulation, study shows

### Links

https://finbold.com/terra-labs-had-3-6-billion-in-stablecoins-potentially-used-for-price-manipulation-study-shows/

### Agreement

- [X] I irrevocably agree to release my contribution under the CC-BY 3.0 License

### Attribution name

Patrick Wood

**Comment by molly** [comment]
Haven't been able to find any higher-quality sources to verify such a major claim.
