### ISSUE TITLE
[NEW]: OpenSea email vendor employee misuse

### ISSUE THREAD

**Issue by erizock** [molly/web3-is-going-great#445]
### Date

6/29/22

### Description

An employee of OpenSea's email vendor, Customer.io, misused their access to Customer.io’s systems to download and share email addresses with an unauthorized third party. Impacted email addresses include those provided by OpenSea users and subscribers to our newsletter.  

### Links

https://cointelegraph.com/news/opensea-data-breach-causes-massive-leak-of-users-email-addresses
https://opensea.io/blog/safety-security/important-update-on-email-vendor-security-incident/
https://nftplazas.com/trouble-at-opensea-as-email-vendor-employee-goes-rogue/

### Agreement

- [X] I irrevocably agree to release my contribution under the CC-BY 3.0 License

### Attribution name

@erizock

**Comment by molly** [comment]
I haven't been including incidents like this because they're pretty standard "web2" problems rather than any flaw with web3.
