### ISSUE TITLE
[NEW]: FTX walked away from a deal with Celsius after seeing state of its finances: sources

### ISSUE THREAD

**Issue by patrickhwood** [molly/web3-is-going-great#447]
### Date

2022-06-30

### Description

FTX was interested in making a deal with Celsius but walked away because of the state of its finances, two sources told The Block.
Celsius had a $2 billion hole in its balance sheet, one source said.

### Links

https://www.theblock.co/post/155069/ftx-walked-away-from-celsius-deal

### Agreement

- [X] I irrevocably agree to release my contribution under the CC-BY 3.0 License

### Attribution name

Patrick Wood

**Comment by molly** [comment]
Waiting on this one to see if more sources verify. So far everything is only sourced to anonymous sources to The Block.
