### ISSUE TITLE
[NEW]: FTX closes in on a deal to buy embattled crypto lender BlockFi for $25 million in a fire sale, source says

### ISSUE THREAD

**Issue by patrickhwood** [molly/web3-is-going-great#448]
### Date

2022-06-30

### Description

The term sheet is almost over the finish line and expected to be signed by the end of the week, according to three sources, who asked not to be named because the deal discussions were confidential. FTX is expected to pay roughly $25 million, one source said, 99% below BlockFi's last private valuation. Jersey City, New Jersey-based BlockFi was last valued at $4.8 billion, according to PitchBook. 

### Links

https://www.cnbc.com/amp/2022/06/30/ftx-closes-in-on-a-deal-to-buy-embattled-crypto-lender-blockfi-for-25-million-in-a-fire-sale.html

### Agreement

- [X] I irrevocably agree to release my contribution under the CC-BY 3.0 License

### Attribution name

Patrick Wood

**Comment by molly** [comment]
Thank you! https://web3isgoinggreat.com/?id=ftx-reportedly-approaches-a-deal-to-buy-blockfi
