### ISSUE TITLE
[NEW]: Indie Developer selling commissioned pixel art as NFTs without permission from original artists

### ISSUE THREAD

**Issue by notphyre** [molly/web3-is-going-great#45]
### Date

2021-03-09

### Description

Jason Rohrer, developer of indie game "The Castle Doctrine" announced his plan to auction 155 of the digital paintings that he commissioned for the game as NFTs on the OpenSea platform, without ever requesting permission from the original artists or informing them of his plan at all. In an email, Rohrer told Kotaku that he did not ask permission to sell people’s works as NFTs “mostly because having email conversations with 50+ people would exceed my bandwidth as a solo creator.”

### Links

https://kotaku.com/game-artists-not-happy-that-developer-is-selling-their-1846465316
https://twitter.com/jasonrohrer/status/1369331652787400704
http://thecastledoctrine.net/crypto.php

### Agreement

- [X] I irrevocably agree to release my contribution under the CC-BY 3.0 License

**Comment by molly** [comment]
Thank you! https://web3isgoinggreat.com?id=2021-03-09-2
