### ISSUE TITLE
Grift counter

### ISSUE THREAD

**Issue by Naleksuh** [molly/web3-is-going-great#452]
Did the default Grift counter setting get changed? Personally, I think counting up was better as it shows while you go past it rather than going down as if the reports are helping. Also, I was confused at first as I thought one of the posts at front was 10.6 billion.

Any particular reason why it was changed? Could consider changing it back please?

**Comment by divmgl** [comment]
? Not sure this is a good use of the issue tracker.

**Comment by Naleksuh** [comment]
It is a perfectly fine use. I was suggesting a feature request.

**Comment by molly** [comment]
Yes, I swapped the direction recently. I might change it back if I can find a good design to also show the current total (without someone having to change their grift counter settings or scroll through all posts). Until then, the page should remember your preference if you change it.

**Comment by Naleksuh** [comment]
@molly I'm still getting annoyed by the grift counter (the preference change also keeps being undone, might be using too short a cookie or something?)

Would it work to just have it in the intro?
![image](https://user-images.githubusercontent.com/24828999/178094858-b15dc597-cd81-4942-8704-4c9eeedd23d7.png)

(Using the correct font of course, I couldn't find which one you used)

**Comment by Naleksuh** [comment]
Some other ideas I also had were a max count ($0/$10100000000) and a new line, but this one works best IMO, as the total is a seperate thing per Mollys post.

**Comment by jose8109** [comment]
ustedes entienden , que me hackearon el celular y no estoy entendiendo que es lo que quieren? por dios me pueden explicar

**Comment by jose8109** [comment]
no entiendo la funcionalidad de este sistema, ya que me cambiaron muchas cosas

**Comment by jose8109** [comment]
necesito confiar en alguien para que vuelva a su lugar todo normal, y así dar buenas noticias a quienes consideremos y pedir disculpas si así lo requieren nunca insulte a nadie, ni hackee el teléfono a nadie,  por favor necesito alguien con experiencia y renombre y de mediador en esta situación tan preocupante para todos , lo merecemos
