### ISSUE TITLE
[NEW]: RSS feed dies a few days ago

### ISSUE THREAD

**Issue by paulehoffman** [molly/web3-is-going-great#456]
### Date

2022-07-01

### Description

https://web3isgoinggreat.com/feed.xml hasn't updated in about two days, and I miss it.

### Links

https://web3isgoinggreat.com/feed.xml

### Agreement

- [X] I irrevocably agree to release my contribution under the CC-BY 3.0 License

### Attribution name

@paulehoffman

**Comment by molly** [comment]
Thank you! Closed in 0dc5d0900920bef813f00ab47692a1173f1d07df
