### ISSUE TITLE
[EDIT] 'Crema Finance hacked for $8.8 million' missing grift counter value

### ISSUE THREAD

**Issue by BiggerJ** [molly/web3-is-going-great#457]
# Entry
Crema Finance hacked for $8.8 million

# Changes
This post does not affect the grift counter, despite the fact that it mentions the theft of cryptocurrency with $8.8 million in notional value. (Other posts measuring thefts in notional value, such as 'Hacker makes off with $3.8 million from the XCarnival "metaverse bank", returns half' and '$100 million stolen from Horizon Bridge', do affect the grift counter.)

# Agreement
By submitting this issue, I irrevocably agree to release my contribution under the [CC-BY 3.0 License](http://creativecommons.org/licenses/by/3.0/deed.en_US). I agree that a hyperlink or URL is sufficient attribution under the Creative Commons license.

Please attribute this contribution to:
* 
*

**Comment by molly** [comment]
Good catch, thank you!
