### ISSUE TITLE
[NEW]: The Verge: No bids on Chevy's first NFT, even though it came with a free Corvette Z06.

### ISSUE THREAD

**Issue by patrickhwood** [molly/web3-is-going-great#469]
### Date

2022-07-04

### Description

Chevy’s First Foray into NFT Auctions Was a Bust With Zero Bids for the Minted Green Corvette Z06

### Links

https://www.theverge.com/2022/7/4/23194242/chevy-corvette-nft-auction-no-bids
https://www.corvetteblogger.com/2022/06/29/chevys-first-foray-into-nft-auctions-was-a-bust-with-zero-bids-for-the-minted-green-corvette-z06/

### Agreement

- [X] I irrevocably agree to release my contribution under the CC-BY 3.0 License

### Attribution name

Patrick Wood

**Comment by molly** [comment]
Already listed at https://web3isgoinggreat.com/?id=even-a-free-sports-car-couldnt-get-anyone-to-bid-on-chevrolets-first-nft
