### ISSUE TITLE
[NEW]: A Spanish crypto-bank activates HODL mode

### ISSUE THREAD

**Issue by rinze** [molly/web3-is-going-great#471]
### Date

2022-07-07

### Description

From the linked article (automatic translation):

> The 2gether platform has addressed its clients to inform them that it is closing the private account service and that on July 10 it will charge them 20 euros as a mandatory management fee "for the maintenance and management of crypto accounts." After this, it has disabled its website and mobile application, preventing its users from doing any management. A message shows that they are “under maintenance”. It has also closed all his social media accounts.

> [...] 2gether was one of the first crypto banks created in Spain and its sudden closure "leaves more than 100,000 affected on the way", the Association of Financial Users (Asufin) has denounced. The organization is one of them, since it invested 100 euros in September 2021 in the five cryptocurrency trading platforms that have the most users in Spain "to test what happens to a real consumer who wants to try this investment."

### Links

https://www-eldiario-es.translate.goog/tecnologia/corralito-criptobanco-espanol-atrapa-fondos-100-000-afectados_1_9151703.html?_x_tr_sl=auto&_x_tr_tl=en&_x_tr_hl=en-US&_x_tr_pto=wapp

### Agreement

- [X] I irrevocably agree to release my contribution under the CC-BY 3.0 License

**Comment by molly** [comment]
Thank you! https://web3isgoinggreat.com/?id=crypto-platform-2gether-closes-user-access-to-accounts
