### ISSUE TITLE
Suggestion: Add Tim Berners-Lee's actual vision for Web 3.0 in the webpage

### ISSUE THREAD

**Issue by AlphaXVIV** [molly/web3-is-going-great#48]
TimBL's vision for Web 3.0 is far from what the decenbros are pushing. I thought it'll be nice if visitors get to know what the actual vision of it is, and to avoid more confusion between the decentralized focus of "web3" and an iteration of the Web that actually improves the web more than decentralization can ever do.

Wikipedia article (not the best source but it'll do)
https://en.wikipedia.org/wiki/Semantic_Web

**Comment by molly** [comment]
This project is meant to describe the blockchain-related version of web3, which is totally distinct from TBL's semantic web ideas. I don't think it's a particularly useful thing to dive into here (similarly to how I don't go into how a DAO is both a decentralized autonomous organization and a data access object—same word, totally different meaning).
