### ISSUE TITLE
[NEW]: RFIA bill on GitHub is archived and issues section removed

### ISSUE THREAD

**Issue by ressy** [molly/web3-is-going-great#485]
### Date

2022-07-13

### Description

Not sure this fits as a new issue, an update, or something else entirely, but...

Some time earlier today, the [RFIA legislation GitHub repo](https://github.com/responsible-financial-innovation-act22/RFIA-bill) that was [covered as a topic last month](https://web3isgoinggreat.com/?id=senators-lummis-and-gillibrand-solicit-feedback-on-their-proposed-crypto-legislation-via-github-and-its-off-to-a-predictably-chaotic-start) was archived, with its issues section removed entirely, so we can't even see what everyone previously had to say.  A shame, because there were some real gems in there.  As it just so happens, this morning I called their bluff and posted my own feedback as an issue there.  It's... uh... long.  I had this strange inkling it might not stay available (though I thought it would last longer than a few hours!) so I made sure it [made it into the wayback machine](http://web.archive.org/web/20220713125935/https://github.com/responsible-financial-innovation-act22/RFIA-bill/issues/165) as soon as I'd posted it.  Thankfully most of the others look like they made it there too (I put a couple examples below) though not all.  So much for wanting our feedback.

Anyway, I figured this would at least deserve an update on the original timeline entry, if not a brand-new event.  Thank you @molly for your tireless efforts on all this.

### Links

https://github.com/responsible-financial-innovation-act22/RFIA-bill
http://web.archive.org/web/20220713125935/https://github.com/responsible-financial-innovation-act22/RFIA-bill/issues/165
http://web.archive.org/web/20220624171336/https://github.com/responsible-financial-innovation-act22/RFIA-bill/issues/89
http://web.archive.org/web/20220624171232/https://github.com/responsible-financial-innovation-act22/RFIA-bill/issues/60

### Agreement

- [X] I irrevocably agree to release my contribution under the CC-BY 3.0 License

**Comment by molly** [comment]
I've made an update to the entry, thank you!
