### ISSUE TITLE
[Feat Request]: Expose the grift total in the RSS header or via a simple json API

### ISSUE THREAD

**Issue by kuzmik** [molly/web3-is-going-great#486]
### Date

2022-07-11

### Description

I was thinking about adding a simple applet to the Tidbyt (https://tidbyt.com) that shows the total amount of grift, since everyone else keeps adding "show this crypo value" applets.

I looked at the source for W3IGG and I just don't understand typescript enough to add this myself :(

### Links

https://tidbyt.com

### Agreement

- [X] I irrevocably agree to release my contribution under the CC-BY 3.0 License

**Comment by molly** [comment]
Here you go! https://us-central1-web3-334501.cloudfunctions.net/getGriftCounterTotal

Please be polite as far as caching/rate-limiting.

**Comment by kuzmik** [comment]
Amazing, thank you! I've already added some caching, so it won't hit the endpoint more than once every 15 minutes.

https://github.com/tidbyt/community/pull/526/files#diff-44ac8e8830a74e844c8459601cd094c6c4ea6d4524419a113b0f1d2827a1d6fb
