### ISSUE TITLE
[NEW]: Move from google-analytics to matomo

### ISSUE THREAD

**Issue by Shnoulle** [molly/web3-is-going-great#49]
Currently there are google-analytics script 

1. Some user disable GA but enable matomo script (me for one example)
2. Google is a know big tracker company
3. Matomo is free like a speech
4. Maybe you can contact matomo team to have a discount : «We are proud to support non-profit organisations and charities around the world that seek to better their communities, provide social good, preserve culture or the environment, provide relief to the poor, or promote human rights. Eligible non-profit organisations may receive a discount. Get in touch to learn more» on https://matomo.org/pricing/
5. Else: you can setup a matomo on your hosting (need php/mariadb)

**Comment by molly** [comment]
It's totally fine with me if people want to disable or block GA! But I'm not going to switch to a $20/mo analytics tool, or totally switch databases for that purpose.
