### ISSUE TITLE
[NEW]: Possible expansion of the term "rug-pull"

### ISSUE THREAD

**Issue by paulehoffman** [molly/web3-is-going-great#496]
### Date

2022-07-19

### Description

An exchange going out of business is not likely left with zero deposits, even after lawsuits. The owners of a bankrupt exchange can likely remove remaining capital for a variety of things that would or would not pass the sniff test for legitimacy. This feels pretty much like a rug-pull in the NFT space. Maybe start calling exchange closings rug-pulls, or potential rug-pulls.

### Links

<none>

### Agreement

- [X] I irrevocably agree to release my contribution under the CC-BY 3.0 License

### Attribution name

@paulehoffman

**Comment by molly** [comment]
I'm mostly going with the widely-used definitions for these terms, so even though you may be correct I'm going to stick with the standard definition.

**Comment by paulehoffman** [comment]
Fair enough; thanks for considering. (And thanks for keeping the site going!)
