### ISSUE TITLE
[EDIT] Small typo fix

### ISSUE THREAD

**Issue by TheoKanning** [molly/web3-is-going-great#497]
# Entry

$7,500–$300,000 NFT-holders-only club set to open in SF, holders still have to pay for their food
July 19th, 2022

# Changes

Small typo 🤷, first sentence is missing the word "as".
Salesforce Park, a suspended park area underneath the Salesforce Tower, has been described **as** intentionally unwelcoming to...

# Agreement

By submitting this issue, I irrevocably agree to release my contribution under the [CC-BY 3.0 License](http://creativecommons.org/licenses/by/3.0/deed.en_US). I agree that a hyperlink or URL is sufficient attribution under the Creative Commons license.

**Comment by molly** [comment]
Thank you!
