### ISSUE TITLE
[NEW]: 9-11 Falling Man replaced with an astronaut NFT for sale on Gamestop's "curated" market

### ISSUE THREAD

**Issue by hydrometer** [molly/web3-is-going-great#499]
### Date

2022-07-22

### Description

Yes someone made an NFT of the 9-11 Falling Man replaced with an astronaut and is selling it on GameStop. I really think it is in bad taste to be selling this image and maybe you will too. With the recent troubles, the new marketplace is "Going Great."

### Links

https://nft.gamestop.com/token/0x6b9eaa12c14c5bd1a70a857c405a343503fbe77d/0x7490b137909ad61988afbec2a706e46bad74b2b93f61b791e6ba36a4c8aa1fa2

### Agreement

- [X] I irrevocably agree to release my contribution under the CC-BY 3.0 License

### Attribution name

anonymous

**Comment by molly** [comment]
https://web3isgoinggreat.com/?id=gamestops-new-nft-platform-features-an-nft-mimicking-a-victim-of-911
