### ISSUE TITLE
README link includes incorrect domain

### ISSUE THREAD

**Issue by ndowmon** [molly/web3-is-going-great#5]
Great project!

Just noticed the README has a link that's broken. I would've opened a PR but it'd be a bogus reason for me to show up under `Contributors`. 

```diff
- # [web3 is going just great](https://web3isgoingjustgreat.com)
+ # [web3 is going just great](https://web3isgoinggreat.com)
```

Cheers!

**Comment by molly** [comment]
Resolved in 9fcee989e12b070299de0ef22c1b2da3be36dbf5, thanks Nick! 👋
