### ISSUE TITLE
Web 3 Streaming Platform Audius Hacked, $6M Stolen: 

### ISSUE THREAD

**Issue by BNFTYNick** [molly/web3-is-going-great#512]
### Date

2022-07-24

### Description

A malicious actor siphoned $6 million from music platform Audius through the platform’s decentralized governance system. The hacker created a malicious proposal requesting the transfer of 18 million AUDIO tokens from the community treasury, an action supposedly approved by the Audius community.

### Links

https://beincrypto.com/web-3-streaming-platform-audius-hacked-6m-stolen/

### Agreement

- [X] I irrevocably agree to release my contribution under the CC-BY 3.0 License

### Attribution name

nickjames

### Personal link

@crypt0l0gical

**Comment by molly** [comment]
Already covered in https://web3isgoinggreat.com/?id=attacker-makes-off-with-1-1-million-after-successful-governance-attack-on-the-audius-web3-music-platform
