### ISSUE TITLE
[NEW]: Kraken Is Suspected of Violating Sanctions

### ISSUE THREAD

**Issue by patrickhwood** [molly/web3-is-going-great#513]
### Date

2022-07-26

### Description

The Treasury Department is investigating whether the crypto exchange allowed users in Iran to buy and sell digital tokens

### Links

https://www.nytimes.com/2022/07/26/technology/kraken-crypto-iran.html

### Agreement

- [X] I irrevocably agree to release my contribution under the CC-BY 3.0 License

### Attribution name

Patrick Wood

**Comment by molly** [comment]
https://web3isgoinggreat.com/?id=ofac-has-been-investigating-kraken-over-suspected-sanctions-violations
