### ISSUE TITLE
[NEW]: Man accidentally throws away £150m in bitcoin

### ISSUE THREAD

**Issue by glyn** [molly/web3-is-going-great#524]
### Date

2022-08-02

### Description

Man who accidentally threw away £150m in bitcoin ‘secures funding’ for plan to dig up landfill.

We just heard this reported on the BBC Radio 4's Today programme.

### Links

https://www.bbc.co.uk/news/uk-wales-55658942

### Agreement

- [X] I irrevocably agree to release my contribution under the CC-BY 3.0 License

**Comment by molly** [comment]
The actual incident way predates the time span I focus on with this blog.
