### ISSUE TITLE
[NEW]: Australian crypto platform Immutable sacks 6%-17% of staff despite plans to ‘hire aggressively’

### ISSUE THREAD

**Issue by AdamMooreGameDev** [molly/web3-is-going-great#526]
### Date

2021-08-03

### Description

Immutable, the crypto gaming company that developed Gods Unchained, laid off 6%-17% of their staff. The company could be hit with legal action as the union questioned the validity of the redundancies. The workers were given various inconsistent reasons for the layoff. The union Games Workers Australia has disputed the number of staff members that were laid off. Concerns have been aired that Immutable is still hiring for similar roles that were made redundant such as product managers and engineers.

### Links

https://www.news.com.au/finance/business/technology/australian-crypto-platform-immutable-sacks-17-of-staff-despite-plans-to-hire-aggressively/news-story/efb79889c00b92ef92324ddd94e22666

### Agreement

- [X] I irrevocably agree to release my contribution under the CC-BY 3.0 License

### Personal link

https://twitter.com/morningstar2651

**Comment by molly** [comment]
https://web3isgoinggreat.com/?id=crypto-platform-immutable-lays-off-17-of-its-gaming-division-staff
