### ISSUE TITLE
[EDIT] The collage of stolen furry art is worse than it sounds

### ISSUE THREAD

**Issue by pdwood** [molly/web3-is-going-great#53]
# Entry
[Someone mints a NFT of 100 stolen furry profile pictures](https://web3isgoinggreat.com?id=2021-11-13-0)

# Changes
The entry claims that the creator of the token promised $5k to anyone who owned an image used in the collage. However, the linked article specifies that the compensation was only available to people who _minted tokens of the artwork and sent them to the creator_—and that all but one of the people who tried this were not even "remotely close to being able to show that their pfp in question was in fact theirs."

# Agreement
By submitting this issue, I irrevocably agree to commit this contribution to the public domain under the terms of [Creative Commons Zero](https://creativecommons.org/share-your-work/public-domain/cc0).

**Comment by molly** [comment]
Ugh, gross. Thank you, updated!
