### ISSUE TITLE
[NEW]: Binance denies owning WazirX, India’s largest crypto exchange 2 years after announcing the acquisition 

### ISSUE THREAD

**Issue by captn3m0** [molly/web3-is-going-great#537]
### Date

2022-08-05

### Description

Binance CEO Changpeng Zhao said the firm did "not own any equity in Zanmai Labs, the entity operating WazirX". He added that "Binance only provides wallet services for WazirX as a tech solution," while WazirX was responsible for KYC and other operations on the exchange. 

This comes 2 year after Binance announced they’d acquired WazirX in a blog post titled “ Binance Acquires India’s Leading Digital Asset Platform WazirX”.  The blog post was edited after the tweets to clarify that “no equity was purchased in the transaction” and that the deal was limited to “certain assets and intellectual property”

The clarification follows India’s Enforcement Directorate freezing WazirX’s assets worth over $8 million, citing suspected violation of foreign exchange rule.

Nischal Shetty, co-founder of WazirX, has disputed Zhao’s claims, asserting Binance indeed acquired WazirX. He confirmed that Binance owned the WazirX domain name and controlled root access to their AWS account.

### Links

https://techcrunch.com/2022/08/06/binance-says-it-doesnt-own-indian-exchange-wazirx-years-after-acquisition-announcement/

https://www.cnbctv18.com/cryptocurrency/wazirx-binance-engage-in-war-of-tweets-investors-crypto-14409062.htm

https://www.binance.com/en/blog/all/binance-acquires-indias-leading-digital-asset-platform-wazirx-to-launch-multiple-fiattocrypto-gateways-404105749895733248

https://cointelegraph.com/news/indian-authorities-freeze-8-1m-in-wazirx-funds-as-part-of-aml-investigation

### Agreement

- [X] I irrevocably agree to release my contribution under the CC-BY 3.0 License

### Attribution name

Nemo

### Personal link

https://twitter.com/captn3m0

**Comment by captn3m0** [comment]
Wrote this on the phone, will put inline links in a bit.

**Comment by molly** [comment]
Thanks! https://web3isgoinggreat.com/?id=no-one-wants-to-admit-to-owning-the-wazirx-crypto-exchange
