### ISSUE TITLE
[NEW]: Celsius CEO Cashed in After Bankrupt Crypto Lender's Token Surged

### ISSUE THREAD

**Issue by patrickhwood** [molly/web3-is-going-great#538]
### Date

2022-08-10

### Description

While a group of traders has been busy pumping the bankrupt crypto lender Celsius Network’s founder cashed out some of his CEL token holdings, which have multiplied in value even as his company struggles

### Links

https://finance.yahoo.com/news/dormant-wallet-linked-alex-mashinsky-193345899.html

### Agreement

- [X] I irrevocably agree to release my contribution under the CC-BY 3.0 License

### Attribution name

Patrick Wood

**Comment by molly** [comment]
https://web3isgoinggreat.com/?id=celsius-ceo-alex-mashinsky-reportedly-sells-off-some-of-his-cel
