### ISSUE TITLE
[NEW]: “It’s Potentially Illegal”: As Crypto Crashed, Coinbase Stopped Some Notifications

### ISSUE THREAD

**Issue by barrynolette** [molly/web3-is-going-great#539]
### Date

2022-08-10

### Description

Coinbase accused of turning off price alert notification emails right as the value of Bitcoin, Ethereum and other cryptocurrencies began to crash sometime around April 2022. This action could have potentially run afoul of Unfair and Deceptive Practice laws.

### Links

https://www.motherjones.com/politics/2022/08/its-potentially-illegal-as-crypto-crashed-coinbase-stopped-some-notifications/

### Agreement

- [X] I irrevocably agree to release my contribution under the CC-BY 3.0 License

**Comment by molly** [comment]
Thanks! https://web3isgoinggreat.com/?id=coinbase-stopped-sending-price-notifications-during-crypto-crash
