### ISSUE TITLE
[NEW]: French surgeon attempts to sell Bataclan victim's X-ray as NFT

### ISSUE THREAD

**Issue by Thibaut120094** [molly/web3-is-going-great#54]
### Date

2022-01-22

### Description

* A senior French surgeon faces legal action and a possible disciplinary charge after attempting to sell an X-ray of a concertgoer who was shot during the 2015 attack on the Bataclan music hall in Paris.
* Orthopaedic surgeon Emmanuel Masmejean, who practises at the Georges Pompidou public hospital in south-west Paris, was first reported by the Mediapart website on Saturday (Jan 22) to be selling an image of the X-ray as a digital artwork, without the patient's consent.
* The picture shows a forearm containing a Kalashnikov bullet and was on sale for US$2,776 on the OpenSea website, which specialises in so-called NFT digital images.
* Asked for comment by Mediapart, Dr Masmejean acknowledged that the sale was "an error" and said he regretted not having sought permission from the patient.
* The patient is not identified, but is described as a young woman whose boyfriend was killed in the Bataclan attack, which was part of a wave of shootings and bomb attacks in the French capital by Islamic State in Iraq and Syria gunmen who claimed 130 lives.

_all items are quotes pulled from the English article_

### Links

[English article (_The Straits Times_)](https://www.straitstimes.com/world/europe/french-surgeon-attempts-to-sell-bataclan-victims-x-ray-as-nft)
[Original French article (_Mediapart_)](https://www.mediapart.fr/journal/france/220122/un-chirurgien-de-l-ap-hp-cherche-vendre-aux-encheres-la-radio-d-une-blessee-du-13-novembre) 

### Agreement

- [X] I irrevocably agree to release my contribution under the CC-BY 3.0 License

**Comment by molly** [comment]
Thank you! https://web3isgoinggreat.com/?id=2022-01-22-2
