### ISSUE TITLE
RSS feed not updated since 2022-08-10

### ISSUE THREAD

**Issue by acfoltzer** [molly/web3-is-going-great#543]
The most recent entry in the RSS feed appears to be `Blur Finance rug pulls for over $600,000`.

Thank you for your work on this project, and in particular for maintaining an RSS feed of it!

**Comment by paulehoffman** [comment]
I'm seeing the same thing here.

**Comment by paulehoffman** [comment]
...and now fixed. Thanks for the quick response!

**Comment by molly** [comment]
Thanks for the heads up! Something must be up with my alerting on that again :(
