### ISSUE TITLE
[NEW]: The official German McDonald's Twitter account steals pixel art, tries to pass it off as NFT art in a reply to Twitter

### ISSUE THREAD

**Issue by DPS2004** [molly/web3-is-going-great#55]
### Date

2022-1-21

### Description

On Jan 20, @twitter posted "gm, looking for an nft pfp", shortly after rolling out hexagonal NFT profile pictures.

The next day, @McDonaldsDENews replied "Say no more!", and included pixel art of the Twitter bird holding a McDonald's bag in its beak.

After further investigation, though, the art was found to be heavily traced from a tweet by @SarahBurssty, which ironically was created to criticize Twitter's support of NFTs. 

### Links

https://twitter.com/SarahBurssty/status/1484769576449576963
https://web.archive.org/web/20220123003021/https://twitter.com/McDonaldsDENews/status/1484459919885705216

### Agreement

- [X] I irrevocably agree to release my contribution under the CC-BY 3.0 License

### Attribution name

DPS2004

### Personal link

https://twitter.com/DPS2004_

**Comment by molly** [comment]
Thank you! https://web3isgoinggreat.com?id=2022-01-20-3
