### ISSUE TITLE
[EDIT] Small typo in august 17th entry about the CDPQ

### ISSUE THREAD

**Issue by bchhun** [molly/web3-is-going-great#555]
# Entry

**Title:** August 17th CDPQ Entry
**Typo:** Canadian _peaisse_ de dépôt

# Changes

**fix:** Canadian _caisse_ de dépôt

# Agreement

By submitting this issue, I irrevocably agree to release my contribution under the [CC-BY 3.0 License](http://creativecommons.org/licenses/by/3.0/deed.en_US). I agree that a hyperlink or URL is sufficient attribution under the Creative Commons license.

Please attribute this contribution to:

N/A

You can leave this blank if this is a change so small as to not be copyrightable.

**Comment by molly** [comment]
oop, thanks!
