### ISSUE TITLE
[NEW]: Another BitMEX employee convicted of violating Federal anti-money laundering laws

### ISSUE THREAD

**Issue by Brett-Bowman** [molly/web3-is-going-great#556]
### Date

Aug 8, 2022

### Description

U.S. Attorney Damian Williams said:  “With this plea, this Office has now obtained criminal convictions against all three founders, as well as a high-ranking employee at BitMEX, for willful violations of anti-money laundering laws. 

### Links

https://www.justice.gov/usao-sdny/pr/high-ranking-employee-cryptocurrency-exchange-pleads-guilty-bank-secrecy-act-violations?mkt_tok=NDE3LUxYRi01NjUAAAGGUMPj3R24ZUfXcdMtLfZlGp8ziocFPgKvdAV5le1jxa1nRB5xKd7sh4l_i9t9AySwtYFD-PFsodys0qemjsS2vkKs820lJu0DOkBloH1pg-GU

### Agreement

- [X] I irrevocably agree to release my contribution under the CC-BY 3.0 License

**Comment by molly** [comment]
Already included at https://web3isgoinggreat.com/?id=bitmex-crypto-exchange-founders-plea
