### ISSUE TITLE
RSS Feed Missing

### ISSUE THREAD

**Issue by ndegruchy** [molly/web3-is-going-great#56]
The [RSS feed][1] returns a 404 error.

[1]: https://web3isgoinggreat.com/feed.xml

**Comment by molly** [comment]
🤔  does it? It's loading for me...

**Comment by ndegruchy** [comment]
Huh, seems to be working now. Miniflux reports that it checked yesterday with a failure. I admit that I hadn't checked *today*.

Thanks!

**Comment by molly** [comment]
Ah yeah, I migrated the site over to next.js yesterday and it took me a bit to get the RSS feed back up. That's probably what it was!
