### ISSUE TITLE
[NEW]: Woman to pay back Crypto.com $10.5 million

### ISSUE THREAD

**Issue by d33pfri3d** [molly/web3-is-going-great#579]
### Date

2022-08-30

### Description

A judge has ruled that a Melbourne woman must pay back $10.5 million to crypto trading platform [Crypto.com](https://crypto.com) after they had mistakenly transferred her the amount in May of 2021, but took 7 months to realise.

### Links

https://tickernews.co/crypto-com-accidentally-transfers-10-5m-to-woman-instead-of-100/

### Agreement

- [X] I irrevocably agree to release my contribution under the CC-BY 3.0 License

**Comment by molly** [comment]
Already included at https://web3isgoinggreat.com/?id=cryptocom-wants-back-the-7-2-million-they-accidentally-sent-a-customer-last-year
