### ISSUE TITLE
[NEW]: All your apes belong to us... due to poor Web2 practices

### ISSUE THREAD

**Issue by KonradIT** [molly/web3-is-going-great#58]
### Date

2022-01-24

### Description

Attacker used OpenSea's API to buy an NFT for an older, much lower price that the current listing price (turns out OpenSea allows for sellers to edit listing prices) then flipped it.

https://therecord.media/hacker-abuses-opensea-to-buy-nfts-at-older-cheaper-prices/

### Links

https://therecord.media/hacker-abuses-opensea-to-buy-nfts-at-older-cheaper-prices/

### Agreement

- [X] I irrevocably agree to release my contribution under the CC-BY 3.0 License

**Comment by molly** [comment]
Thank you! https://web3isgoinggreat.com?id=2022-01-24-1
