### ISSUE TITLE
[NEW]: OptiFi Dev Enters Wrong Command, Closes program on Solana Blockchain

### ISSUE THREAD

**Issue by BitWire** [molly/web3-is-going-great#580]
### Date

2022-08-29

### Description

OptiFi Devs wanted to update their Solana program code, and in the process closed their program on the Solana blockchain permanently, with no way of recovering the funds (roughly 661K USDC). They will refund all users in a timespan of two weeks in Solscan, according to their blogpost.

### Links

https://medium.com/@OptiFi/optifi-program-incident-report-08-29-22-d8fe6d229bad

### Agreement

- [X] I irrevocably agree to release my contribution under the CC-BY 3.0 License

### Attribution name

@BitWire

### Personal link

https://twitter.com/SchmidtsTom

**Comment by molly** [comment]
Already covered in https://web3isgoinggreat.com/?id=optifi-developer-accidentally-closes-the-project-contract-irretrievably-locking-661000
