### ISSUE TITLE
RSS feed URL seems broken

### ISSUE THREAD

**Issue by cvonelm** [molly/web3-is-going-great#581]
The feed URL times out on me in both my browser and my tiny-tiny-rss instance. Maybe I'm doing something real stupid or there might be some problems with the feed currently.

Thank you for your work.

**Comment by molly** [comment]
It's not you, it's me! 😄 Fixed

**Comment by paulehoffman** [comment]
It's been down again for a few days.

**Comment by paulehoffman** [comment]
Fixed now. Thanks!
