### ISSUE TITLE
[NEW]: RSS Broken

### ISSUE THREAD

**Issue by MatthewBrown0** [molly/web3-is-going-great#59]
### Date

2022-01-24

### Description

Today I received a message from my RSS feed that it could no longer connect.  When I look at the RSS page it is not up to date with the latest entries.  I use RSS to pull your updates into a Microsoft Teams channel so that many people in my Org have access.

### Links

https://web3isgoinggreat.com/feed.xml

### Agreement

- [X] I irrevocably agree to release my contribution under the CC-BY 3.0 License

### Attribution name

Matt

**Comment by molly** [comment]
Broke the RSS feed right after I told someone it was working 😅  Should be better now!

**Comment by MatthewBrown0** [comment]
Thanks - I notice that the feed.xml page is now up to date but Teams is still giving me an issue.
![feed](https://user-images.githubusercontent.com/81646186/151014974-3538c07d-5cb9-40e0-995e-bb7e88b5c38c.png)
