### ISSUE TITLE
[NEW]: Shinu Iba AWS token leak

### ISSUE THREAD

**Issue by bcb44** [molly/web3-is-going-great#593]
### Date

2022-9-8

### Description

Shinu Iba leaks credentials to GitHub in commit. No bug bounty or responsible disclosure policy in place so researcher has to post online to draw teams attention. 

### Links

https://blog.pingsafe.com/shiba-inu-cloud-credentials-leaked-in-a-major-security-breach-394ad54382c1
https://www.cyberkendra.com/2022/09/shiba-inu-leaked-their-aws-cloud.html

### Agreement

- [X] I irrevocably agree to release my contribution under the CC-BY 3.0 License

**Comment by molly** [comment]
Thanks! https://web3isgoinggreat.com/?id=shiba-inu-developers-leak-aws-credentials-on-github
