### ISSUE TITLE
typo in recent entry

### ISSUE THREAD

**Issue by trick-knee** [molly/web3-is-going-great#594]
# Entry

[Shiba Inu developers leak AWS credentials on Github](https://web3isgoinggreat.com/?id=shiba-inu-developers-leak-aws-credentials-on-github)

# Changes

> apparently published their AWS creditials to Github.

should be 'credentials'.

# Agreement

By submitting this issue, I irrevocably agree to release my contribution under the [CC-BY 3.0 License](http://creativecommons.org/licenses/by/3.0/deed.en_US). I agree that a hyperlink or URL is sufficient attribution under the Creative Commons license.

Please attribute this contribution to:

- Ken Rodriguez

You can leave this blank if this is a change so small as to not be copyrightable.

**Comment by molly** [comment]
Thank you!
