### ISSUE TITLE
[NEW]: STALKER 2 Is Getting a Metaverse of Blockchain/NFTs

### ISSUE THREAD

**Issue by KnucklesEQ** [molly/web3-is-going-great#6]
### Date

2021-12-15

### Description

GSC Game World announced that STALKER 2, its highly anticipated open world first person shooter game made with Unreal Engine 5, will use blockchain/NFT technology to create the so-called STALKER Metaverse. Established in partnership with DMarket, a platform for trading NFTs and technology for metaverse creation, the STALKER Metaverse will allow players to own the rights to certain unique items in STALKER 2

### Links

https://wccftech.com/stalker-2-is-getting-a-metaverse-of-blockchain-nfts-and-weve-asked-the-developers-why/

### Agreement

- [X] I irrevocably agree to release my contribution under the CC-BY 3.0 License

**Comment by molly** [comment]
Added, thank you!
