### ISSUE TITLE
Grift counter does not appear when directly navigating to a post that is not the most recent

### ISSUE THREAD

**Issue by donquxiote** [molly/web3-is-going-great#607]
Noticed this when clicking a link from twitter. If I navigate to https://web3isgoinggreat.com/?id=double-your-money-scammers-capitalize-on-ethereum-merge, the grift counter does not appear. Also tried this with other older posts to confirm it wasn't that specific post. 

If I navigate to the most recent post (at this time https://web3isgoinggreat.com/?id=binance-accounting-bug-involving-helium-tokens-results-in-19-million-of-erroneous-payouts), then the grift counter will appear.

In the case where it does not appear, I can click on the "start from the top" or remove the params from the URL and it will appear.

**Comment by molly** [comment]
This is works-as-designed: https://web3isgoinggreat.com/faq#grift-counter
