### ISSUE TITLE
[NEW]: MMfinance , exposing insider trading and fraud

### ISSUE THREAD

**Issue by neoragex7** [molly/web3-is-going-great#618]
### Date

09/19/2022

### Description

I like your content and am a regular viewer. I am a youtuber and I cover crypto and modern finance etc.

I came across your recent article where mmfinance was mentioned: https://web3isgoinggreat.com/?id=whale-illustrates-price-manipulation-risk-in-gmx-exchange

I've been covering mmfinance since inception and have discovered lots of unethical and shady behavior. Its really big and I thought you would find it useful since your website covers bad crypto. 

I've created an entire thread on twitter linking to every possible fraud and shady actions conducted by mmfinance, dev team and insiders. I'm linking them below. If you need anything else, please let me know. Lots of people are getting scammed, just check on their official twitter page and the comments by investors.

They sucked cronos ecosystem dry and recently moved over to polygon doing the same, the damage is massive.

I would love to see some big entity , platform cover the story and expose the fraud; probably get a 3rd person perspective.

Thanks

~RBL

### Links

https://twitter.com/unapologeticBOT/status/1565943340503285761
https://twitter.com/unapologeticBOT/status/1567039920035749888
https://twitter.com/unapologeticBOT/status/1567040008665661440

### Agreement

- [X] I irrevocably agree to release my contribution under the CC-BY 3.0 License

### Attribution name

@unapologeticRBL

### Personal link

https://twitter.com/unapologeticBOT

**Comment by molly** [comment]
Thanks for the additional info!
