### ISSUE TITLE
[NEW]: Sports fan cryptocurrency Iqoniq enters liquidation

### ISSUE THREAD

**Issue by howiieb** [molly/web3-is-going-great#62]
### Date

2022-26-01

### Description

"Fan engagement blockchain platform" IQONIQ, which promised token holders “access to a wide range of exciting opportunities which bring them one step close than anyone else to their idols and organisations in sports and entertainment” went into liquidation late January 2022, taking down the token sale platform and crashing the value of the fan-owned coin by over 90%. The platform had major sponsorship deals with multiple Formula 1 teams, European soccer clubs and the Spanish La Liga league, which it owes €820,000.

### Links

https://www.thetimes.co.uk/article/fans-face-big-cryptocurrency-losses-after-platform-goes-into-liquidation-czxpcwd60

### Agreement

- [X] I irrevocably agree to release my contribution under the CC-BY 3.0 License

### Attribution name

Howie

### Personal link

https://twitter.com/howiieb

**Comment by molly** [comment]
Thank you! https://web3isgoinggreat.com?id=2022-01-26-2
