### ISSUE TITLE
[NEW]: Luxury cars seized from 23-year-old 'Crypto King' as investors try to recoup millions

### ISSUE THREAD

**Issue by westcoastace** [molly/web3-is-going-great#620]
### Date

2022-09-20

### Description

Luxury cars seized from 23-year-old 'Crypto King' as investors try to recoup millions

### Links

https://www.cbc.ca/news/canada/toronto/luxury-cars-seized-crypto-king-investors-try-recoup-millions-1.6583982

### Agreement

- [X] I irrevocably agree to release my contribution under the CC-BY 3.0 License

### Attribution name

Harry Bekkema

**Comment by molly** [comment]
Thanks! https://web3isgoinggreat.com/?id=investors-seek-to-recoup-around-35-million-from-canadian-crypto-king-in-his-20s
