### ISSUE TITLE
Web 1.0 previous button breaks in the future

### ISSUE THREAD

**Issue by Naleksuh** [molly/web3-is-going-great#63]
If JS is available, it will show this:

![image](https://user-images.githubusercontent.com/24828999/151407395-04ce47b4-f65c-43d6-8cf9-dcf65ec5d377.png)

Otherwise, it will show this:

![image](https://user-images.githubusercontent.com/24828999/151407230-72a20f89-e505-410a-b9a2-38cf206b0c6b.png)

Steps to reproduce

Step 1 : Go to https://web3isgoinggreat.com/web1

Step 2 : Click next

Step 3 : Click previous

Step 4 : Click previous again

Because there is no previous content to load as it takes you to a nonexistent page, it breaks. The previous link is usually hidden, but shows when coming back from a next link

**Comment by molly** [comment]
Fixed in 661ba2026bf7866da9ce2ce8a29e243e3170d75d !

Thanks for all your bugfinding!
