### ISSUE TITLE
[NEW]: Millionaire burns a $10M Frida Kahlo artwork to sell as NFT

### ISSUE THREAD

**Issue by albertjan** [molly/web3-is-going-great#632]
### Date

2022-09-223

### Description

Precious artwork destroyed by millionaire to inflate price of his NFT’s.  

### Links

https://culturacolectiva.com/art/frida-kahlo-artwork-burned-nft

### Agreement

- [X] I irrevocably agree to release my contribution under the CC-BY 3.0 License

**Comment by molly** [comment]
Thanks! https://web3isgoinggreat.com/?id=someone-claims-to-have-burned-a-frida-kahlo-drawing

**Comment by albertjan** [comment]
Thank you!
