### ISSUE TITLE
[NEW]: Celsius Execs Cashed out at Least $17 Million in Crypto Before Halting Withdrawals for Customers

### ISSUE THREAD

**Issue by patrickhwood** [molly/web3-is-going-great#639]
### Date

2022-10-06

### Description

Pretty much self explanatory. 

### Links

https://www.coindesk.com/business/2022/10/06/celsius-top-execs-cashed-out-17m-in-crypto-before-bankruptcy/

### Agreement

- [X] I irrevocably agree to release my contribution under the CC-BY 3.0 License

### Attribution name

Patrick Wood

**Comment by molly** [comment]
Included in https://web3isgoinggreat.com/?id=celsius-exposes-the-names-of-all-customers-and-their-recent-transactions-in-court-filing--including-their-execs
