### ISSUE TITLE
[NEW]: CNN accused of rug-pull after abandoning NTFS project

### ISSUE THREAD

**Issue by ajsirota** [molly/web3-is-going-great#652]
### Date

2022-10-10

### Description

CNN abandoned their "Vault by CNN" project, a marketplace selling collectible "Moment" NFTs tied to major news events, such as [Ruth Bader Ginsburg's swearing-in](https://vault.cnn.com/drops/8741). 

### Links

https://www.theverge.com/2022/10/10/23397766/vault-by-cnn-nft-shutdown-flow-rebate-rugpull
https://nitter.it/vaultbycnn/status/1579562628493774851

### Agreement

- [X] I irrevocably agree to release my contribution under the CC-BY 3.0 License

### Attribution name

no attribution please

**Comment by molly** [comment]
Thank you!
