### ISSUE TITLE
[NEW]: CRYPTO DEV ENTERS WRONG COMMAND, DESTROYS ENTIRE COMPANY

### ISSUE THREAD

**Issue by ananay** [molly/web3-is-going-great#653]
### Date

2022-10-13

### Description

A coding error accidentally — and permanently — shut the entire Solana blockchain-based platform down, wiping out $661,000 worth of a stablecoin called USDC.

### Links

https://futurism.com/the-byte/crypto-dev-command-company

### Agreement

- [X] I irrevocably agree to release my contribution under the CC-BY 3.0 License

### Attribution name

Ananay Arora

### Personal link

https://twitter.com/ananayarora

**Comment by molly** [comment]
https://web3isgoinggreat.com/?id=optifi-developer-accidentally-closes-the-project-contract-irretrievably-locking-661000
