### ISSUE TITLE
[NEW]: The Verge: Warner Bros.' Lord of the Rings NFT “experience” is just The Fellowship in 4K.

### ISSUE THREAD

**Issue by patrickhwood** [molly/web3-is-going-great#662]
### Date

2022-10-21

### Description

I've seen some stupid NFTs out there, but this one really ranks high on the stupid meter.

### Links

https://www.theverge.com/2022/10/20/23413237/lord-of-the-rings-movie-nft-wb-movieverse-metaverse

### Agreement

- [X] I irrevocably agree to release my contribution under the CC-BY 3.0 License

### Attribution name

Patrick Wood

**Comment by molly** [comment]
https://web3isgoinggreat.com/?id=warner-bros-reinvents-dvd-navigation-menus-with-their-web3-movieverse
