### ISSUE TITLE
[NEW]: AscendEx exchange loses $77M in hack

### ISSUE THREAD

**Issue by philipkd** [molly/web3-is-going-great#69]
### Date

2021-12-16

### Description

AscendEx exchange loses $77M in hack, promises full compensation.

A Singaporean digital currency exchange is the latest victim to a security breach, losing over $77 million in a hack. The criminals accessed the exchange’s hot wallets and drained them of Ethereum, Polygon, BCH, and several other smaller ERC-20 tokens. AscendEx traced most of the stolen funds to have landed on Bitfinex and Binance while pledging to compensate all the victims fully.

### Links

https://coingeek.com/ascendex-exchange-loses-77m-in-hack-promises-full-compensation/

### Agreement

- [X] I irrevocably agree to release my contribution under the CC-BY 3.0 License

**Comment by molly** [comment]
Already in there, just a few days prior: https://web3isgoinggreat.com?id=2021-12-11-1

I really need to get going on #34
