### ISSUE TITLE
[NEW]: Telegram launches an NFT username marketplace, consisting of usernames it took from public channels

### ISSUE THREAD

**Issue by UmbyUmbreon** [molly/web3-is-going-great#695]
### Date

2022-11-05

### Description

Telegram has announced that it launched [Fragment](https://fragment.com), a marketplace for buying, selling, privately trading and auctioning what it calls ["Collectible Usernames"](https://telegram.org/blog/topics-in-groups-collectible-usernames#collectible-usernames). (And yes: just like [Reddit's "Collectible Avatars"](https://web3isgoinggreat.com/?id=reddit-launches-more-nft-avatars-but-wont-call-them-nfts), they're NFTs.) However, instead of creating new usernames to populate the marketplace, or allowing users to create their own collectible usernames, Telegram has taken to "repossessing" usernames already assigned to public channels, and either reselling them, or slating them for resale later in the year. This includes open-source projects unrelated to crypto, such as the [Lawnchair Android homescreen](https://twitter.com/lawnchairapp/status/1585983625627049984), and prominent trademarks, including [FIFA](https://fragment.com/username/fifa), [Facebook](https://fragment.com/username/facebook), and [Amazon](https://fragment.com/username/amazon).

According to Durov, Telegram's Product Manager, CEO and Founder, usernames were revoked from ["all public Telegram addresses linked to channels that were empty or inactive in the past year"](https://t.me/durov/195), with 99% of these being gradually reintroduced "for public use". The other 1% would be put up for auction on Fragment.

### Links

https://fragment.com/
https://telegram.org/blog/topics-in-groups-collectible-usernames
https://twitter.com/lawnchairapp/status/1585983625627049984
https://t.me/durov/195

### Agreement

- [X] I irrevocably agree to release my contribution under the CC-BY 3.0 License

### Attribution name

@UmbyUmbreon

**Comment by JeDaYoshi** [comment]
Usernames were revoked since August 19th (<https://t.me/tginfoen/1471>), and Pavel Durov explained its reasoning on August 29th (<https://t.me/durov/195>). Curiously, this explanation comes a week after he mentioned wanting to "add a little bit of Web 3.0 in the coming weeks", on August 22th (<https://t.me/durov/194>).

Fragment is up since October 10th (<https://t.me/durov/198>), auctioning usernames which were taken from channels/groups/etc. without any prior warning.

I'm not sure the `2022-11-05` date is right in that case.

**Comment by UmbyUmbreon** [comment]
The `11-05` date was the date of the initial announcement of collectible usernames on the Telegram blog, and is probably the most publicised announcement of such (I certainly missed the previous announcements because I don't follow Durov's channel). Having said that, if there's a better date to attribute to this, then by all means it can be changed

**Comment by YaBoiBurner** [comment]
Little bonus thing worth adding - I don't think there's any functioning word filter in place. They might have something for full usernames, but so far, every slur or offensive thing I've searched has had plenty of results available.

**Comment by Techwolf** [comment]
Went to https://fragment.com/ , got " Oops

This service is not available in the United States. "

I wonder why?

**Comment by JeDaYoshi** [comment]
As of today, Telegram has announced on their official channel the Fragment platform: <https://t.me/telegram/201>

Additionally to that, it is sending adverts for it to every individual through the "Telegram" service notification account: <https://t.me/tginfoen/1530> (I also got it myself, so I can confirm this)

**Comment by Techwolf** [comment]
Still getting the same message

**Comment by molly** [comment]
Thank you! And sorry for the huge delay in adding this one!

https://web3isgoinggreat.com/?id=telegram-repossesses-usernames-so-they-can-sell-them-as-nfts
https://twitter.com/web3isgreat/status/1596617847781957642
