### ISSUE TITLE
[NEW]: Ethereum smart contract interaction represent less than 11% of the transactions since its launch

### ISSUE THREAD

**Issue by rllola** [molly/web3-is-going-great#706]
### Date

2022-11-15

### Description

"When looking if the gas used in Ethereum transactions is following the benford law we noticed that it doesnt. It seems that a simple transfer in Ethereum cost 21000 gas. 89% of the transactions on the network might be simple send transaction."

When analyzing the Ethereum transactions since 2015 to 2020, an engineer find out that most of the transactions are not interacting with a smart contract but are a simple fund transfer.

### Links

https://twitter.com/lola29270965/status/1472159506549387265?s=20&t=NsTViUCs7zO1P9yCd8784w
https://github.com/rllola/bendford-ethereum/

### Agreement

- [X] I irrevocably agree to release my contribution under the CC-BY 3.0 License

### Attribution name

Lola

**Comment by rllola** [comment]
Hi! I see the issue has been closed but I don't find it on the site. Has it been published ?

**Comment by molly** [comment]
Sorry, I closed it with the wrong tag! I closed it because it's out of scope for the site.

**Comment by rllola** [comment]
A bit disappointed but ok. I saw you published the article about Decentraland having 38 daily users. It is just a more general statement that people don't interact with smart contracts (and therefore web3).
