### ISSUE TITLE
Visualization of FTX's balance sheet

### ISSUE THREAD

**Issue by paulehoffman** [molly/web3-is-going-great#707]
# Entry

FTX's balance sheet

# Changes

A nice visualization from Visual Capitalist : https://www.visualcapitalist.com/ftx-leaked-balance-sheet-visualized/

# Agreement

By submitting this issue, I irrevocably agree to release my contribution under the [CC-BY 3.0 License](http://creativecommons.org/licenses/by/3.0/deed.en_US). I agree that a hyperlink or URL is sufficient attribution under the Creative Commons license.

Please attribute this contribution to:

Visual Capitalist, of course

**Comment by molly** [comment]
Very cool! Not well suited to a W3IGG entry, though.
