### ISSUE TITLE
[NEW]: Australian Stock Exchange (ASX) Kills Their Blockchain Project

### ISSUE THREAD

**Issue by LochlanS** [molly/web3-is-going-great#709]
### Date

2022-11-17

### Description

The ASX tried to replace their ageing CHESS system with a blockchain replacement. After 5 delays and hundreds of millions of dollars spent they have killed the project and have completely financial written it off as a loss.

### Links

News Article:
https://www.afr.com/companies/financial-services/asx-kills-its-blockchain-project-will-write-off-250-million-20221117-p5byzn

Market Announcement from ASX:
https://cdn-api.markitdigital.com/apiman-gateway/ASX/asx-research/1.0/file/2924-02599209-2A1414213?access_token=83ff96335c2d45a094df02a206a39ff4

### Agreement

- [X] I irrevocably agree to release my contribution under the CC-BY 3.0 License

### Attribution name

No attribution please

### Personal link

NA

**Comment by molly** [comment]
https://web3isgoinggreat.com/?id=australian-securities-exchange-scraps-its-250-million-seven-year-long-blockchain-project
