### ISSUE TITLE
[NEW]: CEO in Charge of FTX Restructuring Calls Case an ‘Unprecedented’ Mess

### ISSUE THREAD

**Issue by patrickhwood** [molly/web3-is-going-great#712]
### Date

2022-11-17

### Description

The man who had to clean up the mess at Enron says the situation at FTX is even worse, describing what he calls a “complete failure” of corporate control.

### Links

https://www.cnn.com/2022/11/17/business/ftx-ceo-complete-failure/index.html
New Chief Calls FTX’s Corporate Control a ‘Complete Failure’ https://nyti.ms/3UO6F0C

### Agreement

- [X] I irrevocably agree to release my contribution under the CC-BY 3.0 License

### Attribution name

Patrick Wood

**Comment by molly** [comment]
Mentioned in my newsletter, but not something I'll add to the timeline.
