### ISSUE TITLE
[NEW]: Iris Energy Limited have received default and acceleration notices

### ISSUE THREAD

**Issue by lawless-m** [molly/web3-is-going-great#714]
### Date

2022-11-22

### Description

Bitcoin mining company Iris Energy Limited have received default and acceleration notices, including a demand that each Facility be immediately repaid in full. Company decides to stop powering most rigs as collateral for $107.8 million debt. 

### Links

https://twitter.com/wublockchain/status/1594874877496160257

https://www.sec.gov/Archives/edgar/data/1878848/000114036122042419/ny20005141x6_6k.htm

### Agreement

- [X] I irrevocably agree to release my contribution under the CC-BY 3.0 License

### Attribution name

Lesslaw

**Comment by molly** [comment]
https://web3isgoinggreat.com/?id=iris-energy-defaults-on-100-million-loan-unplugs-miners
