### ISSUE TITLE
[EDIT] to resolve pronoun ambiguity in "Genesis warns..."

### ISSUE THREAD

**Issue by catsmoke** [molly/web3-is-going-great#716]
# Entry

November 21, 2022
"Genesis warns of bankruptcy if they can't raise $1 billion"

# Changes

> _Genesis Global Trading has reportedly been telling investors that **they** may need to file for bankruptcy if **their** attempts to raise at least $1 billion in new capital don't succeed._

ought to read

> _Genesis Global Trading has reportedly been telling investors that **Genesis** may need to file for bankruptcy if **its** attempts to raise at least $1 billion in new capital don't succeed._

The original form leads the reader to the idea that the investors may need to file for bankruptcy (which may be true, but that doesn't seem to be the idea that the sentence is intended to convey).

I'd also change the headline from

> _Genesis warns of bankruptcy if **they** can't raise $1 billion_

to

> _Genesis warns of bankruptcy if **it** can't raise $1 billion_

In general, it's okay to use the plural pronoun for the singular noun antecedent, but in this context it is confusing.

# Agreement

By submitting this issue, I irrevocably agree to release my contribution under the [CC-BY 3.0 License](http://creativecommons.org/licenses/by/3.0/deed.en_US). I agree that a hyperlink or URL is sufficient attribution under the Creative Commons license.
Please attribute this contribution to:

Jesse Berry

You can leave this blank if this is a change so small as to not be copyrightable.

**Comment by molly** [comment]
Ah, good spot! Thanks, fixed.
