### ISSUE TITLE
Generate tweets for @web3isgreat automatically

### ISSUE THREAD

**Issue by molly** [molly/web3-is-going-great#72]
Right now when I add a new post I have to manually screenshot the entry, copy over the title/date/link, and copy the post contents into alt-text. Would be pretty cool to be able to do this automatically (though should still be kicked off by me, since not all posts go in the Twitter feed, and sometimes I need to make edits after a post is added to fix typos etc.).

**Comment by 0pling** [comment]
I made [this](https://github.com/0pling/w3igg_tweet).

**Comment by molly** [comment]
Closed with https://github.com/molly/w3igg-crossposter
