### ISSUE TITLE
[NEW]: Refugees as guinea pigs for cryptocurrency, blockchain and Web3 

### ISSUE THREAD

**Issue by Nlea** [molly/web3-is-going-great#733]
### Date

November 2022

### Description

This report was published in November 2022 by Dr Margie Cheesman. It describes how web 3 start-ups and companies test their solution with marginalized groups. Those groups already have to take on the consequences and risks when it comes to poor designed web3/ blockchain applications.

### Links

https://www.mctd.ac.uk/wp-content/uploads/2022/11/MCTD-Web3-Report-WEB.pdf

### Agreement

- [X] I irrevocably agree to release my contribution under the CC-BY 3.0 License

### Attribution name

Nele Lea (@nlea)

### Personal link

Mastodon: @nlea@social.anoxinon.de Twitter: @nele_lea

**Comment by molly** [comment]
Thanks! I've read and shared this article, but don't think it's necessarily in scope for the site.
