### ISSUE TITLE
[NEW]: 

### ISSUE THREAD

**Issue by jonmenaster** [molly/web3-is-going-great#734]
### Date

2022-11-29

### Description

A.P. Moller - Maersk and IBM to discontinue TradeLens, a blockchain-enabled global trade platform. TradeLens was founded on the bold vision to make a leap in global supply chain digitization as an open and neutral industry platform. Unfortunately, while we successfully developed a viable platform, the need for full global industry collaboration has not been achieved. As a result, TradeLens has not reached the level of commercial viability necessary to continue work and meet the financial expectations as an independent business.

### Links

https://www.maersk.com/news/articles/2022/11/29/maersk-and-ibm-to-discontinue-tradelens

### Agreement

- [X] I irrevocably agree to release my contribution under the CC-BY 3.0 License

### Attribution name

Jon

**Comment by molly** [comment]
https://web3isgoinggreat.com/?id=maersk-and-ibm-announce-the-discontinuation-of-their-blockchain-based-tradelens-platform
