### ISSUE TITLE
[EDIT]

### ISSUE THREAD

**Issue by teeshaw** [molly/web3-is-going-great#735]
# Entry

Nov 30 2022, Kraken pays over $360,000 to settle violations of sanctions against Iran

# Changes

Link to treasury.gov notice is broken.

# Agreement

By submitting this issue, I irrevocably agree to release my contribution under the [CC-BY 3.0 License](http://creativecommons.org/licenses/by/3.0/deed.en_US). I agree that a hyperlink or URL is sufficient attribution under the Creative Commons license.

Please attribute this contribution to:

- 
- 

You can leave this blank if this is a change so small as to not be copyrightable.

**Comment by molly** [comment]
Thanks!
