### ISSUE TITLE
[NEW]: SBF Admits to fraud in interview

### ISSUE THREAD

**Issue by Lind0rm** [molly/web3-is-going-great#747]
### Date

2022-11-8

### Description

In a published interview, youtube creator and crypto investigative journalist CoffeeZilla gets Sam Bankman Fried to directly admit to fraud by co-mingling funds on FTX; displacing any legal doubt that may be left on the issue.

### Links

https://m.youtube.com/watch?v=4o_jPzBZSIo

### Agreement

- [X] I irrevocably agree to release my contribution under the CC-BY 3.0 License

### Attribution name

Lind

**Comment by molly** [comment]
Thanks -- I'm going to omit this for now just to reduce the enormous
