### ISSUE TITLE
[NEW]: 

### ISSUE THREAD

**Issue by servalan999** [molly/web3-is-going-great#749]
### Date

9/12/2022

### Description

Cryptocurrency broker Digital Surge goes into administration, as the FTX fallout continues

### Links

https://www.abc.net.au/news/2022-12-09/digital-surge-administration-ftx-cryptocurrency-savings-super/101753514

### Agreement

- [X] I irrevocably agree to release my contribution under the CC-BY 3.0 License

**Comment by molly** [comment]
Thanks! https://web3isgoinggreat.com/?id=digital-surge-enters-administration
