### ISSUE TITLE
[NEW]: ASX faces more RBA, ASIC scrutiny after collapse of blockchain project

### ISSUE THREAD

**Issue by servalan999** [molly/web3-is-going-great#760]
### Date

15/12/2022

### Description

Another blockchain project comes unstuck - this time at the Australian Stock Exchange operator. 

### Links

https://www.smh.com.au/business/companies/asx-faces-more-rba-asic-scrutiny-after-collapse-of-blockchain-project-20221215-p5c6je.html

### Agreement

- [X] I irrevocably agree to release my contribution under the CC-BY 3.0 License

**Comment by molly** [comment]
https://web3isgoinggreat.com/?id=australian-securities-exchange-scraps-its-250-million-seven-year-long-blockchain-project
