### ISSUE TITLE
[EDIT] The World Wildlife Fund ...

### ISSUE THREAD

**Issue by philipkd** [molly/web3-is-going-great#78]
# Entry

https://web3isgoinggreat.com?id=2022-01-31-5

# Changes

I'm a blockchain developer, and I'm pretty sure Polygon is eco-friendly. I don't see any evidence for it being otherwise.

Both Polygon and the media tout Polygon as an L2-scaling solution for Ethereum. However, Polygon, the blockchain (sometimes referred to as MATIC to reduce/enhance confusion), is not an L2 scaling solution for Ethereum. MATIC is simply its own, Ethereum-derived chain, which just so happens to have some L2-like improvements. Polygon, the organization, also markets L2 technologies on the side. I believe this confusion is intentional.

MATIC uses PoS which uses [orders of magnitude](https://blog.polygon.technology/polygon-the-eco-friendly-blockchain-scaling-ethereum-bbdd52201ad/) [less power](https://niftykit.com/polygon-eco-friendly-implications-compared-to-ethereum-and-bitcoin-usage/) than PoW-based Ethereum.

# Agreement
By submitting this issue, I irrevocably agree to release my contribution under the [CC-BY 3.0 License](http://creativecommons.org/licenses/by/3.0/deed.en_US). I agree that a hyperlink or URL is sufficient attribution under the Creative Commons license.

Please attribute this contribution to:
* not needed, right?

**Comment by molly** [comment]
hrm, that is very confusing. I've tweaked the entry.
