### ISSUE TITLE
[EDIT] "Millions of dollars of user funds stolen in BitKeep wallet hack" misspelled PeckShieldAlert in link text

### ISSUE THREAD

**Issue by bcb44** [molly/web3-is-going-great#785]
# Entry

https://web3isgoinggreat.com/single/millions-of-dollars-of-user-funds-stolen-in-bitkeep-wallet-hack

# Changes

In the link to the PeckShieldAlert, the d is missing so it's spelled PeckShielAlert. Small change for typo needed

# Agreement

By submitting this issue, I irrevocably agree to release my contribution under the [CC-BY 3.0 License](http://creativecommons.org/licenses/by/3.0/deed.en_US). I agree that a hyperlink or URL is sufficient attribution under the Creative Commons license.

**Comment by molly** [comment]
Thank you!
