### ISSUE TITLE
[EDIT] “my” should be “by”

### ISSUE THREAD

**Issue by barnabywalters** [molly/web3-is-going-great#789]
# Entry

https://web3isgoinggreat.com/?id=wallets-linked-to-sam-bankman-frieds-alameda-research-unexpectedly-begin-selling-off-1-7-million-in-tokens

# Changes

“founded my Sam” -> “founded by Sam”

# Agreement

By submitting this issue, I irrevocably agree to release my contribution under the [CC-BY 3.0 License](http://creativecommons.org/licenses/by/3.0/deed.en_US). I agree that a hyperlink or URL is sufficient attribution under the Creative Commons license.

Please attribute this contribution to:

no attribution necessary.

You can leave this blank if this is a change so small as to not be copyrightable.

**Comment by barnabywalters** [comment]
The highlighted link to “cryptocurrency mixers” in the same post is also broken.

**Comment by molly** [comment]
Thank you!
