### ISSUE TITLE
[NEW]: site that collates all the economic damage from hacks and scams in one place (24B and counting)

### ISSUE THREAD

**Issue by manach** [molly/web3-is-going-great#79]
### Date

ongoing

### Description

Hard to gauge the reliability but it seems pretty good at first glance. Big fan of your site; hope you find this helpful.

### Links

https://hacked.slowmist.io/en/statistics/?c=all&d=all

### Agreement

- [X] I irrevocably agree to release my contribution under the CC-BY 3.0 License

**Comment by molly** [comment]
Thanks, appreciate the tip!
