### ISSUE TITLE
[NEW]: Wyre, once worth $1.5 Billion, is Now Shutting Down

### ISSUE THREAD

**Issue by MetaVRse** [molly/web3-is-going-great#797]
### Date

2023-01-03

### Description

On Friday, employees received worse news: They were told via email the company was basically shutting down, as nearly all its employees were being let go.  Wyre did not respond to emails requesting comment, but CEO Ioannis Giannaros told [Axios via email](https://www.axios.com/2023/01/03/wyre-shutdown-crypto-winter) that the company is “still operating but will be scaling back to plan our next steps.”

### Links

https://sfstandard.com/business/this-crypto-startup-was-worth-1-5-billion-its-now-said-to-be-shutting-down/

### Agreement

- [X] I irrevocably agree to release my contribution under the CC-BY 3.0 License

### Attribution name

Alan

**Comment by molly** [comment]
Thanks! https://web3isgoinggreat.com/?id=crypto-payments-platform-wyre-to-shut-down-or-scale-back
