### ISSUE TITLE
Grift explainer link links to wrong page

### ISSUE THREAD

**Issue by R5201** [molly/web3-is-going-great#802]
# Entry
Grift counter 

# Changes
Change */about#grift-question to */faq#grift-question

# Agreement

By submitting this issue, I irrevocably agree to release my contribution under the [CC-BY 3.0 License](http://creativecommons.org/licenses/by/3.0/deed.en_US). I agree that a hyperlink or URL is sufficient attribution under the Creative Commons license.

Please attribute this contribution to:

- 
- 

You can leave this blank if this is a change so small as to not be copyrightable.

**Comment by R5201** [comment]
what. I didnt mean to create this, I clicked out of the text box

**Comment by molly** [comment]
Thanks! Forgot to deploy it :)
