### ISSUE TITLE
[NEW] Made the "flames" image in the bottom-right into a .gif and animated format for more flare

### ISSUE THREAD

**Issue by FlatBoulders** [molly/web3-is-going-great#81]
![flames](https://user-images.githubusercontent.com/38474413/152428576-93e74099-f217-491f-820a-8a792be857f8.gif)

**Comment by FlatBoulders** [comment]
To add this .gif to the website, replace `.grift-counter`'s `border-image-source` with `url(https://user-images.githubusercontent.com/38474413/152428576-93e74099-f217-491f-820a-8a792be857f8.gif)` (or you can just upload it to the server directly and link that URL).

`border-image-source: url(https://user-images.githubusercontent.com/38474413/152428576-93e74099-f217-491f-820a-8a792be857f8.gif);`

**Comment by FlatBoulders** [comment]
To add this .gif to the website, replace `.grift-counter`'s `border-image-source` with `url(https://user-images.githubusercontent.com/38474413/152428576-93e74099-f217-491f-820a-8a792be857f8.gif)` (or you can just upload it to the server directly and link that URL).

`border-image-source: url(https://user-images.githubusercontent.com/38474413/152428576-93e74099-f217-491f-820a-8a792be857f8.gif);`

**Comment by molly** [comment]
![Will Ferrell Hunger Games GIF: "Dear God, it's beautiful"](https://media1.giphy.com/media/V2AkNZZi9ygbm/giphy.gif?cid=ecf05e47y1n59o1ckqahu5gqxxsjreyhhhhbr6wois23vx5g&rid=giphy.gif&ct=g)
