### ISSUE TITLE
[NEW]: Paul Denino openly admits stealing half a mil defrauding his loyal followers

### ISSUE THREAD

**Issue by MrCsabaToth** [molly/web3-is-going-great#82]
### Date

2021-01-31

### Description

A popular streamer Paul Denino a.k.a. Ice Poseidon openly admits stealing more than $500K from his loyal followers and doesn't seems to be too much apologetic.

The community based CxCoin which was founded, hyped, and shilled by Denino to his followers. As with many web3 projects CxCoin had some various vague promises behind it like the development of an influencer donation platform - which never saw a light of a single day. Part of the shilling and marketing phase focused on silencing skeptics - including redaction of scam focused online news bit - or pressing them to give benefit of the doubt. Well before CxCoin Denino had several streams where he already planned out the foundation of a coin and promised the rug pull. Later he was swearing those were "jokes" only, and that is especially interesting given how CxCoin ended up. The almost mandatory "all money is there" promise was very loud, but from the get-go Denino already stole $200K from the liquidity fund leaving less than 10% in the reserves. Then he stole $250K allocated for marketing, and finally he finished off his own coin by rug-pulling $300K from under it. Coffeezilla (A YouTuber focusing on scams) interviewed Denino, during which Denino was unprecedentedly honest (unlike other influencer scammer, for example the Save The Kids mega-scam) and admitted pulling out all the money from various wallets and acknowledging keeping it to himself. Netting 750K is not too bad for two weeks of work (so maybe web3 is not that bad after all - at least for some select influencers), although he had to may his developers. Denino already purchased a Tesla shortly after getting hold of some of the coins. After Coffeezilla's report Denino must have done some very deep soul searching and "generously" put back less than $50K into the liquidity pool - we have to say: well done, what a gentleman!
BTW, I think the Save The Kids Scam is definitely worth mentioning because that was a milestone in how low the morale is: well known influencers repeatedly scam their own followers, in case of the Save The Kids it was widely marketed that an anti-whale clause prevented a rug-pull, but that code section was essentially disabled right before the coin went live and shortly after all the influencers and founders rug pulled. It is not even surprising that the frequent giveaway raffles surrounding crypto releases are rigged and influencers essentially gift even that money to each other behind the scenes.
In my view all of the above are part of the great Web 3 and show how wonderful it is.

### Links

https://www.youtube.com/watch?v=A7MaoD4tJuc
https://www.notebookcheck.net/Popular-YouTuber-steals-US-500-000-from-fans-and-shamelessly-buys-a-new-Tesla-with-the-money.597273.0.html

### Agreement

- [X] I irrevocably agree to release my contribution under the CC-BY 3.0 License

### Attribution name

@MrCsabaToth

**Comment by MrCsabaToth** [comment]
I know a measly $700K doesn't even hit rekt.news's 1 mil $ threshold, but the morale of these influencer scams are just another world.

**Comment by molly** [comment]
https://web3isgoinggreat.com?id=2022-01-31-0

**Comment by MrCsabaToth** [comment]
Not sure how I missed that!

**Comment by molly** [comment]
Planning to work on search this weekend! 😊

**Comment by MrCsabaToth** [comment]
> Planning to work on search this weekend! blush

Ok, I was sloppy, so I did a Google search `ice poseidon site:web3isgoinggreat.com` and that actually finds the `https://web3isgoinggreat.com/?id=2022-01-31-1` but in the hit list it's listed as `Tax season begins to hit crypto Reddit hard - Web3 is going ...` so I skimmed over. So Google does index into the content but the items cannot be indexed individually but only per day?

So a GCSE / Google Custom Search Engine can be enough as well https://cse.google.com/cse/all

I didn't find entry on save the kids though
