### ISSUE TITLE
[NEW]: add "apes" to the glossary

### ISSUE THREAD

**Issue by palmbardier** [molly/web3-is-going-great#83]
### Date

2022-02-04

### Description

I continue to see the term "apes" thrown around by crypto/NFT people.  Sounds like there might be some derogatory connotation to it.  Can you add this to the glossary of terms on your site to educate us noobs?

### Links

https://web3isgoinggreat.com/glossary

### Agreement

- [X] I irrevocably agree to release my contribution under the CC-BY 3.0 License

**Comment by molly** [comment]
Done!
