### ISSUE TITLE
[NEW]: Dutch central bank fines cryptocurrency exchange Coinbase 3.3 milion euros

### ISSUE THREAD

**Issue by JochemKuijpers** [molly/web3-is-going-great#837]
### Date

2023-01-256

### Description

Coinbase was fined 3.3 million euros ($3.6 million) by the Dutch Central Bank (DNB), for failing to obtain the correct registration in the Netherlands before offering services. The exchange should have obtained a registration when it became mandatory in May 2020, but did so 22 months too late, which means a potentially large amount of illegal transactions during this time could not be monitored correctly. DNB says the fine is higher than the minimum fine due to the serious nature of the infraction and culpability.

### Links

https://www.reuters.com/article/netherlands-coinbase-fine/dutch-central-bank-fines-cryptocurrency-exchange-coinbase-3-3-mln-euros-idUKA5N32P01H

https://nos.nl/artikel/2461283-miljoenenboete-van-dnb-voor-cryptobeurs-coinbase (Dutch)

### Agreement

- [X] I irrevocably agree to release my contribution under the CC-BY 3.0 License

### Attribution name

none

**Comment by molly** [comment]
Thanks! https://web3isgoinggreat.com/?id=coinbase-fined-3-6-million-by-dutch-central-bank
