### ISSUE TITLE
[EDIT] Can I ask that the link to my suspended Twitter account be removed from my name?

### ISSUE THREAD

**Issue by DPS2004** [molly/web3-is-going-great#84]
# Entry

https://web3isgoinggreat.com/attribution

# Changes

I would really appreciate it if my name was not a hyperlink to my suspended Twitter account, and instead was a link to my itch.io page. Sorry if this causes any trouble.

# Agreement
By submitting this issue, I irrevocably agree to release my contribution under the [CC-BY 3.0 License](http://creativecommons.org/licenses/by/3.0/deed.en_US). I agree that a hyperlink or URL is sufficient attribution under the Creative Commons license.

Please attribute this contribution to:
* 
DPS2004
* 
[dps2004.itch.io](https://dps2004.itch.io/)

**Comment by molly** [comment]
No problem, done!
