### ISSUE TITLE
[NEW]: 

### ISSUE THREAD

**Issue by paulehoffman** [molly/web3-is-going-great#859]
### Date

2023-02-08

### Description

Luxury brand Hermès International SA won its lawsuit against the digital artist behind “MetaBirkin” nonfungible tokens after convincing a Manhattan federal jury that Mason Rothschild’s sale of the NFTs violated Hermès’ rights to the “Birkin” trademark.

This is covered in nice detail in this afternoon's Money Stuff from Matt Levine, which I assume you subscribe to...

### Links

https://news.bloomberglaw.com/ip-law/hermes-gets-win-over-metabirkins-in-first-nft-trademark-trial

### Agreement

- [X] I irrevocably agree to release my contribution under the CC-BY 3.0 License

### Attribution name

Paul Hoffman

**Comment by molly** [comment]
Already covered at https://web3isgoinggreat.com/?id=creator-of-metabirkins-nfts-loses-trademark-infringement-lawsuit-from-herms, though thanks for the heads up that Matt Levine covered! I do subscribe, but hadn't gotten around to reading his latest.
