### ISSUE TITLE
Links at the bottom of a timeline entry are not clickable if they are bellow the top of the next entry

### ISSUE THREAD

**Issue by Jell** [molly/web3-is-going-great#86]
Tested on desktop in Firefox and Chrome.

Issue seems to be with the `timeline-entry` div covering the previous entry's body.

![image](https://user-images.githubusercontent.com/184571/152635025-5e0516aa-5550-4ea5-b72e-41825d63b907.png)

**Comment by Jell** [comment]
To clarify, in the above the two reference links "Team17" and "Worms publisher" are not clickable

**Comment by molly** [comment]
Thanks so much for the report and PR to fix! Closed in #87

**Comment by Jell** [comment]
Happy to help! keep up the good work @molly :muscle: :rocket:
