### ISSUE TITLE
"laundered" thingummy pops up empty

### ISSUE THREAD

**Issue by trick-knee** [molly/web3-is-going-great#877]
# Entry

in this story
https://web3isgoinggreat.com/?id=dexible-hacked-for-around-1-6-million
the word "laundered" is dash-underlined, as if an explanatory tooltip box should pop up.  but, when it does, the box is empty.  I have no idea what's going on there.

hopefully "tooltip" isn't part of terminology that is so old that it no longer has meaning.

# Changes

¯\_(ツ)_/¯

# Agreement

By submitting this issue, I irrevocably agree to release my contribution under the [CC-BY 3.0 License](http://creativecommons.org/licenses/by/3.0/deed.en_US). I agree that a hyperlink or URL is sufficient attribution under the Creative Commons license.

Please attribute this contribution to:

- 
- 

You can leave this blank if this is a change so small as to not be copyrightable.

**Comment by molly** [comment]
Thank you! (And yes, tooltip is what I'd call it!)
