### ISSUE TITLE
[EDIT]

### ISSUE THREAD

**Issue by dsghub** [molly/web3-is-going-great#888]
# Entry

https://web3isgoinggreat.com/?id=silvergate-crypto-focused-bank-faces-crisis
# Changes

Old:  They acknowledged that the bank's "ability to continue" was a "going concern".

New: They are still "evaluating ... their ability to continue as a going concern". 
Alternatively: They are still "evaluating" their ability to survive.

Background: "To continue as a going concern" is actually something positive, in the language of finance. It is what every copmany hopes to achieve. "Concern" here is not used as in something "concerning", something troublesome, but as in "venture", "living entity", or "to survive". 

# Agreement

By submitting this issue, I irrevocably agree to release my contribution under the [CC-BY 3.0 License](http://creativecommons.org/licenses/by/3.0/deed.en_US). I agree that a hyperlink or URL is sufficient attribution under the Creative Commons license.

Agreed. No attribution required. I transfer all my rights in this little snippet to you.
Daniel Sokolov

Please attribute this contribution to:

- 
- 

You can leave this blank if this is a change so small as to not be copyrightable.

**Comment by molly** [comment]
Appreciate it!
