### ISSUE TITLE
Attribution box doesn't work

### ISSUE THREAD

**Issue by VoidsHeiress** [molly/web3-is-going-great#89]
This actually broke in #87, since it inherits the pointer-events: none from its parent; So you can't close it or interact with it in any way.
I was already looking into this because of the overlap problems, but now it broke in a new unique way.

just give the lightbox class pointer-events:auto and it will work again.

**Comment by molly** [comment]
The original issue was caused by a regression in #76: https://github.com/molly/web3-is-going-great/pull/76/files#diff-f98830684453e538ebcdff92316da2dee800df6a4e18e8e47295e1a1dabec50eL194

Restoring that style fixes both problems. Thanks for reporting!
