### ISSUE TITLE
[NEW]: Crypto-focused bank Silvergate plans to wind down following blow from FTX

### ISSUE THREAD

**Issue by LochlanS** [molly/web3-is-going-great#901]
### Date

2023-03-08

### Description

March 8 (Reuters) - Crypto-focused bank Silvergate Capital Corp [(SI.N)](https://www.reuters.com/companies/SI.N) said on Wednesday it planned to wind down operations and voluntarily liquidate after it was hit with losses following the dramatic collapse of crypto exchange FTX, sending its shares down 35% in after-hours trade.

### Links

https://www.reuters.com/technology/crypto-focused-bank-silvergate-plans-wind-down-operations-2023-03-08/

### Agreement

- [X] I irrevocably agree to release my contribution under the CC-BY 3.0 License

### Attribution name

No attribution please

**Comment by molly** [comment]
https://web3isgoinggreat.com/?id=silvergate-bank-collapses
