### ISSUE TITLE
[NEW]: NFT developer Dynasty Loop owes employees $2 million in paychecks

### ISSUE THREAD

**Issue by Guendeli** [molly/web3-is-going-great#902]
### Date

2021-03-11

### Description

NFT developer Dynasty Loop owes employees $2 million in paychecks

### Links

https://www.polygon.com/23632736/dynasty-loop-unpaid-wages-allegations-montreal-canada

### Agreement

- [X] I irrevocably agree to release my contribution under the CC-BY 3.0 License

**Comment by molly** [comment]
Thanks! https://web3isgoinggreat.com/?id=dynasty-loop-nft-games-studio-allegedly-owes-millions-to-employees #914
