### ISSUE TITLE
[NEW]: Meta drops NFT support across it's family of apps. 

### ISSUE THREAD

**Issue by panderson54** [molly/web3-is-going-great#903]
### Date

2023-03-13

### Description

Meta drops NFT support across it's family of apps. "Some product news: across the company, we're looking closely at what we prioritize to increase our focus. We’re winding down digital collectibles (NFTs) for now to focus on other ways to support creators, people, and businesses. " -  Stephane Kasriel

### Links

https://twitter.com/skasriel/status/1635386565487898624

### Agreement

- [X] I irrevocably agree to release my contribution under the CC-BY 3.0 License

**Comment by molly** [comment]
Thanks! https://web3isgoinggreat.com/?id=meta-pulls-the-plug-on-nfts
