### ISSUE TITLE
[NEW]: NFT-backed restaurant in San Francisco's Salesforce Park goes silent

### ISSUE THREAD

**Issue by amebeefs** [molly/web3-is-going-great#904]
### Date

3-27-2023

### Description

According to SFGATE, Joshua Sigel's NFT-backed Japanese restaurant Sho has apparently been abandoned with no new social media activity since September 2022. The space itself remains empty save for the artist mock-ups, which appear to have remained "strewn about on the floor" since the project's unveiling.

### Links

https://www.sfgate.com/local/article/salesforce-park-sho-restaurant-goes-silent-17858831.php

### Agreement

- [X] I irrevocably agree to release my contribution under the CC-BY 3.0 License

**Comment by molly** [comment]
Updated the existing entry: https://web3isgoinggreat.com/?id=7500-300000-nft-holders-only-club-set-to-open-in-sf
