### ISSUE TITLE
[NEW]: Bittrex winds down operations in the US

### ISSUE THREAD

**Issue by YabosMcGee** [molly/web3-is-going-great#907]
### Date

2023-03-31

### Description

Bittrex winds down operations in the US due to "continued regulatory uncertainty".

### Links

https://bittrex.zendesk.com/hc/en-us/articles/10080271948701
https://www.coindesk.com/policy/2023/03/31/crypto-exchange-bittrex-to-wind-down-us-operations-next-month/
https://www.businesswire.com/news/home/20230331005339/en/Bittrex-Statement-on-U.S.-Operations

### Agreement

- [X] I irrevocably agree to release my contribution under the CC-BY 3.0 License

### Attribution name

YabosMcGee

**Comment by molly** [comment]
https://web3isgoinggreat.com/?id=bittrex-crypto-exchange-to-close-us-operations
