### ISSUE TITLE
[EDIT] Bittrex and Canada

### ISSUE THREAD

**Issue by dsghub** [molly/web3-is-going-great#908]
# Entry

https://web3isgoinggreat.com/?id=bittrex-crypto-exchange-to-close-us-operations

"Bittrex will continue operations outside of the US, and currently operate in Europe, Canada, and South America."

# Changes

I think they no longer operate in Canada, at least not out in the open. I was unable to access bittrex.com with a Canadian IP address.

Bittrex has stopped accepting new Canadian clients in May of 2022, see
https://bittrexglobal.zendesk.com/hc/en-us/articles/6448712770203-Notice-to-Canadian-Users-May-24-2022-

Given the new Canadian crypto-regulations
https://www.securities-administrators.ca/news/canadian-securities-regulators-strengthen-oversight-enhance-expectations-of-crypto-asset-trading-platforms-operating-in-canada/

and that Bittrex has not registered in Canada
https://www.securities-administrators.ca/crypto-trading-platforms-regulation-and-enforcement-actions/crypto-trading-platforms-authorized-to-do-business-with-canadians/

and has not even started the pre-registration process
https://www.securities-administrators.ca/crypto-trading-platforms-regulation-and-enforcement-actions/crypto-trading-platforms-that-have-filed-pre-registration-undertakings/

it is likely that continuted service to Canadian clients (other than winding down their accounts) would be a violation of Canadian securities regulations.

# Agreement

By submitting this issue, I irrevocably agree to release my contribution under the [CC-BY 3.0 License](http://creativecommons.org/licenses/by/3.0/deed.en_US). I agree that a hyperlink or URL is sufficient attribution under the Creative Commons license.

Please attribute this contribution to:

No attribution required. I transfer all rights in my contribution to Molly White.

**Comment by molly** [comment]
Thank you!
