### ISSUE TITLE
[EDIT] Russian Ponzi scheme collapses after defrauding investors of almost $1 billion

### ISSUE THREAD

**Issue by emilv** [molly/web3-is-going-great#91]
# Entry

Title: Russian Ponzi scheme collapses after defrauding investors of almost $1 billion
Published: 2021-07-31

# Changes

$95M is not "almost $1 billion". Suggest changing the title to: Russian Ponzi scheme collapses after defrauding investors of $95 million

# Agreement
By submitting this issue, I irrevocably agree to release my contribution under the [CC-BY 3.0 License](http://creativecommons.org/licenses/by/3.0/deed.en_US). I agree that a hyperlink or URL is sufficient attribution under the Creative Commons license.

Please attribute this contribution to:
* Emil Vikström

**Comment by molly** [comment]
Yikes, must've been half asleep writing that one 😅 Thank you!
