### ISSUE TITLE
[NEW]: Binance's derivatives license cancelled by Australian Regulators

### ISSUE THREAD

**Issue by sandervankasteel** [molly/web3-is-going-great#911]
### Date

2023-0406

### Description

Australia's corporate regulator on Thursday cancelled the Australian financial services licence held by an entity trading as cryptocurrency exchange Binance Australia Derivatives.

### Links

https://www.coindesk.com/business/2023/04/06/binance-australias-derivatives-license-cancelled-by-regulator/
https://www.binance.com/en-AU/blog/all/winding-down-of-binance-australia-derivatives-on-21-april-2023-5937431074265361443
https://decrypt.co/125572/financial-regulator-cancels-license-binances-derivatives-business-australia

### Agreement

- [X] I irrevocably agree to release my contribution under the CC-BY 3.0 License

### Attribution name

Sander van Kasteel

### Personal link

https://mastodon.online/@SuitedUpDev

**Comment by molly** [comment]
https://web3isgoinggreat.com/?collection=binance&id=binance-closes-its-derivatives-arm-in-australia
