### ISSUE TITLE
[NEW]: NYTimes environmental costs of bitcoin mining

### ISSUE THREAD

**Issue by bcb44** [molly/web3-is-going-great#912]
### Date

2023-3-10

### Description

The NYT did a really nice job of documenting the electrical usage of bitcoin miners and putting that into easily understandable terms. Also documents some of the fucked up stuff bitcoin miners have negotiated with power companies like having to pay them to turn off during the texas grids struggles two years ago. 

Maybe more of a essay than news

### Links

https://www.nytimes.com/2023/04/09/business/bitcoin-mining-electricity-pollution.html

### Agreement

- [X] I irrevocably agree to release my contribution under the CC-BY 3.0 License

**Comment by molly** [comment]
Thanks! Not really suited to the W3IGG format, but appreciate the link!
