### ISSUE TITLE
[NEW]: Niantic(of Pokemon Go fame) Shuts down Ingress Trading Post (for NFTs)

### ISSUE THREAD

**Issue by mxxcon** [molly/web3-is-going-great#913]
### Date

2023-04-10

### Description

> Niantic announced that the Ingress Trading Post is shutting down on June 9th. The Trading Post was a web3 project from the SpotX team, a web3 research and development group at Niantic, with the goal of connecting Ingress Agents around the world through digital Ingress Bio Cards.

### Links

https://community.ingress.com/en/discussion/21379/thank-you-for-all-your-support-trading-post-ingress-community/
https://tradingpost.nianticlabs.com/
https://www.spotx.games/

### Agreement

- [X] I irrevocably agree to release my contribution under the CC-BY 3.0 License

### Attribution name

Mxx

**Comment by molly** [comment]
https://web3isgoinggreat.com/?id=niantic-shutters-its-web3-project-after-less-than-six-months
