### ISSUE TITLE
[NEW]: Indie studio Dynasty Loop working on NFT & Metaverse projects hasn’t paid workers in months

### ISSUE THREAD

**Issue by grace7190** [molly/web3-is-going-great#914]
### Date

2023-03-09

### Description

Montreal-based Dynasty Loop, a studio working on video game projects involving NFTs and metaverse, has stopped paying employees since last December after months of unclear communication. Without clarifying if employees were being laid off or fired, this left many of its 20 or so employees in the lurch and having gone months without pay. Four employees are now suing the company after the CEO stopped responding to emails and redirected all communications to her lawyer. 

### Links

https://www.polygon.com/23632736/dynasty-loop-unpaid-wages-allegations-montreal-canada
https://www.lapresse.ca/affaires/entreprises/2023-04-01/jeux-video/fin-de-partie-abrupte-pour-des-employes-d-un-studio-montrealais.php

### Agreement

- [X] I irrevocably agree to release my contribution under the CC-BY 3.0 License

### Attribution name

no credit thanks!

**Comment by molly** [comment]
https://web3isgoinggreat.com/?id=dynasty-loop-nft-games-studio-allegedly-owes-millions-to-employees
