### ISSUE TITLE
[NEW]: Belgian cryptocurreny platform Bit4You supends its activities

### ISSUE THREAD

**Issue by sandervankasteel** [molly/web3-is-going-great#915]
### Date

2023-04-27

### Description

Bit4You, the first and only cryptocurrency lending platform in Belgium, said it is suspending its activities after CoinLoan, one of its main service providers, was declared insolvent by an Estonian court.

Estonia-based CoinLoan also no longer has the required registration as a custodian of virtual currencies, Bit4You said in a statement on its website.

### Links

https://bit4you.medium.com/en-suspension-of-activities-b0cd3ef54587

### Agreement

- [X] I irrevocably agree to release my contribution under the CC-BY 3.0 License

### Attribution name

Sander van Kasteel

### Personal link

https://mastodon.online/@SuitedUpDev

**Comment by molly** [comment]
Thank you! https://web3isgoinggreat.com/?id=bit4you-suspends-activities
