### ISSUE TITLE
[NEW]: Binance leaves the Canadian market

### ISSUE THREAD

**Issue by sandervankasteel** [molly/web3-is-going-great#918]
### Date

2023-05-12

### Description

Binance will withdraw from the Canadian market, the cryptocurrency exchange announced on Twitter on May 12. It called its withdrawal “proactive” as new guidance issued by Canadian regulators continues to take a toll on the country’s crypto industry.

### Links

https://cointelegraph.com/news/binance-calls-it-quits-in-canada-blames-new-rules
https://twitter.com/binance/status/1657099651210969088?s=20

### Agreement

- [X] I irrevocably agree to release my contribution under the CC-BY 3.0 License

### Attribution name

Sander van Kasteel

### Personal link

https://mastodon.online/@SuitedUpDev

**Comment by molly** [comment]
Thanks! https://web3isgoinggreat.com/?id=binance-exits-canada
