### ISSUE TITLE
[EDIT]

### ISSUE THREAD

**Issue by acaloiaro** [molly/web3-is-going-great#919]
# Entry

May 12, 2023

Fractional NFT ownership platform Tessera shuts down

# Changes

Change `if you've find` -> `if you've found`

# Agreement

By submitting this issue, I irrevocably agree to release my contribution under the [CC-BY 3.0 License](http://creativecommons.org/licenses/by/3.0/deed.en_US). I agree that a hyperlink or URL is sufficient attribution under the Creative Commons license.

Please attribute this contribution to:

**Comment by molly** [comment]
Thanks!
