### ISSUE TITLE
[NEW]: European Union has approved crypto regulation law (MiCA)

### ISSUE THREAD

**Issue by sandervankasteel** [molly/web3-is-going-great#920]
### Date

2023-05-16

### Description

The Economic and Financial Affairs Council of the European Union — comprising finance ministers of all member states — has given the green light to the highly-anticipated Markets in Crypto-Assets (MiCA) regulation after a vote on May 16.

Finance ministers from 27 member states [voted](https://www.consilium.europa.eu/en/general-secretariat/corporate-policies/transparency/open-data/voting-results/?meeting=3948) in favor of the MiCA bill, and amendments to several regulations and directives relating to the new legislation.

Two more pieces of legislation, including regulation on information accompanying transfers of funds and certain crypto assets, were also adopted by the European Parliament in conjunction with MiCA’s adoption

### Links

https://www.consilium.europa.eu/en/general-secretariat/corporate-policies/transparency/open-data/voting-results/?meeting=3948

https://cointelegraph.com/news/eu-council-approves-mica-regulations

### Agreement

- [X] I irrevocably agree to release my contribution under the CC-BY 3.0 License

### Attribution name

Sander van Kasteel

### Personal link

https://mastodon.online/@SuitedUpDev

**Comment by molly** [comment]
Mentioned in the newsletter, not as well suited to W3IGG.
