### ISSUE TITLE
[NEW]: Ex-CFO at Seattle startup accused of stealing $35m from former employer, blowing it all on crypto trades

### ISSUE THREAD

**Issue by Ajax-Al** [molly/web3-is-going-great#921]
### Date

2023-05-18

### Description

The former chief financial officer of a Seattle-based startup -- fabric -- stole $35 million of his employer’s money shortly after being told he was going to be fired, and then lost it by investing in cryptocurrency before the market crashed last year, according to a federal indictment returned by a grand jury Wednesday. Nevin Shetty, 39, is charged with  four counts of wire fraud.

### Links

https://www.seattletimes.com/business/seattle-startups-ex-cfo-accused-of-diverting-35m-losing-it-in-crypto-crash/

### Agreement

- [X] I irrevocably agree to release my contribution under the CC-BY 3.0 License

### Attribution name

@scoopharvey

**Comment by molly** [comment]
Thanks! https://web3isgoinggreat.com/?id=former-fabric-cfo-accused-of-siphoning-35-million-into-his-crypto-startup-and-losing-it-all
