### ISSUE TITLE
[NEW]: Binance mishandled funds and violated securities laws, according to SEC lawsuit

### ISSUE THREAD

**Issue by sandervankasteel** [molly/web3-is-going-great#922]
### Date

2023-06-05

### Description

The world’s largest cryptocurrency exchange Binance and its founder Changpeng Zhao are accused of misusing investor funds, operating as an unregistered exchange and violating a slew of U.S. securities laws in [a lawsuit filed by the SEC](https://www.sec.gov/files/litigation/complaints/2023/comp-pr2023-101.pdf).

Filed in the U.S. District Court for the District of Columbia, the Securities and Exchange Commission lawsuit on Monday lists thirteen charges against the firm — including commingling and divert customer assets to an entity Zhao owned called Sigma Chain.

Binance is a Cayman Islands limited liability company founded by Zhao and the charges are familiar to practices uncovered after the collapse of the second largest cryptocurrency exchange, FTX, last year.

The lawsuit lays out the extent to which the firms owners knew of the alleged legal violations: “Binance’s CCO bluntly admitted to another Binance compliance officer in December 2018, “we are operating as a fking unlicensed securities exchange in the USA bro.”

### Links

https://apnews.com/article/crypto-binance-treasury-sec-stocks-ba3ce6c0086d36650e97e80a1ba780b1

https://nos.nl/artikel/2477867-amerikaanse-beursautoriteit-start-fraudezaak-tegen-cryptoplatform-binance (Dutch national news)

https://cointelegraph.com/news/sec-sues-binance-in-us-district-court-for-unregistered-securities-operations

### Agreement

- [X] I irrevocably agree to release my contribution under the CC-BY 3.0 License

### Attribution name

Sander van Kasteel

### Personal link

https://mastodon.online/@SuitedUpDev

**Comment by molly** [comment]
Thanks, https://web3isgoinggreat.com/?id=sec-files-complaint-against-binance
