### ISSUE TITLE
[NEW]: Kraken Ordered to Hand Over User Information to IRS

### ISSUE THREAD

**Issue by patrickhwood** [molly/web3-is-going-great#925]
### Date

2023-06-30

### Description

Kraken has been ordered to submit a vast amount of user information to the IRS for an investigation into potential tax evasion.  The IRS stated it requires this information to investigate whether Kraken's users have failed to accurately report their taxes.

### Links

https://storage.courtlistener.com/recap/gov.uscourts.cand.407965/gov.uscourts.cand.407965.34.0.pdf
https://cointelegraph.com/news/kraken-ordered-by-court-disclose-user-data-irs-tax-compliance
https://fortune.com/crypto/2023/07/03/kraken-irs-wealthy-taxpayers-20000-judge-summons-transaction-records/

### Agreement

- [X] I irrevocably agree to release my contribution under the CC-BY 3.0 License

### Attribution name

Patrick Wood

**Comment by molly** [comment]
Thanks! https://web3isgoinggreat.com/?id=kraken-ordered-to-turn-over-user-information-to-us-tax-investigators
