### ISSUE TITLE
[NEW]: Regulator cancels license of FTX's Australian business

### ISSUE THREAD

**Issue by sandervankasteel** [molly/web3-is-going-great#928]
### Date

2023-07-19

### Description

Australia's securities regulator said on Wednesday it had cancelled the license of the local arm of collapsed U.S. cryptocurrency exchange FTX, effective from July 14.

Bahamas-headquartered FTX, once a star of the crypto industry with a $32 billion valuation in January 2023, [filed for U.S. bankruptcy protection](https://www.reuters.com/markets/currencies/rise-fall-crypto-exchange-ftx-2022-11-10/) last November, saying it was unable to completely repay customers who had deposited funds on its exchange.

### Links

https://www.reuters.com/technology/regulator-cancels-license-ftxs-australian-business-2023-07-19/

### Agreement

- [X] I irrevocably agree to release my contribution under the CC-BY 3.0 License

### Attribution name

Sander van Kasteel

### Personal link

mastodon.online/@SuitedUpDev

**Comment by jose8109** [comment]
a eso me refiero quieren colapsar el mundo?

**Comment by jose8109** [comment]
para hacerse millonarios 10 20 40 tipos cuando hablamos de hambre en casi todo el mundo, todos somos pepe y yo soy parte de el, he echo mucho, consideremos una solución en la cual ni ustedes me violencia mi privacidad, y yo pueda contribuir como todos los merecen es la familia pepe , no son 50 hombres o mujeres o cuantos fueran cuantos sonaron este momento cada uno que se haga cargo de lo que corresponda, esta es mi cuenta y volaron mi privacidad desde poner y cambiar situaciones de mi teléfono observar alterar situaciones y demas
