### ISSUE TITLE
[EDIT] fraude

### ISSUE THREAD

**Issue by jose8109** [molly/web3-is-going-great#929]
# Entry

# Changes

# Agreement

By submitting this issue, I irrevocably agree to release my contribution under the [CC-BY 3.0 License](http://creativecommons.org/licenses/by/3.0/deed.en_US). I agree that a hyperlink or URL is sufficient attribution under the Creative Commons license.

Please attribute this contribution to:

- 
- 

You can leave this blank if this is a change so small as to not be copyrightable.

**Comment by R3Ked** [comment]
10/10 submisison
