### ISSUE TITLE
[NEW]: Uniswap fires employee responsible for a $25k worth rug pull scam 

### ISSUE THREAD

**Issue by JimGalasyn** [molly/web3-is-going-great#931]
### Date

2023-08-12

### Description

Uniswap developer accused of misconduct with memecoin project, withdrawing liquidity and pocketing $25k in ETH. The exchange has fired the employee, citing misalignment with company values.

### Links

https://www.cryptopolitan.com/uniswap-fires-employee-responsible-for-scam/

### Agreement

- [X] I irrevocably agree to release my contribution under the CC-BY 3.0 License

**Comment by molly** [comment]
https://web3isgoinggreat.com/?id=frenstech-rug-pull
