### ISSUE TITLE
[NEW]: LastPass vaults starting to get cracked - crypto stolen

### ISSUE THREAD

**Issue by bcb44** [molly/web3-is-going-great#934]
### Date

2023-9-5

### Description

MetaMask CEO and other researchers are finding that lots of stolen crypto going to same/linked address, common link between thefts is that the users were all LastPass users. This is the first real example I've seen of LastPass vaults cracked and used in the wild. Fitting that it's crypto

### Links

https://krebsonsecurity.com/2023/09/experts-fear-crooks-are-cracking-keys-stolen-in-lastpass-breach/

### Agreement

- [X] I irrevocably agree to release my contribution under the CC-BY 3.0 License

**Comment by molly** [comment]
Thanks!
