### ISSUE TITLE
[NEW]: Glossary addition request ("sats")

### ISSUE THREAD

**Issue by Wintergalactic** [molly/web3-is-going-great#977]
### Date

2023-09-26

### Description

Can we add a glossary entry for "sats". I don't actually know what this means but see it on r/buttcoin all the time. 

### Links

n/a

### Agreement

- [X] I irrevocably agree to release my contribution under the CC-BY 3.0 License

**Comment by molly** [comment]
https://web3isgoinggreat.com/glossary#sats
