### ISSUE TITLE
[NEW]:  BigWhale get's hacked by $1.5 million

### ISSUE THREAD

**Issue by franz101** [molly/web3-is-going-great#993]
### Date

2023-10-03

### Description

Unfortunately, we suffered what seems to be a spoofing type or some other type of hack at about 2023-10-03 5:01:14 UTC, with one failed zApproveLoanGrant transaction, followed by a successful one - in addition to this, the 5% dev fees which were there in our dev / contract creator wallet were moved to an address

### Links

https://twitter.com/bigwhaleio/status/1709159020186173687

https://www.binance.com/en/feed/post/1260861

### Agreement

- [X] I irrevocably agree to release my contribution under the CC-BY 3.0 License

### Attribution name

@filmfranz

### Personal link

https://twitter.com/filmfranz

**Comment by molly** [comment]
Thank you! https://web3isgoinggreat.com/?id=bigwhale-hack
